<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetName>MUXTestInfra</TargetName>
    <Platforms>x86;x64;ARM64</Platforms>
    <TargetFramework>$(DotNetCoreTargetFrameworkMoniker)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsAppSdkTargetPlatformVersion)</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>$(TargetPlatformMinVersion)</SupportedOSPlatformVersion>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <DefineConstants Condition="$(SolutionName) == 'MUXControlsInnerLoop'">$(DefineConstants);INNERLOOP_BUILD</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="$(MicrosoftCsWinRTPackageVersion)" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Taef" Version="$(TaefNugetPackageVersion)" />
    <PackageReference Include="Microsoft.Windows.Apps.Test" Version="1.0.181205002" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />

    <!-- Must track $(WindowsTargetPlatformVersion): Microsoft.Windows.SDK.cpp.targets errors out if the
         package's UWP version does not match the TargetPlatformVersion implied by $(TargetFramework). -->
    <PackageReference Include="Microsoft.Windows.SDK.cpp" Version="$(MicrosoftWindowsSDKCppNugetPackageVersion)" />
  </ItemGroup>
  
  <ItemGroup>
    <BinplaceItem Include="$(OutDir)MUXTestInfra.dll">
      <Destination>$(TestBinplaceDestinationPath)\MUXTestInfra</Destination>
      </BinplaceItem>
  </ItemGroup>
</Project>
