// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace StaticLibInApp
{
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 Dummy;
    }
}
