// AUTOGENERATED_FOR_WINRT
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

#include "pch.h"
#include "common.h"

#include "InkToolBarFlyoutItemAutomationPeer.g.h"

class InkToolBarFlyoutItemAutomationPeer :
    public ReferenceTracker<InkToolBarFlyoutItemAutomationPeer, winrt::implementation::InkToolBarFlyoutItemAutomationPeerT>
{
public:
    InkToolBarFlyoutItemAutomationPeer(winrt::InkToolBarFlyoutItem owner) {};
};

