namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass ProgressBar : Windows.UI.Xaml.Controls.Primitives.RangeBase
{
    ProgressBar();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsIndeterminate{ get; set; };

    Boolean ShowError{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean ShowPaused{ get; set; };

    Windows.UI.Xaml.Controls.Primitives.ProgressBarTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty IsIndeterminateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowErrorProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowPausedProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty TemplateSettingsProperty{ get; };
}

}
