namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_NEEDS_DP_FIELD]
runtimeclass ProgressBarTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    Double ContainerAnimationStartPosition{ get; };
    Double ContainerAnimationEndPosition{ get; };
    Double Container2AnimationStartPosition{ get; };
    Double Container2AnimationEndPosition{ get; };
    Double ContainerAnimationMidPosition{ get; };
    Double IndicatorLengthDelta{ get; };
    Windows.UI.Xaml.Media.RectangleGeometry ClipRect{ get; };
   
    // TemplateSetting properties from WUXC for backwards compatibility.
    Double EllipseAnimationEndPosition{ get; };
    Double EllipseAnimationWellPosition{ get; };
    Double EllipseDiameter{ get; };
    Double EllipseOffset{ get; };
}

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ProgressBar : Windows.UI.Xaml.Controls.Primitives.RangeBase
{
    ProgressBar();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsIndeterminate{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean ShowError{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean ShowPaused{ get; set; };

    [MUX_PROPERTY_NEEDS_DP_FIELD]
    ProgressBarTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty IsIndeterminateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowErrorProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowPausedProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ProgressBarAutomationPeer : Windows.UI.Xaml.Automation.Peers.RangeBaseAutomationPeer
{
    ProgressBarAutomationPeer(MU_XC_NAMESPACE.ProgressBar owner);
}

}
