namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass ProgressBarTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    ProgressBarTemplateSettings();

    Double ContainerAnimationStartPosition;
    static Windows.UI.Xaml.DependencyProperty ContainerAnimationStartPositionProperty{ get; };

    Double ContainerAnimationEndPosition;
    static Windows.UI.Xaml.DependencyProperty ContainerAnimationEndPositionProperty{ get; };

    Double ContainerAnimationStartPosition2;
    static Windows.UI.Xaml.DependencyProperty ContainerAnimationStartPosition2Property{ get; };

    Double ContainerAnimationEndPosition2;
    static Windows.UI.Xaml.DependencyProperty ContainerAnimationEndPosition2Property{ get; };

    Double ContainerAnimationMidPosition;
    static Windows.UI.Xaml.DependencyProperty ContainerAnimationMidPositionProperty{ get; };

    Double IndicatorLengthDelta;
    static Windows.UI.Xaml.DependencyProperty IndicatorLengthDeltaProperty{ get; };

    Windows.UI.Xaml.Media.RectangleGeometry ClipRect;
    static Windows.UI.Xaml.DependencyProperty ClipRectProperty{ get; };

    // TemplateSetting properties from WUXC for backwards compatibility.
    Double EllipseAnimationEndPosition;
    static Windows.UI.Xaml.DependencyProperty EllipseAnimationEndPositionProperty{ get; };

    Double EllipseAnimationWellPosition;
    static Windows.UI.Xaml.DependencyProperty EllipseAnimationWellPositionProperty{ get; };

    Double EllipseDiameter;
    static Windows.UI.Xaml.DependencyProperty EllipseDiameterProperty{ get; };

    Double EllipseOffset;
    static Windows.UI.Xaml.DependencyProperty EllipseOffsetProperty{ get; };
}

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass ProgressBar : Windows.UI.Xaml.Controls.Primitives.RangeBase
{
    ProgressBar();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsIndeterminate{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean ShowError{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean ShowPaused{ get; set; };

    ProgressBarTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty IsIndeterminateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowErrorProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ShowPausedProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty TemplateSettingsProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass ProgressBarAutomationPeer : Windows.UI.Xaml.Automation.Peers.RangeBaseAutomationPeer
{
    ProgressBarAutomationPeer(MU_XC_NAMESPACE.ProgressBar owner);
}

}
