namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass SplitButtonAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer,
Windows.UI.Xaml.Automation.Provider.IExpandCollapseProvider,
Windows.UI.Xaml.Automation.Provider.IInvokeProvider
{
    SplitButtonAutomationPeer(MU_XC_NAMESPACE.SplitButton owner);
}

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ToggleSplitButtonAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer,
Windows.UI.Xaml.Automation.Provider.IExpandCollapseProvider,
Windows.UI.Xaml.Automation.Provider.IToggleProvider
{
    ToggleSplitButtonAutomationPeer(MU_XC_NAMESPACE.ToggleSplitButton owner);
}

}