namespace MU_XCP_NAMESPACE
{
[WUXC_VERSION_PREVIEW]
[webhosthidden]
[default_interface]
unsealed runtimeclass RadioButtonsElementFactory : MU_XC_NAMESPACE.ElementFactory
{
    RadioButtonsElementFactory();
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[default_interface]
unsealed runtimeclass ColumnMajorUniformToLargestGridLayout : MU_XC_NAMESPACE.NonVirtualizingLayout
{
    ColumnMajorUniformToLargestGridLayout();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Int32 MaximumColumns{ get; set; };
    static Windows.UI.Xaml.DependencyProperty MaximumColumnsProperty{ get; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Int32 ColumnSpacing{ get; set; };
    static Windows.UI.Xaml.DependencyProperty ColumnSpacingProperty{ get; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Int32 RowSpacing{ get; set; };
    static Windows.UI.Xaml.DependencyProperty RowSpacingProperty{ get; };
}

}
