namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("Items")]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass RadioButtons : Windows.UI.Xaml.Controls.Control
{
    RadioButtons();

    Object ItemsSource;
    Windows.Foundation.Collections.IVector<Object> Items{ get; };
    Object ItemTemplate;

    Windows.UI.Xaml.UIElement ContainerFromIndex(Int32 index);

    [MUX_DEFAULT_VALUE("-1")]
    Int32 SelectedIndex;
    Object SelectedItem;
    event Windows.UI.Xaml.Controls.SelectionChangedEventHandler SelectionChanged;

    [MUX_DEFAULT_VALUE("1")]
    Int32 MaxColumns;

    Object Header;
    Windows.UI.Xaml.DataTemplate HeaderTemplate;

    static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectedIndexProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectedItemProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MaxColumnsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HeaderTemplateProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass RadioButtonsAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    RadioButtonsAutomationPeer(MU_XC_NAMESPACE.RadioButtons owner);
}

}
