// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace BindTestbedCppWinRTModel
{
    [bindable]
    [default_interface]
    runtimeclass Animal
    {
        Animal();
        Animal(String name, String color);
        
        String Name{ get; };
        String Color{ get; };

        void Click_RegularArgsOnAnimal(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void Click_NoArgsOnAnimal();
        void Click_BaseArgsOnAnimal(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
        void Click_OverloadedArgsOnAnimal(Object sender, Object e);
    }
}
