namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass PipsPagerAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    PipsPagerAutomationPeer(MU_XC_NAMESPACE.PipsPager owner);
}

}

