<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetCoreTargetFrameworkMoniker)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsAppSdkTargetPlatformVersion)</TargetPlatformMinVersion>
    <RootNamespace>LibManagedDllSatellite</RootNamespace>
    <UseWinUI>true</UseWinUI>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
</Project>