//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.0.0-build.101+g12769c43d3
//       
//       Command:
//           LottieGen -Language Cppwinrt -WinUIVersion 2.4 -InputFile AnimatedChevronUpDownSmallVisualSource.json
//       
//       Input file:
//           AnimatedChevronUpDownSmallVisualSource.json (30476 bytes created 11:16-08:00 Mar 5 2021)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   323 |
// |--------------------------+-------|
// | Expression animators     |    49 |
// | KeyFrame animators       |    47 |
// | Reference parameters     |    50 |
// | Expression operations    |     4 |
// |--------------------------+-------|
// | Animated brushes         |     1 |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     2 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |    19 |
// | ShapeVisuals             |    18 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |    18 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
#include "pch.h"
#include "AnimatedVisuals\AnimatedChevronUpDownSmallVisualSource.h"
#include <winrt/Windows.Foundation.Metadata.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.UI.Composition.h>
#include "d2d1.h"
#include <d2d1_1.h>
#include <d2d1helper.h>
#include <Windows.Graphics.Interop.h>
#ifdef BUILD_WINDOWS
namespace ABI
{
#include <Windows.Graphics.Effects.Interop.h>
}
#else
#include <Windows.Graphics.Effects.Interop.h>
#endif
#include <winrt/Windows.Graphics.Effects.h>

using namespace winrt::Microsoft::UI::Xaml::Controls;
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Foundation::Numerics;
using namespace winrt::Windows::Graphics;
using namespace winrt::Windows::UI;
using namespace winrt::Windows::UI::Composition;
using TimeSpan = winrt::Windows::Foundation::TimeSpan;

namespace winrt::Microsoft::UI::Xaml::Controls::AnimatedVisuals
{
    CppWinRTActivatableClassWithBasicFactory(AnimatedChevronUpDownSmallVisualSource)
}
#include "AnimatedVisuals\AnimatedChevronUpDownSmallVisualSource.g.cpp"

class CanvasGeometry : public winrt::implements<CanvasGeometry,
    IGeometrySource2D,
    ::ABI::Windows::Graphics::IGeometrySource2DInterop>
{
    winrt::com_ptr<ID2D1Geometry> _geometry{ nullptr };

public:
    CanvasGeometry(winrt::com_ptr<ID2D1Geometry> geometry)
        : _geometry{ geometry }
    { }

    // IGeometrySource2D.
    winrt::com_ptr<ID2D1Geometry> Geometry() { return _geometry; }

    // IGeometrySource2DInterop.
    IFACEMETHODIMP GetGeometry(ID2D1Geometry** value) override
    {
        _geometry.copy_to(value);
        return S_OK;
    }

    // IGeometrySource2DInterop.
    IFACEMETHODIMP TryGetGeometryUsingFactory(ID2D1Factory*, ID2D1Geometry**) override
    {
        return E_NOTIMPL;
    }
};
class AnimatedChevronUpDownSmallVisualSource_AnimatedVisual : public winrt::implements<AnimatedChevronUpDownSmallVisualSource_AnimatedVisual,
        winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual,
        IClosable>
{
    winrt::com_ptr<ID2D1Factory> _d2dFactory{ nullptr };
    static constexpr int64_t c_durationTicks{ 40000000L };
    Compositor const _c{ nullptr };
    ExpressionAnimation const _reusableExpressionAnimation{ nullptr };
    CompositionPropertySet const _themeProperties{ nullptr };
    CompositionColorBrush _themeColor_Foreground{ nullptr };
    CompositionPathGeometry _pathGeometry{ nullptr };
    ContainerVisual _root{ nullptr };
    CubicBezierEasingFunction _cubicBezierEasingFunction_0{ nullptr };
    CubicBezierEasingFunction _cubicBezierEasingFunction_1{ nullptr };
    CubicBezierEasingFunction _cubicBezierEasingFunction_2{ nullptr };
    CubicBezierEasingFunction _cubicBezierEasingFunction_3{ nullptr };
    CubicBezierEasingFunction _cubicBezierEasingFunction_4{ nullptr };
    ExpressionAnimation _rootProgress{ nullptr };
    InsetClip _insetClip_0{ nullptr };
    StepEasingFunction _holdThenStepEasingFunction{ nullptr };
    StepEasingFunction _stepThenHoldEasingFunction{ nullptr };

    static void StartProgressBoundAnimation(
        CompositionObject target,
        winrt::hstring animatedPropertyName,
        CompositionAnimation animation,
        ExpressionAnimation controllerProgressExpression)
    {
        target.StartAnimation(animatedPropertyName, animation);
        const auto controller = target.TryGetAnimationController(animatedPropertyName);
        controller.Pause();
        controller.StartAnimation(L"Progress", controllerProgressExpression);
    }

    void BindProperty(
        CompositionObject target,
        winrt::hstring animatedPropertyName,
        winrt::hstring expression,
        winrt::hstring referenceParameterName,
        CompositionObject referencedObject)
    {
        _reusableExpressionAnimation.ClearAllParameters();
        _reusableExpressionAnimation.Expression(expression);
        _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
        target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
    }

    BooleanKeyFrameAnimation CreateBooleanKeyFrameAnimation(float initialProgress, bool initialValue)
    {
        const auto result = _c.CreateBooleanKeyFrameAnimation();
        result.Duration(TimeSpan{ c_durationTicks });
        result.InsertKeyFrame(initialProgress, initialValue);
        return result;
    }

    ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
    {
        const auto result = _c.CreateScalarKeyFrameAnimation();
        result.Duration(TimeSpan{ c_durationTicks });
        result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
        return result;
    }

    Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, winrt::float2 initialValue, CompositionEasingFunction initialEasingFunction)
    {
        const auto result = _c.CreateVector2KeyFrameAnimation();
        result.Duration(TimeSpan{ c_durationTicks });
        result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_00()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.916666687F, true);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_01()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.833333313F, true);
        result.InsertKeyFrame(0.916666687F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_02()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.791666687F, true);
        result.InsertKeyFrame(0.833333313F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_03()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.708333313F, true);
        result.InsertKeyFrame(0.791666687F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_04()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.625F, true);
        result.InsertKeyFrame(0.708333313F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_05()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.583333313F, true);
        result.InsertKeyFrame(0.625F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_06()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.541666687F, true);
        result.InsertKeyFrame(0.583333313F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_07()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.5F, true);
        result.InsertKeyFrame(0.541666687F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_08()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.458333343F, true);
        result.InsertKeyFrame(0.5F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_09()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.416666657F, true);
        result.InsertKeyFrame(0.458333343F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_10()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.375F, true);
        result.InsertKeyFrame(0.416666657F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_11()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.333333343F, true);
        result.InsertKeyFrame(0.375F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_12()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.291666657F, true);
        result.InsertKeyFrame(0.333333343F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_13()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.25F, true);
        result.InsertKeyFrame(0.291666657F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_14()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.166666672F, true);
        result.InsertKeyFrame(0.25F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_15()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.125F, true);
        result.InsertKeyFrame(0.166666672F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_16()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.0833333358F, true);
        result.InsertKeyFrame(0.125F, false);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    BooleanKeyFrameAnimation IsVisibleBooleanAnimation_17()
    {
        const auto result = CreateBooleanKeyFrameAnimation(0.0833333358F, false);
        return result;
    }

    winrt::com_ptr<CanvasGeometry> Geometry()
    {
        winrt::com_ptr<ID2D1PathGeometry> path{ nullptr };
        winrt::check_hresult(_d2dFactory->CreatePathGeometry(path.put()));
        winrt::com_ptr<ID2D1GeometrySink> sink{ nullptr };
        winrt::check_hresult(path->Open(sink.put()));
        sink->BeginFigure({ -3.54299998F, -1.79299998F }, D2D1_FIGURE_BEGIN_FILLED);
        sink->AddLine({ 0.0199999996F, 1.70700002F });
        sink->AddLine({ 3.48900008F, -1.71500003F });
        sink->EndFigure(D2D1_FIGURE_END_OPEN);
        winrt::check_hresult(sink->Close());
        auto result = winrt::make_self<CanvasGeometry>(path);
        return result;
    }

    // Color bound to theme property value: Foreground
    CompositionColorBrush ThemeColor_Foreground()
    {
        const auto result = _themeColor_Foreground = _c.CreateColorBrush();
        BindProperty(result, L"Color", L"ColorRGB(_theme.Foreground.W*1,_theme.Foreground.X,_theme.Foreground.Y,_theme.Foreground.Z)", L"_theme", _themeProperties);
        return result;
    }

    CompositionPathGeometry PathGeometry()
    {
        return _pathGeometry = _c.CreatePathGeometry(CompositionPath(CanvasGeometryToIGeometrySource2D(Geometry())));
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // Transforms for Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_00()
    {
        const auto result = _c.CreateSpriteShape(PathGeometry());
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(ThemeColor_Foreground());
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_180_0(), RootProgress());
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_00(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // Transforms for Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_01()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_180_1(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_01(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // Transforms for Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_02()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_180_2(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_02(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // Transforms for Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_03()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_180_to_0_0(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_03(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // Transforms for Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_04()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_180_to_0_1(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_04(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // Transforms for Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_05()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_180_to_0_2(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_05(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    // Transforms for Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_06()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_06(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    // Transforms for Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_07()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_07(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 10 -
    // PointerOverOffToPointerOverOn
    // Transforms for Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_08()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_180_3(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_08(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    // Transforms for Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_09()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.RotationAngleInDegrees(180.0F);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_09(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    // Transforms for Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_10()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.RotationAngleInDegrees(180.0F);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_10(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 07 -
    // PointerOverOnToPointerOverOff
    // Transforms for Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_11()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_180_to_0_3(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_11(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    // Transforms for Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_12()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_12(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    // Transforms for Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_13()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_13(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // Transforms for Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_14()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_180_4(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_14(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    // Transforms for Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_15()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.RotationAngleInDegrees(180.0F);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_15(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    // Transforms for Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_16()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.RotationAngleInDegrees(180.0F);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_16(), _rootProgress);
        return result;
    }

    // - PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // Transforms for Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // Scale(1,1,0)
    // Path 1
    CompositionSpriteShape SpriteShape_17()
    {
        const auto result = _c.CreateSpriteShape(_pathGeometry);
        result.Scale({ 4.0F, 4.0F });
        result.StrokeBrush(_themeColor_Foreground);
        result.StrokeDashCap(CompositionStrokeCap::Round);
        result.StrokeStartCap(CompositionStrokeCap::Round);
        result.StrokeEndCap(CompositionStrokeCap::Round);
        result.StrokeLineJoin(CompositionStrokeLineJoin::Round);
        result.StrokeMiterLimit(2.0F);
        StartProgressBoundAnimation(result, L"RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_180_to_0_4(), _rootProgress);
        StartProgressBoundAnimation(result, L"Offset", OffsetVector2Animation_17(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    ContainerVisual ContainerVisual_00()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(InsetClip_0());
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_00());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_00(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    ContainerVisual ContainerVisual_01()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_01());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_01(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    ContainerVisual ContainerVisual_02()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_02());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_02(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    ContainerVisual ContainerVisual_03()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_03());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_03(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    ContainerVisual ContainerVisual_04()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_04());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_04(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    ContainerVisual ContainerVisual_05()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_05());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_05(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    ContainerVisual ContainerVisual_06()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_06());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_06(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    ContainerVisual ContainerVisual_07()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_07());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_07(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
    ContainerVisual ContainerVisual_08()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_08());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_08(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    ContainerVisual ContainerVisual_09()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_09());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_09(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    ContainerVisual ContainerVisual_10()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_10());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_10(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
    ContainerVisual ContainerVisual_11()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_11());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_11(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    ContainerVisual ContainerVisual_12()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_12());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_12(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    ContainerVisual ContainerVisual_13()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_13());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_13(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    ContainerVisual ContainerVisual_14()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_14());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_14(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    ContainerVisual ContainerVisual_15()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_15());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_15(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    ContainerVisual ContainerVisual_16()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.IsVisible(false);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_16());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_16(), _rootProgress);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    ContainerVisual ContainerVisual_17()
    {
        const auto result = _c.CreateContainerVisual();
        result.Clip(_insetClip_0);
        result.Size({ 48.0F, 48.0F });
        // Scale:<1, 1>
        result.TransformMatrix({ 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.0F });
        // Transforms for Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
        // Scale(1,1,0)
        result.Children().InsertAtTop(ShapeVisual_17());
        StartProgressBoundAnimation(result, L"IsVisible", IsVisibleBooleanAnimation_17(), _rootProgress);
        return result;
    }

    // The root of the composition.
    ContainerVisual Root()
    {
        const auto result = _root = _c.CreateContainerVisual();
        const auto propertySet = result.Properties();
        propertySet.InsertScalar(L"Progress", 0.0F);
        propertySet.InsertScalar(L"t0", 0.0F);
        const auto children = result.Children();
        // PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
        children.InsertAtTop(ContainerVisual_00());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
        children.InsertAtTop(ContainerVisual_01());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
        children.InsertAtTop(ContainerVisual_02());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
        children.InsertAtTop(ContainerVisual_03());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
        children.InsertAtTop(ContainerVisual_04());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
        children.InsertAtTop(ContainerVisual_05());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
        children.InsertAtTop(ContainerVisual_06());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
        children.InsertAtTop(ContainerVisual_07());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
        children.InsertAtTop(ContainerVisual_08());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
        children.InsertAtTop(ContainerVisual_09());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
        children.InsertAtTop(ContainerVisual_10());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
        children.InsertAtTop(ContainerVisual_11());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
        children.InsertAtTop(ContainerVisual_12());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
        children.InsertAtTop(ContainerVisual_13());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
        children.InsertAtTop(ContainerVisual_14());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
        children.InsertAtTop(ContainerVisual_15());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
        children.InsertAtTop(ContainerVisual_16());
        // PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
        children.InsertAtTop(ContainerVisual_17());
        StartProgressBoundAnimation(propertySet, L"t0", t0ScalarAnimation_0_to_1(), _rootProgress);
        return result;
    }

    CubicBezierEasingFunction CubicBezierEasingFunction_0()
    {
        return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction({ 0.550000012F, 0.0F }, { 0.0F, 1.0F });
    }

    CubicBezierEasingFunction CubicBezierEasingFunction_1()
    {
        return _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction({ 0.850000024F, 0.0F }, { 0.449999988F, 1.0F });
    }

    CubicBezierEasingFunction CubicBezierEasingFunction_2()
    {
        return _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction({ 0.349999994F, 0.0F }, { 0.0F, 1.0F });
    }

    CubicBezierEasingFunction CubicBezierEasingFunction_3()
    {
        return _cubicBezierEasingFunction_3 = _c.CreateCubicBezierEasingFunction({ 0.166999996F, 0.166999996F }, { 0.0F, 1.0F });
    }

    CubicBezierEasingFunction CubicBezierEasingFunction_4()
    {
        return _cubicBezierEasingFunction_4 = _c.CreateCubicBezierEasingFunction({ 0.850000024F, 0.0F }, { 0.75F, 1.0F });
    }

    ExpressionAnimation RootProgress()
    {
        const auto result = _rootProgress = _c.CreateExpressionAnimation(L"_.Progress");
        result.SetReferenceParameter(L"_", _root);
        return result;
    }

    InsetClip InsetClip_0()
    {
        const auto result = _insetClip_0 = _c.CreateInsetClip();
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_180_0()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, StepThenHoldEasingFunction());
        result.InsertKeyFrame(0.9375F, 0.0F, HoldThenStepEasingFunction());
        result.InsertKeyFrame(0.995833337F, 180.0F, CubicBezierEasingFunction_0());
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_180_1()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.854166687F, 0.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.912500024F, 180.0F, _cubicBezierEasingFunction_0);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_180_2()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.791666687F, 0.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.829166651F, 180.0F, CubicBezierEasingFunction_3());
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 10 -
    // PointerOverOffToPointerOverOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 10 -
    // PointerOverOffToPointerOverOn Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_180_3()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.458333343F, 0.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.495833337F, 180.0F, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_180_4()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 0.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.1875F, 0.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.245833337F, 180.0F, _cubicBezierEasingFunction_0);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_180_to_0_0()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 180.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.729166687F, 180.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.787500024F, 0.0F, _cubicBezierEasingFunction_0);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_180_to_0_1()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 180.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.645833313F, 180.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.704166651F, 0.0F, _cubicBezierEasingFunction_0);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_180_to_0_2()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 180.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.583333313F, 180.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.620833337F, 0.0F, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 07 -
    // PointerOverOnToPointerOverOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 07 -
    // PointerOverOnToPointerOverOff Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_180_to_0_3()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 180.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.333333343F, 180.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.370833337F, 0.0F, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Rotation
    ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_180_to_0_4()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.0F, 180.0F, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.020833334F, 180.0F, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.0791666657F, 0.0F, _cubicBezierEasingFunction_0);
        return result;
    }

    ScalarKeyFrameAnimation t0ScalarAnimation_0_to_1()
    {
        const auto result = CreateScalarKeyFrameAnimation(0.416666687F, 0.0F, _stepThenHoldEasingFunction);
        result.SetReferenceParameter(L"_", _root);
        result.InsertKeyFrame(0.454166651F, 1.0F, _cubicBezierEasingFunction_3);
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_00()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_00());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_01()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_01());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_02()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_02());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_03()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_03());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_04()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_04());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_05()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_05());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_06()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_06());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_07()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_07());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 10 - PointerOverOffToPointerOverOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_08()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_08());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_09()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_09());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_10()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_10());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 07 - PointerOverOnToPointerOverOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_11()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_11());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_12()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_12());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_13()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_13());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_14()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_14());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_15()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_15());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_16()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_16());
        return result;
    }

    // PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // Shape tree root for layer: DownArrowRotate 2
    ShapeVisual ShapeVisual_17()
    {
        const auto result = _c.CreateShapeVisual();
        result.Size({ 48.0F, 48.0F });
        // ShapeGroup: Shape 1
        result.Shapes().Append(SpriteShape_17());
        return result;
    }

    StepEasingFunction HoldThenStepEasingFunction()
    {
        const auto result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
        result.IsFinalStepSingleFrame(true);
        return result;
    }

    StepEasingFunction StepThenHoldEasingFunction()
    {
        const auto result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
        result.IsInitialStepSingleFrame(true);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 18 - PressedOffToNormalOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_00()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 36.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.916666687F, { 24.1709995F, 36.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.9375F, { 24.1709995F, 38.6730003F }, CubicBezierEasingFunction_1());
        result.InsertKeyFrame(0.995833337F, { 24.1709995F, 23.9230003F }, CubicBezierEasingFunction_2());
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 17 - PressedOffToPointerOverOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_01()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 36.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.833333313F, { 24.1709995F, 36.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.854166687F, { 24.1709995F, 38.9230003F }, _cubicBezierEasingFunction_1);
        result.InsertKeyFrame(0.912500024F, { 24.1709995F, 13.9230003F }, _cubicBezierEasingFunction_2);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 16 - PressedOffToPressedOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_02()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 36.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.791666687F, { 24.1709995F, 36.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.829166651F, { 24.1709995F, 11.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 15 - PressedOnToNormalOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_03()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 11.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.708333313F, { 24.1709995F, 11.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.729166687F, { 24.1709995F, 9.64999962F }, CubicBezierEasingFunction_4());
        result.InsertKeyFrame(0.787500024F, { 24.1709995F, 23.9230003F }, _cubicBezierEasingFunction_2);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 14 - PressedOnToPointerOverOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_04()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 11.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.625F, { 24.1709995F, 11.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.645833313F, { 24.1709995F, 9.27499962F }, _cubicBezierEasingFunction_4);
        result.InsertKeyFrame(0.704166651F, { 24.1709995F, 31.4230003F }, _cubicBezierEasingFunction_2);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 13 - PressedOnToPressedOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_05()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 11.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.583333313F, { 24.1709995F, 11.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.620833337F, { 24.1709995F, 36.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 12 -
    // PointerOverOffToPressedOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 12 - PointerOverOffToPressedOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_06()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 31.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.541666687F, { 24.1709995F, 31.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.579166651F, { 24.1709995F, 36.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 11 - PointerOverOffToNormalOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_07()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 31.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.5F, { 24.1709995F, 31.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.541666687F, { 24.1709995F, 23.9230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 10 -
    // PointerOverOffToPointerOverOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 10 -
    // PointerOverOffToPointerOverOn Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_08()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 31.4230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.458333343F, { 24.1709995F, 31.4230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.495833337F, { 24.1709995F, 15.1730003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 09 - PointerOverOnToPressedOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_09()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 15.1730003F }, _stepThenHoldEasingFunction);
        result.SetReferenceParameter(L"_", _root);
        result.InsertKeyFrame(0.416666657F, { 24.1709995F, 15.1730003F }, _holdThenStepEasingFunction);
        result.InsertExpressionKeyFrame(0.454166651F, L"(Pow(1-_.t0,3)*Vector2(24.171,15.173))+(3*Square(1-_.t0)*_.t0*Vector2(24.171,14.548))+(3*(1-_.t0)*Square(_.t0)*Vector2(24.171,9.756001))+(Pow(_.t0,3)*Vector2(24.171,11.423))", _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.454166681F, { 24.1709995F, 11.4230003F }, _stepThenHoldEasingFunction);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 08 - PointerOverOnToNormalOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_10()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 15.1730003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.375F, { 24.1709995F, 15.1730003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.412499994F, { 24.1709995F, 23.9230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 07 -
    // PointerOverOnToPointerOverOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 07 -
    // PointerOverOnToPointerOverOff Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_11()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 15.1730003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.333333343F, { 24.1709995F, 15.1730003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.370833337F, { 24.1709995F, 31.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 06 - NormalOffToPressedOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_12()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.291666657F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.329166681F, { 24.1709995F, 36.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 05 -NormalOffToPointerOverOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_13()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.25F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.287499994F, { 24.1709995F, 31.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 04 - NormalOffToNormalOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_14()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.166666672F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.1875F, { 24.1709995F, 38.5480003F }, _cubicBezierEasingFunction_1);
        result.InsertKeyFrame(0.245833337F, { 24.1709995F, 23.9230003F }, _cubicBezierEasingFunction_2);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 03 - NormalOnToPressedOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_15()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.125F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.162499994F, { 24.1709995F, 11.4230003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    // - Transforms for Controls - 07 - Dropdown Rotate - 02 - NormalOnToPointerOverOn
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_16()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _stepThenHoldEasingFunction);
        result.InsertKeyFrame(0.0833333358F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.12083333F, { 24.1709995F, 15.1730003F }, _cubicBezierEasingFunction_3);
        return result;
    }

    // - - PreComp layer: Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // - Transforms for Controls - 07 - Dropdown Rotate - 01 - NormalOnToNormalOff
    // Scale(1,1,0)
    // ShapeGroup: Shape 1
    // Offset
    Vector2KeyFrameAnimation OffsetVector2Animation_17()
    {
        const auto result = CreateVector2KeyFrameAnimation(0.0F, { 24.1709995F, 23.9230003F }, _holdThenStepEasingFunction);
        result.InsertKeyFrame(0.020833334F, { 24.1709995F, 9.89999962F }, _cubicBezierEasingFunction_4);
        result.InsertKeyFrame(0.0791666657F, { 24.1709995F, 23.9230003F }, _cubicBezierEasingFunction_2);
        return result;
    }

    static IGeometrySource2D CanvasGeometryToIGeometrySource2D(winrt::com_ptr<CanvasGeometry> geo)
    {
        return geo.as<IGeometrySource2D>();
    }

public:
    AnimatedChevronUpDownSmallVisualSource_AnimatedVisual(
        Compositor compositor,
        CompositionPropertySet themeProperties)
        : _c{compositor}
        , _themeProperties{themeProperties}
        , _reusableExpressionAnimation(compositor.CreateExpressionAnimation())
    {
        winrt::check_hresult(D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED, _d2dFactory.put()));
        const auto _ = Root();
    }

    void Close()
    {
        if (_root)
        {
            _root.Close();
        }
    }

    TimeSpan Duration() const
    {
        return TimeSpan{ c_durationTicks };
    }

    Visual RootVisual() const
    {
        return _root;
    }

    winrt::float2 Size() const
    {
        return { 48.0F, 48.0F };
    }

    static bool IsRuntimeCompatible()
    {
        return winrt::Windows::Foundation::Metadata::ApiInformation::IsApiContractPresent(L"Windows.Foundation.UniversalApiContract", 7);
    }
};

winrt::float4 AnimatedChevronUpDownSmallVisualSource::ColorAsVector4(Color color)
{
    return { static_cast<float>(color.R), static_cast<float>(color.G), static_cast<float>(color.B), static_cast<float>(color.A) };
}

CompositionPropertySet AnimatedChevronUpDownSmallVisualSource::EnsureThemeProperties(Compositor compositor)
{
    if (_themeProperties == nullptr)
    {
        _themeProperties = compositor.CreatePropertySet();
        _themeProperties.InsertVector4(L"Foreground", ColorAsVector4((Color)_themeForeground));
    }

    return _themeProperties;
}

Color AnimatedChevronUpDownSmallVisualSource::Foreground()
{
    return _themeForeground;
}

void AnimatedChevronUpDownSmallVisualSource::Foreground(Color value)
{
    _themeForeground = value;
    if (_themeProperties != nullptr)
    {
        _themeProperties.InsertVector4(L"Foreground", ColorAsVector4((Color)_themeForeground));
    }
}

winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual AnimatedChevronUpDownSmallVisualSource::TryCreateAnimatedVisual(
    Compositor const& compositor)
{
    IInspectable diagnostics = nullptr;
    return TryCreateAnimatedVisual(compositor, diagnostics);
}

winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual AnimatedChevronUpDownSmallVisualSource::TryCreateAnimatedVisual(
    Compositor const& compositor,
    IInspectable& diagnostics)
{
    const auto _ = EnsureThemeProperties(compositor);
    diagnostics = nullptr;

    if (AnimatedChevronUpDownSmallVisualSource_AnimatedVisual::IsRuntimeCompatible())
    {
        return winrt::make<AnimatedChevronUpDownSmallVisualSource_AnimatedVisual>(
            compositor,
            _themeProperties);
    }

    return nullptr;
}

double AnimatedChevronUpDownSmallVisualSource::FrameCount()
{
    return 240.0;
}

double AnimatedChevronUpDownSmallVisualSource::Framerate()
{
    return 60.0;
}

TimeSpan AnimatedChevronUpDownSmallVisualSource::Duration()
{
    return TimeSpan{ 40000000L };
}

double AnimatedChevronUpDownSmallVisualSource::FrameToProgress(double frameNumber)
{
    return frameNumber / 240.0;
}

winrt::Windows::Foundation::Collections::IMapView<hstring, double> AnimatedChevronUpDownSmallVisualSource::Markers()
{
    return winrt::single_threaded_map<winrt::hstring, double>(
        std::map<winrt::hstring, double>
        {
            { L"NormalOnToNormalOff_Start", 0.0 },
            { L"NormalOnToNormalOff_End", 0.079375 },
            { L"NormalOnToPointerOverOn_Start", 0.0835416666666667 },
            { L"NormalOnToPointerOverOn_End", 0.121041666666667 },
            { L"NormalOnToPressedOn_Start", 0.125208333333333 },
            { L"NormalOnToPressedOn_End", 0.162708333333333 },
            { L"NormalOffToNormalOn_Start", 0.166875 },
            { L"NormalOffToNormalOn_End", 0.246041666666667 },
            { L"NormalOffToPointerOverOff_Start", 0.250208333333333 },
            { L"NormalOffToPointerOverOff_End", 0.287708333333333 },
            { L"NormalOffToPressedOff_Start", 0.291875 },
            { L"NormalOffToPressedOff_End", 0.329375 },
            { L"PointerOverOnToPointerOverOff_Start", 0.333541666666667 },
            { L"PointerOverOnToPointerOverOff_End", 0.371041666666667 },
            { L"PointerOverOnToNormalOn_Start", 0.375208333333333 },
            { L"PointerOverOnToNormalOn_End", 0.412708333333333 },
            { L"PointerOverOnToPressedOn_Start", 0.416875 },
            { L"PointerOverOnToPressedOn_End", 0.454375 },
            { L"PointerOverOffToPointerOverOn_Start", 0.458541666666667 },
            { L"PointerOverOffToPointerOverOn_End", 0.496041666666667 },
            { L"PointerOverOffToNormalOff_Start", 0.500208333333333 },
            { L"PointerOverOffToNormalOff_End", 0.537708333333333 },
            { L"PointerOverOffToPressedOff_Start", 0.541875 },
            { L"PointerOverOffToPressedOff_End", 0.579375 },
            { L"PressedOnToPressedOff_Start", 0.583541666666667 },
            { L"PressedOnToPressedOff_End", 0.621041666666667 },
            { L"PressedOnToPointerOverOff_Start", 0.625208333333333 },
            { L"PressedOnToPointerOverOff_End", 0.704375 },
            { L"PressedOnToNormalOff_Start", 0.708541666666667 },
            { L"PressedOnToNormalOff_End", 0.787708333333333 },
            { L"PressedOffToPressedOn_Start", 0.791875 },
            { L"PressedOffToPressedOn_End", 0.829375 },
            { L"PressedOffToPointerOverOn_Start", 0.833541666666667 },
            { L"PressedOffToPointerOverOn_End", 0.912708333333333 },
            { L"PressedOffToNormalOn_Start", 0.916875 },
            { L"PressedOffToNormalOn_End", 0.996041666666667 },
        }
    ).GetView();
}

void AnimatedChevronUpDownSmallVisualSource::SetColorProperty(hstring const& propertyName, Color value)
{
    if (propertyName == L"Foreground")
    {
        _themeForeground = value;
    }
    else
    {
        return;
    }

    if (_themeProperties != nullptr)
    {
        _themeProperties.InsertVector4(propertyName, ColorAsVector4(value));
    }
}

void AnimatedChevronUpDownSmallVisualSource::SetScalarProperty(hstring const&, double)
{
}
