//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "INotifyDataErrorInfoTests.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::BindTestbed::implementation
{
    using Application = ::winrt::Windows::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Windows::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Windows::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Windows::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Windows::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Windows::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void INotifyDataErrorInfoTestsT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            Uri resourceLocator{ L"ms-appx:///INotifyDataErrorInfoTests.xaml" };
            Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename... I>
    void INotifyDataErrorInfoTestsT<D, I...>::Connect(int32_t, IInspectable const&)
    {
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void INotifyDataErrorInfoTestsT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void INotifyDataErrorInfoTestsT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }


    template <typename D, typename... I>
    IComponentConnector INotifyDataErrorInfoTestsT<D, I...>::GetBindingConnector(int32_t, IInspectable const&)
    {
        return nullptr;
    }

    template struct INotifyDataErrorInfoTestsT<struct INotifyDataErrorInfoTests>;
}


namespace winrt::BindTestbed::implementation
{
::winrt::Windows::Foundation::IInspectable ActivateType_BindTestbed_INotifyDataErrorInfoTests()
{
    return ::winrt::make<::winrt::BindTestbed::implementation::INotifyDataErrorInfoTests>();
}

::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_DOErrorModel_BindTestbed_INotifyDataErrorInfoTests(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<::winrt::BindTestbed::INotifyDataErrorInfoTests>().DOErrorModel());
}

::winrt::Windows::Foundation::IInspectable GetReferenceTypeMember_ErrorModel_BindTestbed_INotifyDataErrorInfoTests(::winrt::Windows::Foundation::IInspectable const& instance)
{
    return ::winrt::box_value(instance.as<::winrt::BindTestbed::INotifyDataErrorInfoTests>().ErrorModel());
}
}

#pragma warning(pop)


