namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
enum RefreshPullDirection
{
    LeftToRight = 0,
    TopToBottom = 1,
    RightToLeft = 2,
    BottomToTop = 3,
};

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass RefreshContainer : Windows.UI.Xaml.Controls.ContentControl
{
    RefreshContainer();

    RefreshVisualizer Visualizer { get; set; };
    [MUX_DEFAULT_VALUE("winrt::RefreshPullDirection::TopToBottom")]
    RefreshPullDirection PullDirection { get; set; };
    event Windows.Foundation.TypedEventHandler<RefreshContainer, RefreshRequestedEventArgs> RefreshRequested;
    void RequestRefresh();

    static Windows.UI.Xaml.DependencyProperty VisualizerProperty { get; };
    static Windows.UI.Xaml.DependencyProperty PullDirectionProperty { get; };
}

}
