[WUXC_VERSION_RS4]
[webhosthidden]
enum RefreshPullDirection
{
    LeftToRight = 0,
    TopToBottom = 1,
    RightToLeft = 2,
    BottomToTop = 3,
};

[WUXC_VERSION_RS4]
[webhosthidden]
[WUXC_INTERFACE_NAME("IRefreshContainer", 535dc413-b1d5-43c1-b057-8658ce1e0ba2)]
[WUXC_STATIC_NAME("IRefreshContainerStatics", a20af5a5-7015-475d-9de3-81a0479dda38)]
[WUXC_CONSTRUCTOR_NAME("IRefreshContainerFactory", 0a04777f-089e-4239-baeb-c4641484c37e)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass RefreshContainer : Windows.UI.Xaml.Controls.ContentControl
{
    RefreshContainer();

    RefreshVisualizer Visualizer { get; set; };
    [MUX_DEFAULT_VALUE("winrt::RefreshPullDirection::TopToBottom")]
    RefreshPullDirection PullDirection { get; set; };
    event Windows.Foundation.TypedEventHandler<RefreshContainer, RefreshRequestedEventArgs> RefreshRequested;
    void RequestRefresh();

    static Windows.UI.Xaml.DependencyProperty VisualizerProperty { get; };
    static Windows.UI.Xaml.DependencyProperty PullDirectionProperty { get; };
}
