namespace MU_PRIVATE_CONTROLS_NAMESPACE
{
interface IRefreshInfoProviderAdapter;

[MUX_INTERNAL]
[webhosthidden]
interface IRefreshContainerPrivate
{
    IRefreshInfoProviderAdapter RefreshInfoProviderAdapter { get; set; };
}

}
