// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

//  Abstract:
//      Including this file gives the common core EventArgs types.

#pragma once

#include "RoutedEventArgs.h"
#include "InputPointEventArgs.h"
#include "DragEventArgs.h"
#include "KeyboardEventArgs.h"
#include "PointerEventArgs.h"
#include "DoubleTappedEventArgs.h"
#include "TappedEventArgs.h"
#include "HoldingEventArgs.h"
#include "ContextRequestedEventArgs.h"
#include "EffectiveViewportChangedEventArgs.h"
#include "RightTappedEventArgs.h"
#include "ManipulationEventArgs.h"
#include "ManipulationCompletedEventArgs.h"
#include "ManipulationDeltaEventArgs.h"
#include "ManipulationInertiaStartingEventArgs.h"
#include "ManipulationStartedEventArgs.h"
#include "ManipulationStartingEventArgs.h"
#include "ChangedPropertyEventArgs.h"
#include "CharacterReceivedEventArgs.h"
#include "IsEnabledChangedEventArgs.h"
#include "ContextMenuEventArgs.h"
#include "VisualStateChangedEventArgs.h"
#include "RenderingEventArgs.h"
#include "RenderedEventArgs.h"
#include "SizeChangedEventArgs.h"
#include "TextChangedEventArgs.h"
#include "TextControlPasteEventArgs.h"
#include "TextControlCopyingToClipboardEventArgs.h"
#include "TextControlCuttingToClipboardEventArgs.h"
#include "TextCompositionEventArgs.h"
#include "CandidateWindowBoundsChangedEventArgs.h"
#include "ExceptionRoutedEventArgs.h"
#include "HoldingEventArgs.h"
#include "DownloadProgressEventArgs.h"
#include "RateChangedRoutedEventArgs.h"
#include "SplitViewPaneClosingEventArgs.h"
#include "FocusedElementRemovedEventArgs.h"
#include "AccessKeyInvokedEventArgs.h"
#include "AccessKeyShownEventArgs.h"
#include "SvgImageSourceFailedEventArgs.h"
#include "GettingFocusEventArgs.h"
#include "LosingFocusEventArgs.h"
#include "LoadedImageSourceLoadCompletedEventArgs.h"
#include "NoFocusCandidateFoundEventArgs.h"
#include "CKeyboardAcceleratorInvokedEventArgs.h"
#include "BringIntoViewRequestedEventArgs.h"
#include "ValidationErrorEventArgs.h"
#include "HasValidationErrorsChangedEventArgs.h"
#include "FocusManagerLostFocusEventArgs.h"
#include "FocusManagerGotFocusEventArgs.h"
#include "ComboBoxTextSubmittedEventArgs.h"
