// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

#define TEXT_DATEPICKERFLYOUT_TITLE 5030
#define TEXT_TIMEPICKERFLYOUT_TITLE 5031
#define TEXT_LISTPICKERFLYOUT_TITLE 5032

#define TEXT_PICKERFLYOUTBASE_ACCEPTBTNLABEL 5130
#define TEXT_PICKERFLYOUTBASE_CANCELBTNLABEL 5131

#define UIA_AP_DATEPICKER_NAME 5230
#define UIA_AP_DATEPICKER_DAYNAME 5231
#define UIA_AP_DATEPICKER_MONTHNAME 5232
#define UIA_AP_DATEPICKER_YEARNAME 5233
#define UIA_AP_TIMEPICKER_NAME 5234
#define UIA_AP_TIMEPICKER_MINUTENAME 5235
#define UIA_AP_TIMEPICKER_HOURNAME 5236
#define UIA_AP_TIMEPICKER_PERIODNAME 5237
#define UIA_AP_LISTPICKERFLYOUT_NAME 5238
#define UIA_AP_PICKERFLYOUT_NAME 5239

#define UIA_AP_MAP_NAME 5240
#define UIA_AP_MAP_FORMATTEDNAME_ALL 5241
#define UIA_AP_MAP_FORMATTEDNAME_DISTANCE 5242
#define UIA_AP_MAP_FORMATTEDNAME_NOLOCATION 5243

#define UIA_AP_MAP_HEADING_NORTH 5250
#define UIA_AP_MAP_HEADING_NORTHEAST 5251
#define UIA_AP_MAP_HEADING_NORTHWEST 5252
#define UIA_AP_MAP_HEADING_EAST 5253
#define UIA_AP_MAP_HEADING_WEST 5254
#define UIA_AP_MAP_HEADING_SOUTH 5255
#define UIA_AP_MAP_HEADING_SOUTHEAST 5256
#define UIA_AP_MAP_HEADING_SOUTHWEST 5257
#define UIA_AP_MAP_HEADING_FORMATTEDSTRING 5258

#define UIA_AP_MAP_UNIT_MILE 5260
#define UIA_AP_MAP_UNIT_MILES 5261
#define UIA_AP_MAP_UNIT_FOOT 5262
#define UIA_AP_MAP_UNIT_FEET 5263
#define UIA_AP_MAP_UNIT_YARD 5264
#define UIA_AP_MAP_UNIT_YARDS 5265
#define UIA_AP_MAP_UNIT_KILOMETER 5266
#define UIA_AP_MAP_UNIT_KILOMETERS 5267
#define UIA_AP_MAP_UNIT_METER 5268
#define UIA_AP_MAP_UNIT_METERS 5269

// please do not conflict with resources ids in xcperrorresource.h when this actually merges.
// let's use ids from 5600 onwards.
#define UIA_CONTROLTYPE_PIVOT 5600
#define UIA_CONTROLTYPE_PIVOTITEM 5601
#define UIA_DIALOG_ACCEPT 5602
#define UIA_DIALOG_DISMISS 5603

#define IDS_ELEMENT_ENABLED_ONLY_IN_APP 5300 // Used in designer for elements that are not enabled
#define IDS_MAP_MISSING_CREDENTIALS_WARNING 5301
