namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IIconSource", 92ec8d55-45eb-47a4-863c-91b224044f9b)]
[WUXC_STATIC_NAME("IIconSourceStatics", 1d389dbe-1cd3-4f4f-83b0-55dc6387685b)]
[WUXC_CONSTRUCTOR_NAME("IIconSourceFactory", 4d117cf1-1fd6-49d7-b483-02ec3de997d6)]
unsealed runtimeclass IconSource : Windows.UI.Xaml.DependencyObject
{
    Windows.UI.Xaml.Media.Brush Foreground { get; set; };

    static Windows.UI.Xaml.DependencyProperty ForegroundProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("ISymbolIconSource", 625d95a2-b6b1-408a-b289-eab2ecba62d8)]
[WUXC_STATIC_NAME("ISymbolIconSourceStatics", 8bc49738-d94e-4148-8d64-1adf0f23f25f)]
[WUXC_CONSTRUCTOR_NAME("ISymbolIconSourceFactory", a526aab0-4130-4907-b049-21f9240c7a40)]
unsealed runtimeclass SymbolIconSource : IconSource
{
    SymbolIconSource();

    [MUX_DEFAULT_VALUE("winrt::Symbol::Emoji")]
    Windows.UI.Xaml.Controls.Symbol Symbol { get; set; };

    static Windows.UI.Xaml.DependencyProperty SymbolProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IFontIconSource", 2211ac9a-74e3-43ed-b61c-21afc7df4d10)]
[WUXC_STATIC_NAME("IFontIconSourceStatics", 8c0e422f-8269-43b1-b95a-ef070e86770d)]
[WUXC_CONSTRUCTOR_NAME("IFontIconSourceFactory", 8bdcf6bd-fc06-42b8-b30b-7505082ac38f)]
unsealed runtimeclass FontIconSource : IconSource
{
    FontIconSource();

    String Glyph { get; set; };
    [MUX_DEFAULT_VALUE("20.0")]
    Double FontSize { get; set; };
    [MUX_DEFAULT_VALUE("winrt::FontFamily{ c_fontIconSourceDefaultFontFamily }")]
    Windows.UI.Xaml.Media.FontFamily FontFamily { get; set; };
    [MUX_DEFAULT_VALUE("{ 400 }")]
    Windows.UI.Text.FontWeight FontWeight { get; set; };
    [MUX_DEFAULT_VALUE("winrt::FontStyle::Normal")]
    Windows.UI.Text.FontStyle FontStyle { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean IsTextScaleFactorEnabled { get; set; };
    Boolean MirroredWhenRightToLeft { get; set; };

    static Windows.UI.Xaml.DependencyProperty GlyphProperty { get; };
    static Windows.UI.Xaml.DependencyProperty FontSizeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty FontFamilyProperty { get; };
    static Windows.UI.Xaml.DependencyProperty FontWeightProperty { get; };
    static Windows.UI.Xaml.DependencyProperty FontStyleProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsTextScaleFactorEnabledProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MirroredWhenRightToLeftProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IBitmapIconSource", c8e33dc7-d4ae-4a87-947f-ac4d0bcf5af4)]
[WUXC_STATIC_NAME("IBitmapIconSourceStatics", 5a105887-e494-4d2b-8528-39472296133f)]
[WUXC_CONSTRUCTOR_NAME("IBitmapIconSourceFactory", 6509e5c6-44b6-4cd1-86cd-c3189b12c43c)]
unsealed runtimeclass BitmapIconSource : IconSource
{
    BitmapIconSource();

    Windows.Foundation.Uri UriSource { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean ShowAsMonochrome { get; set; };

    static Windows.UI.Xaml.DependencyProperty UriSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ShowAsMonochromeProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IPathIconSource", 1f47010e-b305-4863-8b7a-15d08d633c7a)]
[WUXC_STATIC_NAME("IPathIconSourceStatics", df7027d5-3682-43ff-80f0-afa256b2fdc3)]
[WUXC_CONSTRUCTOR_NAME("IPathIconSourceFactory", 8f7f85b9-5247-4f3b-833f-e384bf7e9c84)]
unsealed runtimeclass PathIconSource : IconSource
{
    PathIconSource();

    Windows.UI.Xaml.Media.Geometry Data { get; set; };

    static Windows.UI.Xaml.DependencyProperty DataProperty { get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass ImageIconSource : IconSource
{
    ImageIconSource();

    Windows.UI.Xaml.Media.ImageSource ImageSource{ get; set; };

    static Windows.UI.Xaml.DependencyProperty ImageSourceProperty{ get; };
}

}
