
copy C:\repo\microsoft-ui-xaml\dev\AutoSuggestBox\AutoSuggestBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\AutoSuggestBox\AutoSuggestBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CalendarDatePicker\CalendarDatePicker_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CalendarDatePicker\CalendarDatePicker_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CalendarView\CalendarView_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CalendarView\CalendarView_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CheckBox\CheckBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CheckBox\CheckBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorPicker.xaml D:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorPicker_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorPicker_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorPicker_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorSpectrum.xaml D:\repo\microsoft-ui-xaml\dev\ColorPicker\ColorSpectrum_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ComboBox\ComboBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ComboBox\ComboBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommandBarFlyout\CommandBarFlyout.xaml D:\repo\microsoft-ui-xaml\dev\CommandBarFlyout\CommandBarFlyout_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommandBarFlyout\CommandBarFlyout_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommandBarFlyout\CommandBarFlyout_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\Common_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\Common_themeresources_v2.5.xaml
echo copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\HyperlinkButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\HyperlinkButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\RadioButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\RadioButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\AppBarButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\AppBarButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\AppBarToggleButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\AppBarToggleButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\ListBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\ListBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\RichEditBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\RichEditBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\ToggleSwitch_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\ToggleSwitch_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\CommandBar_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\CommandBar_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\PasswordBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\PasswordBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\ListViewItem_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\ListViewItem_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\TextBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\TextBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\FlyoutPresenter_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\FlyoutPresenter_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\Button_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\Button_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\ToggleButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\ToggleButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\CornerRadius_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\CornerRadius_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\ProgressBar_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\ProgressBar_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\MediaTransportControls_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\MediaTransportControls_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\CommonStyles\RepeatButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\CommonStyles\RepeatButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ContentDialog\ContentDialog_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ContentDialog\ContentDialog_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\DatePicker\DatePicker_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\DatePicker\DatePicker_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\DatePicker\DateTimePickerFlyout_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\DatePicker\DateTimePickerFlyout_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton_rs1.xaml D:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton_rs1_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton.xaml D:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton_v2.5.xaml
echo copy C:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\DropDownButton\DropDownButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\Expander\Expander.xaml D:\repo\microsoft-ui-xaml\dev\Expander\Expander_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\Expander\Expander_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\Expander\Expander_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\FlipView\FlipView_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\FlipView\FlipView_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\FlipView\FlipViewItem_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\FlipView\FlipViewItem_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ImageIcon\ImageIcon.xaml D:\repo\microsoft-ui-xaml\dev\ImageIcon\ImageIcon_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ImageIcon\ImageIcon_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ImageIcon\ImageIcon_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\InfoBar\InfoBar.xaml D:\repo\microsoft-ui-xaml\dev\InfoBar\InfoBar_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\InfoBar\InfoBar_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\InfoBar\InfoBar_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBar.xaml D:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBar_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBarItem.xaml D:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBarItem_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBar_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\MenuBar\MenuBar_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\MenuFlyout\MenuFlyout_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\MenuFlyout\MenuFlyout_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView.xaml D:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView_rs2_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationView_rs2_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationBackButton.xaml D:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationBackButton_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationBackButton_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\NavigationView\NavigationBackButton_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NumberBox\NumberBox.xaml D:\repo\microsoft-ui-xaml\dev\NumberBox\NumberBox_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\NumberBox\NumberBox_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\NumberBox\NumberBox_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PagerControl\PagerControl.xaml D:\repo\microsoft-ui-xaml\dev\PagerControl\PagerControl_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PagerControl\PagerControl_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\PagerControl\PagerControl_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PersonPicture\PersonPicture.xaml D:\repo\microsoft-ui-xaml\dev\PersonPicture\PersonPicture_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PersonPicture\PersonPicture_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\PersonPicture\PersonPicture_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PipsPager\PipsPager.xaml D:\repo\microsoft-ui-xaml\dev\PipsPager\PipsPager_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\PipsPager\PipsPager_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\PipsPager\PipsPager_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\Pivot\Pivot_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\Pivot\Pivot_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ProgressBar\ProgressBar.xaml D:\repo\microsoft-ui-xaml\dev\ProgressBar\ProgressBar_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ProgressRing\ProgressRing.xaml D:\repo\microsoft-ui-xaml\dev\ProgressRing\ProgressRing_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ProgressRing\ProgressRing_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ProgressRing\ProgressRing_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButtons.xaml D:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButtons_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButtons_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButtons_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButton.xaml D:\repo\microsoft-ui-xaml\dev\RadioButtons\RadioButton_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs2_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs2_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs4_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs4_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs5_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RadioMenuFlyoutItem\RadioMenuFlyoutItem_rs5_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RatingControl\RatingControl.xaml D:\repo\microsoft-ui-xaml\dev\RatingControl\RatingControl_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\RatingControl\RatingControl_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\RatingControl\RatingControl_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ScrollBar\ScrollBar_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ScrollBar\ScrollBar_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView.xaml D:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs3_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs3_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs4_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ScrollView\ScrollView_rs4_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\Slider\Slider_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\Slider\Slider_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton.xaml D:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton_rs1.xaml D:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton_rs1_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\SplitButton\SplitButton_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SplitView\SplitView_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\SplitView\SplitView_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl.xaml D:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl_rs1.xaml D:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl_rs1_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\SwipeControl\SwipeControl_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TabView\TabView.xaml D:\repo\microsoft-ui-xaml\dev\TabView\TabView_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TabView\TabView_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\TabView\TabView_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip.xaml D:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip_rs2_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\TeachingTip\TeachingTip_rs2_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TimePicker\TimePicker_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\TimePicker\TimePicker_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ToolTip\ToolTip_rs1_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ToolTip\ToolTip_rs1_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\ToolTip\ToolTip_rs5_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\ToolTip\ToolTip_rs5_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TreeView\TreeView.xaml D:\repo\microsoft-ui-xaml\dev\TreeView\TreeView_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TreeView\TreeViewItem.xaml D:\repo\microsoft-ui-xaml\dev\TreeView\TreeViewItem_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TreeView\TreeView_themeresources.xaml D:\repo\microsoft-ui-xaml\dev\TreeView\TreeView_themeresources_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TwoPaneView\TwoPaneView_rs1.xaml D:\repo\microsoft-ui-xaml\dev\TwoPaneView\TwoPaneView_rs1_v2.5.xaml
copy C:\repo\microsoft-ui-xaml\dev\TwoPaneView\TwoPaneView.xaml D:\repo\microsoft-ui-xaml\dev\TwoPaneView\TwoPaneView_v2.5.xaml
