// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

#define SUBLANG_ENGLISH_US              0x01
#define LANG_ENGLISH                    0x09
#define IMAGE_RULE_TITLE                102
#define IMAGE_RULE_IMPACT               103
#define IMAGE_RULE_SOLUTION             104
#define IMAGE_RULE_LINK_TITLE           105
#define IMAGE_RULE_DESCRIPTION          107
#define IMAGE_RULE_SYNCDECODE           108
#define IMAGE_RULE_NOTLIVE              109
#define IMAGE_RULE_SOFTWARERENDERING    110
#define IMAGE_RULE_DRAGDROP             111
#define IMAGE_RULE_BITMAPICON           112
#define IMAGE_RULE_USESIMAGETILING      113
#define IMAGE_RULE_EMPTYBOUNDS          114
#define IMAGE_RULE_NINEGRID             115
#define IMAGE_RULE_DECODESIZESPECIFIED  116
#define COLLAPSED_ELEMENTS_TITLE        120
#define COLLAPSED_ELEMENTS_SOLUTION     121
#define COLLAPSED_ELEMENTS_IMPACT       122
#define COLLAPSED_ELEMENTS_DESCRIPTION  123
#define COLLAPSED_ELEMENTS_DESCRIPTION_NO_NAME  124
#define COLLAPSED_ELEMENTS_LINK_TITLE   125
#define LV_DEVIRTUALIZED_TITLE          127
#define LV_DEVIRTUALIZED_PANEL_SOLUTION 128
#define LV_DEVIRTUALIZED_LAYOUT_SOLUTION 129
#define LV_DEVIRTUALIZED_LAYOUT_DESCRIPTION_NO_NAME 130
#define LV_DEVIRTUALIZED_LAYOUT_DESCRIPTION 131
#define LV_DEVIRTUALIZED_IMPACT         132
#define LV_DEVIRTUALIZED_LINK_TITLE     136
#define UI_THREAD_UTILIZATION_TITLE     138
#define UI_THREAD_UTILIZATION_IMPACT    139
#define UI_THREAD_UTILIZATION_LINK_TITLE 140
#define UI_THREAD_UTILIZATION_DESCRIPTION 142
#define UI_THREAD_UTILIZATION_SOLUTION  143
#define UI_THREAD_UTILIZATION_NOTIFICATION_DESCRIPTION 144
#define DYNAMIC_BINDING_TITLE           151
#define DYNAMIC_BINDING_IMPACT          152
#define DYNAMIC_BINDING_DESCRIPTION     153
#define DYNAMIC_BINDING_SOLUTION        154
#define DYNAMIC_BINDING_LINK_TITLE      155
#define DYNAMIC_BINDING_DESCRIPTION_NO_NAME 156
#define DYNAMIC_BINDING_DETAILED_DESCRIPTION 157
#define ACC_NO_NAME_TITLE               159
#define ACC_NO_NAME_IMPACT              160
#define ACC_NO_NAME_SOLUTION            161
#define ACC_NO_NAME_DESCRIPTION         162
#define ACC_NO_NAME_LINK_TITLE          163
#define ACC_NO_NAME_DESCRIPTION_NO_NAME 164
#define ACC_NAME_DUPLICATE_TITLE        166
#define ACC_NAME_DUPLICATE_IMPACT       167
#define ACC_NAME_DUPLICATE_SOLUTION     168
#define ACC_NAME_DUPLICATE_DESCRIPTION  169
#define ACC_NAME_DUPLICATE_LINK_TITLE   170
#define RESOURCE_USING_XNAME_TITLE        171
#define RESOURCE_USING_XNAME_IMPACT       172
#define RESOURCE_USING_XNAME_SOLUTION     173
#define RESOURCE_USING_XNAME_DESCRIPTION  174
#define RESOURCE_USING_XNAME_LINK_TITLE   175
#define NON_VIRTUALIZED_ITEMS_PANEL_TITLE                   176
#define NON_VIRTUALIZED_ITEMS_PANEL_IMPACT                  177
#define NON_VIRTUALIZED_ITEMS_PANEL_SOLUTION                178
#define NON_VIRTUALIZED_ITEMS_PANEL_DESCRIPTION             179
#define NON_VIRTUALIZED_ITEMS_PANEL_DESCRIPTION_NO_NAME     180
#define NON_VIRTUALIZED_ITEMS_PANEL_LINK_TITLE              181

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
