namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[WUXC_VERSION_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass ScrollViewerTestHooks
{
    static Windows.Foundation.IReference<Boolean> GetAutoHideScrollControllers(MU_XC_NAMESPACE.ScrollViewer scrollViewer);
    static void SetAutoHideScrollControllers(MU_XC_NAMESPACE.ScrollViewer scrollViewer, Windows.Foundation.IReference<Boolean> value);

    static MU_XCP_NAMESPACE.Scroller GetScrollerPart(MU_XC_NAMESPACE.ScrollViewer scrollViewer);
}

}
