namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum InfoBarCloseReason
{
    CloseButton = 0,
    Programmatic = 1
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum InfoBarSeverity
{
    Critical = 0,
    Warning = 1,
    Success = 2,
    Default = 3
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass InfoBarClosedEventArgs
{
    InfoBarCloseReason Reason { get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass InfoBarClosingEventArgs
{
    InfoBarCloseReason Reason { get; };
    Boolean Cancel { get; set; };

    Windows.Foundation.Deferral GetDeferral();
}

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass InfoBarTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    InfoBarTemplateSettings();

    Windows.UI.Xaml.Controls.IconElement IconElement;

    static Windows.UI.Xaml.DependencyProperty IconElementProperty{ get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass InfoBar : Windows.UI.Xaml.Controls.Control
{
    InfoBar();

    [MUX_DEFAULT_VALUE("false")]
    Boolean IsOpen{ get; set; };

    String Title{ get; set; };
    String Message{ get; set; };

    [MUX_DEFAULT_VALUE("winrt::InfoBarSeverity::Default")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    InfoBarSeverity Severity{ get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    IconSource IconSource{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsIconVisible{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsUserDismissable{ get; set; };

    Windows.UI.Xaml.Input.ICommand CloseButtonCommand{ get; set; };
    Object CloseButtonCommandParameter{ get; set; };

    Windows.UI.Xaml.Controls.Primitives.ButtonBase ActionButton{ get; set; };

    InfoBarTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty IsOpenProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty TitleProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MessageProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SeverityProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IconSourceProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsIconVisibleProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsUserDismissableProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty CloseButtonCommandProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty CloseButtonCommandParameterProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ActionButtonProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty TemplateSettingsProperty{ get; };
}

}
