namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
enum AnimatedIconAnimationQueueBehavior
{
    Cut,
    QueueOne,
    SpeedUpQueueOne,
};

[MUX_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass AnimatedIconTestHooks
{
    static void SetAnimationQueueBehavior(MU_XC_NAMESPACE.AnimatedIcon animatedIcon, AnimatedIconAnimationQueueBehavior easingFunction);
    static void SetDurationMultiplier(MU_XC_NAMESPACE.AnimatedIcon animatedIcon, Single multiplier);
    static void SetSpeedUpMultiplier(MU_XC_NAMESPACE.AnimatedIcon animatedIcon, Single multiplier);
    static void SetQueueLength(MU_XC_NAMESPACE.AnimatedIcon animatedIcon, Int32 length);

    static String GetLastAnimationSegment(MU_XC_NAMESPACE.AnimatedIcon animatedIcon);
    static String GetLastAnimationSegmentStart(MU_XC_NAMESPACE.AnimatedIcon animatedIcon);
    static String GetLastAnimationSegmentEnd(MU_XC_NAMESPACE.AnimatedIcon animatedIcon);
    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.AnimatedIcon, Object> LastAnimationSegmentChanged;
};

}
