[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ContentOrientation
{
    Vertical = 0,
    Horizontal = 1,
    None = 2,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum InteractionState
{
    Idle = 0,
    Interaction = 1,
    Inertia = 2,
    Animation = 3,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerScrollMode
{
    Auto = 0,
    Enabled = 1,
    Disabled = 2,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerZoomMode
{
    Enabled = 0,
    Disabled = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerChainingMode
{
    Auto = 0,
    Always = 1,
    Never = 2,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerRailingMode
{
    Enabled = 0,
    Disabled = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[flags]
enum ScrollerInputKind
{
    Touch = 1,
    Pen = 2,
    MouseWheel = 4,
    All = 255,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerViewKind
{
    Absolute = 0,
    RelativeToCurrentView = 1,
    RelativeToEndOfInertiaView = 2,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerViewChangeKind
{
    DisableAnimation = 0,
    AllowAnimation = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerViewChangeSnapPointRespect
{
    IgnoreSnapPoints = 0,
    RespectSnapPoints = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum ScrollerViewChangeResult
{
    Completed = 0,
    Interrupted = 1,
    Ignored = 2,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[marshaling_behavior(agile)]
[threading(both)]
runtimeclass ScrollerChangeOffsetsOptions
{
    ScrollerChangeOffsetsOptions(Double horizontalOffset, Double verticalOffset, ScrollerViewKind offsetsKind, ScrollerViewChangeKind viewChangeKind, ScrollerViewChangeSnapPointRespect snapPointRespect);

    Double HorizontalOffset { get; set; };
    Double VerticalOffset { get; set; };
    ScrollerViewKind OffsetsKind { get; set; };
    ScrollerViewChangeKind ViewChangeKind { get; set; };
    ScrollerViewChangeSnapPointRespect SnapPointRespect{ get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerChangeOffsetsWithAdditionalVelocityOptions
{
    ScrollerChangeOffsetsWithAdditionalVelocityOptions(Windows.Foundation.Numerics.Vector2 additionalVelocity, Windows.Foundation.IReference<Windows.Foundation.Numerics.Vector2> inertiaDecayRate);

    Windows.Foundation.Numerics.Vector2 AdditionalVelocity { get; set; };
    Windows.Foundation.IReference<Windows.Foundation.Numerics.Vector2> InertiaDecayRate { get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerChangeZoomFactorOptions
{
    ScrollerChangeZoomFactorOptions(Single zoomFactor, ScrollerViewKind zoomFactorKind, Windows.Foundation.Numerics.Vector2 centerPoint, ScrollerViewChangeKind viewChangeKind, ScrollerViewChangeSnapPointRespect snapPointRespect);

    Single ZoomFactor { get; set; };
    ScrollerViewKind ZoomFactorKind { get; set; };
    Windows.Foundation.Numerics.Vector2 CenterPoint { get; set; };
    ScrollerViewChangeKind ViewChangeKind { get; set; };
    ScrollerViewChangeSnapPointRespect SnapPointRespect{ get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerChangeZoomFactorWithAdditionalVelocityOptions
{
    ScrollerChangeZoomFactorWithAdditionalVelocityOptions(Single additionalVelocity, Windows.Foundation.IReference<Single> inertiaDecayRate, Windows.Foundation.Numerics.Vector2 centerPoint);

    Single AdditionalVelocity { get; set; };
    Windows.Foundation.IReference<Single> InertiaDecayRate { get; set; };
    Windows.Foundation.Numerics.Vector2 CenterPoint { get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerChangingOffsetsEventArgs
{
    Windows.UI.Composition.CompositionAnimation Animation { get; set; };
    Windows.Foundation.Numerics.Vector2 StartPosition { get; };
    Windows.Foundation.Numerics.Vector2 EndPosition { get; };
    Int32 ViewChangeId { get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerChangingZoomFactorEventArgs
{
    Windows.Foundation.Numerics.Vector2 CenterPoint { get; };
    Single StartZoomFactor{ get; };
    Single EndZoomFactor{ get; };
    Windows.UI.Composition.CompositionAnimation Animation { get; set; };
    Int32 ViewChangeId { get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerViewChangeCompletedEventArgs
{
    Int32 ViewChangeId { get; };
    ScrollerViewChangeResult Result { get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerBringingIntoViewEventArgs
{
    Windows.UI.Xaml.BringIntoViewRequestedEventArgs RequestEventArgs { get; };
    Double TargetHorizontalOffset { get; };
    Double TargetVerticalOffset { get; };
    Int32 ViewChangeId { get; };
    Boolean Cancel { get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass ScrollerAnchorRequestedEventArgs
{
    Windows.Foundation.Collections.IVector<Windows.UI.Xaml.UIElement> AnchorCandidates { get; };
    Windows.UI.Xaml.UIElement AnchorElement { get; set; };
}
