[WUXC_VERSION_RS3]
[webhosthidden]
enum ParallaxSourceOffsetKind
{
    Absolute = 0,
    Relative = 1,
};

[WUXC_VERSION_RS3]
[webhosthidden]
[contentproperty("Child")]
[WUXC_INTERFACE_NAME("IParallaxView", 6b84fcd4-4083-5b4b-bc40-d9204e19b41a)]
[WUXC_STATIC_NAME("IParallaxViewStatics", 8836e49c-0e0e-57d8-9395-f0a9a0d1bb28)]
[WUXC_CONSTRUCTOR_NAME("IParallaxViewFactory", e4eb9642-3e8e-5a26-94f2-9121d121b916)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass ParallaxView : Windows.UI.Xaml.FrameworkElement
{
    ParallaxView();

    Windows.UI.Xaml.UIElement Child { get; set; };
    Double HorizontalShift { get; set; };
    Double HorizontalSourceEndOffset { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ParallaxSourceOffsetKind::Relative")]
    ParallaxSourceOffsetKind HorizontalSourceOffsetKind { get; set; };
    Double HorizontalSourceStartOffset { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean IsHorizontalShiftClamped { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean IsVerticalShiftClamped { get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double MaxHorizontalShiftRatio { get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double MaxVerticalShiftRatio { get; set; };
    Windows.UI.Xaml.UIElement Source { get; set; };
    Double VerticalShift { get; set; };
    Double VerticalSourceEndOffset { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ParallaxSourceOffsetKind::Relative")]
    ParallaxSourceOffsetKind VerticalSourceOffsetKind { get; set; };
    Double VerticalSourceStartOffset { get; set; };
    void RefreshAutomaticHorizontalOffsets();
    void RefreshAutomaticVerticalOffsets();

    static Windows.UI.Xaml.DependencyProperty ChildProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceEndOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceOffsetKindProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceStartOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxHorizontalShiftRatioProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalShiftProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsHorizontalShiftClampedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsVerticalShiftClampedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty SourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceEndOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceOffsetKindProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceStartOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxVerticalShiftRatioProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalShiftProperty { get; };
}
