namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
enum ParallaxSourceOffsetKind
{
    Absolute = 0,
    Relative = 1,
};

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("Child")]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass ParallaxView : Windows.UI.Xaml.FrameworkElement
{
    ParallaxView();

    Windows.UI.Xaml.UIElement Child { get; set; };
    Double HorizontalShift { get; set; };
    Double HorizontalSourceEndOffset { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ParallaxSourceOffsetKind::Relative")]
    ParallaxSourceOffsetKind HorizontalSourceOffsetKind { get; set; };
    Double HorizontalSourceStartOffset { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean IsHorizontalShiftClamped { get; set; };
    [MUX_DEFAULT_VALUE("true")]
    Boolean IsVerticalShiftClamped { get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double MaxHorizontalShiftRatio { get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double MaxVerticalShiftRatio { get; set; };
    Windows.UI.Xaml.UIElement Source { get; set; };
    Double VerticalShift { get; set; };
    Double VerticalSourceEndOffset { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ParallaxSourceOffsetKind::Relative")]
    ParallaxSourceOffsetKind VerticalSourceOffsetKind { get; set; };
    Double VerticalSourceStartOffset { get; set; };
    void RefreshAutomaticHorizontalOffsets();
    void RefreshAutomaticVerticalOffsets();

    static Windows.UI.Xaml.DependencyProperty ChildProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceEndOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceOffsetKindProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalSourceStartOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxHorizontalShiftRatioProperty { get; };
    static Windows.UI.Xaml.DependencyProperty HorizontalShiftProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsHorizontalShiftClampedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsVerticalShiftClampedProperty { get; };
    static Windows.UI.Xaml.DependencyProperty SourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceEndOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceOffsetKindProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalSourceStartOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxVerticalShiftRatioProperty { get; };
    static Windows.UI.Xaml.DependencyProperty VerticalShiftProperty { get; };
}

}
