
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

namespace winrt::BindPhasingTestBedCppWinRT::implementation
{


    namespace MainPage_staticasserts
    {
        template<typename, typename = void>
        constexpr bool is_type_complete_v = false;

        template<typename T>
        constexpr bool is_type_complete_v<T, std::void_t<decltype(sizeof(T))>> = true;

        static_assert( is_type_complete_v<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>, "Please #include the implementation header for '::winrt::Microsoft::UI::Xaml::Controls::TextBlock' in your precompiled header 'pch.h'." );

    }


    using Application = ::winrt::Microsoft::UI::Xaml::Application;
    using ComponentResourceLocation = ::winrt::Microsoft::UI::Xaml::Controls::Primitives::ComponentResourceLocation;
    using DataTemplate = ::winrt::Microsoft::UI::Xaml::DataTemplate;
    using DependencyObject = ::winrt::Microsoft::UI::Xaml::DependencyObject;
    using DependencyProperty = ::winrt::Microsoft::UI::Xaml::DependencyProperty;
    using IComponentConnector = ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector;
    using Uri = ::winrt::Windows::Foundation::Uri;
    using XamlBindingHelper = ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper;

    template <typename D, typename ... I>
    void MainPageT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///MainPage.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Application);
        }
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 2:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::GridView>();
                this->myGridView(targetElement);
                auto weakThis = ::winrt::make_weak<class_type>(*this);
                targetElement.ContainerContentChanging([weakThis](::winrt::Microsoft::UI::Xaml::Controls::ListViewBase const& p0, ::winrt::Microsoft::UI::Xaml::Controls::ContainerContentChangingEventArgs const& p1){
                    if (auto t = weakThis.get())
                    {
                        ::winrt::get_self<D>(t)->MyGridView_ContainerContentChanging(p0, p1);
                    }
                });
            }
            break;
        }
        _contentLoaded = true;
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::DisconnectUnloadedObject(int32_t)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects to disconnect." };
    }

    template <typename D, typename ... I>
    void MainPageT<D, I...>::UnloadObject(DependencyObject const&)
    {
        throw ::winrt::hresult_invalid_argument { L"No unloadable objects." };
    }

    template <typename D, typename... I>
    IComponentConnector MainPageT<D, I...>::GetBindingConnector(int32_t connectionId, IInspectable const& target)
    {
        ::winrt::com_ptr<::winrt::BindPhasingTestBedCppWinRT::implementation::XamlBindings> bindings;
        switch (connectionId)
        {
            case 4: // MainPage.xaml line 18
                {
                    auto element4 = target.as<::winrt::Microsoft::UI::Xaml::Controls::StackPanel>();
                    auto objBindings = std::make_shared<MainPage_obj4_Bindings>();
                    objBindings->SetDataRoot(element4.DataContext());
                    bindings = ::winrt::make_self<::winrt::BindPhasingTestBedCppWinRT::implementation::XamlBindings>(std::move(objBindings));
                    bindings->SubscribeForDataContextChanged(element4);
                    DataTemplate::SetExtensionInstance(element4, bindings.as<::winrt::Microsoft::UI::Xaml::IDataTemplateExtension>());
                    XamlBindingHelper::SetDataTemplateComponent(element4, bindings.as<::winrt::Microsoft::UI::Xaml::Markup::IDataTemplateComponent>());
                }
                break;
        }
        return bindings ? bindings.as<::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector>() : nullptr;
    }

    template <typename D, typename ... I>
    struct MainPageT<D, I...>::MainPage_obj4_Bindings
        : public ::winrt::BindPhasingTestBedCppWinRT::implementation::ReferenceTypeXamlBindings<::winrt::BindPhasingTestBedCppWinRT::MyItem, ::winrt::BindPhasingTestBedCppWinRT::implementation::XamlBindingTrackingBase>
        , public std::enable_shared_from_this<MainPageT<D, I...>::MainPage_obj4_Bindings>
        , public ::winrt::BindPhasingTestBedCppWinRT::implementation::IXamlBindingTracking
{
        MainPage_obj4_Bindings()
        {
            InitializeTracking(this);
        }

        ~MainPage_obj4_Bindings()
        {
            ReleaseAllListeners();
        }

        void Connect(int32_t connectionId, IInspectable const& target) override
        {
            switch(connectionId)
            {
            case 4: // MainPage.xaml line 18
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::StackPanel>();
                    obj4 = targetElement;
                }
                break;
            case 6: // MainPage.xaml line 23
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj6 = targetElement;
                }
                break;
            case 7: // MainPage.xaml line 27
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj7 = targetElement;
                }
                break;
            case 8: // MainPage.xaml line 31
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj8 = targetElement;
                }
                break;
            case 9: // MainPage.xaml line 35
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj9 = targetElement;
                }
                break;
            case 10: // MainPage.xaml line 39
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj10 = targetElement;
                }
                break;
            case 11: // MainPage.xaml line 43
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj11 = targetElement;
                }
                break;
            case 12: // MainPage.xaml line 47
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj12 = targetElement;
                }
                break;
            case 13: // MainPage.xaml line 51
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj13 = targetElement;
                }
                break;
            case 14: // MainPage.xaml line 54
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj14 = targetElement;
                    // MainPage.xaml line 54
                    if (obj14)
                    {
                        Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj14, obj14TextDeferredValue);
                    }
                }
                break;
            case 15: // MainPage.xaml line 58
                {
                    auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Controls::TextBlock>();
                    obj15 = targetElement;
                    // MainPage.xaml line 58
                    if (obj15)
                    {
                        Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj15, obj15TextDeferredValue);
                    }
                }
                break;
            }
        }

        void DisconnectUnloadedObject(int connectionId) override
        {
            switch (connectionId)
            {
                case 14: // MainPage.xaml line 54
                    {
                        if (obj14)
                        {
                            obj14TextDeferredValue = obj14.Text();
                            obj14 = nullptr;
                        }
                }
                break;
                case 15: // MainPage.xaml line 58
                    {
                        if (obj15)
                        {
                            obj15TextDeferredValue = obj15.Text();
                            obj15 = nullptr;
                        }
                }
                break;
                default:
                    throw hresult_invalid_argument(L"Invalid connectionId.");
            }
        }

        void Recycle() override
        {
            ReleaseAllListeners();
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj6);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj8);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj7);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj12);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj9);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj10);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj11);
            ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj13);
            if (obj15)
            {
                ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::SuspendRendering(obj15);
            }
        }

        void ProcessBindings(IInspectable const& item, int itemIndex, int phase, int32_t& nextPhase)
        {
            nextPhase = -1;
            switch (phase)
            {
            case 0:
                {
                    nextPhase = 1;
                    SetDataRoot(item);
                    if (_dataContextChangedToken.value != 0)
                    {
                        auto rootElement = this->obj4.get();
                        if (rootElement != nullptr)
                        {
                            rootElement.DataContextChanged(_dataContextChangedToken);
                        }
                        _dataContextChangedToken.value = 0;
                    }
                    _isInitialized = true;
                 }
                 break;
            case 1:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj6);
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj8);
                    nextPhase = 2;
                }
                break;
            case 2:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj7);
                    nextPhase = 3;
                }
                break;
            case 3:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj12);
                    nextPhase = 4;
                }
                break;
            case 4:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj9);
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj10);
                    nextPhase = 6;
                }
                break;
            case 6:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj11);
                    nextPhase = 7;
                }
                break;
            case 7:
                {
                    ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj13);
                    nextPhase = 19;
                }
                break;
            case 19:
                {
                    if (obj15)
                    {
                        ::winrt::Microsoft::UI::Xaml::Markup::XamlBindingHelper::ResumeRendering(obj15);
                    }
                    nextPhase = -1;
                }
                break;
            }
            Update_(::winrt::unbox_value<::winrt::BindPhasingTestBedCppWinRT::MyItem>(item) , 1 << phase);
        }


    private:
        // Fields for each control that has bindings.
        ::winrt::weak_ref<::winrt::Microsoft::UI::Xaml::Controls::StackPanel> obj4;
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj6 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj7 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj8 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj9 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj10 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj11 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj12 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj13 { nullptr };
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj14 { nullptr };
        ::winrt::hstring obj14TextDeferredValue {};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock obj15 { nullptr };
        ::winrt::hstring obj15TextDeferredValue {};

        // Fields for binding tracking.
        ::winrt::weak_ref<::winrt::Microsoft::UI::Xaml::Data::INotifyPropertyChanged> cachePC_;
        ::winrt::weak_ref<::winrt::Microsoft::UI::Xaml::DependencyObject> cacheDPC_DPOnMyItem;
        ::winrt::event_token tokenPC_ {};
        __int64 tokenDPC_DPOnMyItem{0};

        // Update methods for each path node used in binding steps.

        void Update_(::winrt::BindPhasingTestBedCppWinRT::MyItem obj, int32_t phase)
        {
            _bindingsTracking->UpdatePropertyChangedListener(obj, cachePC_, tokenPC_);
            _bindingsTracking->UpdateDependencyPropertyChangedListener(obj, ::winrt::BindPhasingTestBedCppWinRT::implementation::MyItem::DPOnMyItemProperty(), cacheDPC_DPOnMyItem, tokenDPC_DPOnMyItem);
            if (obj)
            {
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 1) | (1 << 19))) != 0)
                {
                    Update_Subtitle(obj.Subtitle(), phase);
                }
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 1) | (1 << 2))) != 0)
                {
                    Update_Title(obj.Title(), phase);
                }
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0) | (1 << 3))) != 0)
                {
                    Update_Description(obj.Description(), phase);
                }
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 4))) != 0)
                {
                    Update_Info(obj.Info(), phase);
                }
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 6))) != 0)
                {
                    Update_OtherInfo(obj.OtherInfo(), phase);
                }
                if ((phase & (NOT_PHASED | DATA_CHANGED | (1 << 0) | (1 << 7))) != 0)
                {
                    Update_DPOnMyItem(obj.DPOnMyItem(), phase);
                }
            }
            else
            {
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 1) | (1 << 2))) != 0)
                {
                    UpdateFallback_Title(phase);
                }
            }
        }

        void Update_Title(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 1) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 23
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj6, obj);
            }
            if((phase & ((1 << 2) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 27
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj7, obj);
            }
        }

        void Update_Subtitle(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 0) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 54
                if (obj14)
                {
                    Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj14, obj);
                }
                else
                {
                    obj14TextDeferredValue = obj;
                }
            }
            if((phase & ((1 << 1) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 31
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj8, obj);
            }
            if((phase & ((1 << 19) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 58
                if (obj15)
                {
                    Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj15, obj);
                }
                else
                {
                    obj15TextDeferredValue = obj;
                }
            }
        }

        void Update_Info(::winrt::BindPhasingTestBedCppWinRT::MyInfo obj, int32_t phase)
        {
            if (obj)
            {
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 4))) != 0)
                {
                    Update_Info_ImageUrl(obj.ImageUrl(), phase);
                    Update_Info_Caption(obj.Caption(), phase);
                }
            }
        }

        void Update_Info_ImageUrl(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 4) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 35
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj9, obj);
            }
        }

        void Update_Info_Caption(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 4) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 39
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj10, obj);
            }
        }

        void Update_OtherInfo(::winrt::BindPhasingTestBedCppWinRT::ExtraInfo obj, int32_t phase)
        {
            if (obj)
            {
                if ((phase & (NOT_PHASED | (1 << 0) | (1 << 6))) != 0)
                {
                    Update_OtherInfo_Caption(obj.Caption(), phase);
                }
            }
        }

        void Update_OtherInfo_Caption(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 6) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 43
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj11, obj);
            }
        }

        void Update_Description(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 3) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 47
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj12, obj);
            }
        }

        void Update_DPOnMyItem(::winrt::hstring obj, int32_t phase)
        {
            if((phase & ((1 << 7) | NOT_PHASED | DATA_CHANGED)) != 0)
            {
                // MainPage.xaml line 51
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj13, obj);
            }
        }

        void UpdateFallback_Title(int phase)
        {
            if((phase & ((1 << 2) | NOT_PHASED )) != 0)
            {
                // MainPage.xaml line 27
                Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(obj7, L"foo");
            }
        }

        virtual void ReleaseAllListeners() override
        {
            _bindingsTracking->UpdatePropertyChangedListener(nullptr, cachePC_, tokenPC_);
            _bindingsTracking->UpdateDependencyPropertyChangedListener(nullptr, ::winrt::BindPhasingTestBedCppWinRT::implementation::MyItem::DPOnMyItemProperty(), cacheDPC_DPOnMyItem, tokenDPC_DPOnMyItem);
        }

        virtual void PropertyChanged(IInspectable const& sender, ::winrt::Microsoft::UI::Xaml::Data::PropertyChangedEventArgs const& e) override
        {
            if (GetDataRoot() && GetDataRoot() == sender)
            {
                auto propName = e.PropertyName();
                auto obj = sender.as<::winrt::BindPhasingTestBedCppWinRT::MyItem>();
                if (propName.empty())
                {
                    if (obj)
                    {
                        Update_Description(obj.Description(), DATA_CHANGED);
                        Update_DPOnMyItem(obj.DPOnMyItem(), DATA_CHANGED);
                    }
                }
                else if (propName == L"Description")
                {
                    if (obj)
                    {
                        Update_Description(obj.Description(), DATA_CHANGED);
                    }
                }
                else if (propName == L"DPOnMyItem")
                {
                    if (obj)
                    {
                        Update_DPOnMyItem(obj.DPOnMyItem(), DATA_CHANGED);
                    }
                }
            }
        }

        void CollectionChanged(IInspectable const& sender, ::winrt::Microsoft::UI::Xaml::Interop::NotifyCollectionChangedEventArgs const& e) override
        {
        }

        void VectorChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IVectorChangedEventArgs const& e) override
        {
        }

        void MapChanged(IInspectable const& sender, ::winrt::Windows::Foundation::Collections::IMapChangedEventArgs<::winrt::hstring> const& e) override
        {
        }

        void DependencyPropertyChanged(DependencyObject const& sender, DependencyProperty const& prop) override
        {
            if (sender)
            {
                if (sender == cacheDPC_DPOnMyItem.get() && ::winrt::BindPhasingTestBedCppWinRT::implementation::MyItem::DPOnMyItemProperty() == prop)
                {
                    auto obj = sender.as<::winrt::BindPhasingTestBedCppWinRT::MyItem>();
                    if (obj)
                    {
                        Update_DPOnMyItem(obj.DPOnMyItem(), DATA_CHANGED);
                    }
                }
            }
        }


        static void Set_Microsoft_UI_Xaml_Controls_TextBlock_Text(::winrt::Microsoft::UI::Xaml::Controls::TextBlock const& obj, ::winrt::hstring const& value)
        {
            obj.Text(value);
        }
    }; 

    template struct MainPageT<struct MainPage>;
}


#pragma warning(pop)


