<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.windows.sdk.buildtools.msix\1.7.251221100\buildTransitive\Microsoft.Windows.SDK.BuildTools.MSIX.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windows.sdk.buildtools.msix\1.7.251221100\buildTransitive\Microsoft.Windows.SDK.BuildTools.MSIX.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windows.sdk.buildtools\10.0.26100.4654\buildTransitive\Microsoft.Windows.SDK.BuildTools.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windows.sdk.buildtools\10.0.26100.4654\buildTransitive\Microsoft.Windows.SDK.BuildTools.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windowsappsdk.base\2.0.3-experimental1\buildTransitive\Microsoft.WindowsAppSDK.Base.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk.base\2.0.3-experimental1\buildTransitive\Microsoft.WindowsAppSDK.Base.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windowsappsdk.interactiveexperiences\2.0.11-experimental\buildTransitive\Microsoft.WindowsAppSDK.InteractiveExperiences.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk.interactiveexperiences\2.0.11-experimental\buildTransitive\Microsoft.WindowsAppSDK.InteractiveExperiences.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\2.0.19-experimental\buildTransitive\Microsoft.WindowsAppSDK.Foundation.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk.foundation\2.0.19-experimental\buildTransitive\Microsoft.WindowsAppSDK.Foundation.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.web.webview2\1.0.3719.77\buildTransitive\Microsoft.Web.WebView2.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.web.webview2\1.0.3719.77\buildTransitive\Microsoft.Web.WebView2.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windowsappsdk.winui\3.0.0-dev\buildTransitive\Microsoft.WindowsAppSDK.WinUI.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windowsappsdk.winui\3.0.0-dev\buildTransitive\Microsoft.WindowsAppSDK.WinUI.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.windows.cswinrt\2.1.1\build\Microsoft.Windows.CsWinRT.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.windows.cswinrt\2.1.1\build\Microsoft.Windows.CsWinRT.targets')" />
  </ImportGroup>
</Project>