namespace MU_XC_NAMESPACE
{

[MUX_PREVIEW]
[webhosthidden]
enum WrapPanelItemsStretch
{
    None = 0,
    Last = 1,
};

[MUX_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass WrapPanel : Microsoft.UI.Xaml.Controls.Panel
{
    WrapPanel();

    Microsoft.UI.Xaml.Thickness Padding{ get; set; };
    static Microsoft.UI.Xaml.DependencyProperty PaddingProperty{ get; };

    Double ItemSpacing;
    static Microsoft.UI.Xaml.DependencyProperty ItemSpacingProperty{ get; };

    Double LineSpacing;
    static Microsoft.UI.Xaml.DependencyProperty LineSpacingProperty{ get; };

    [MUX_DEFAULT_VALUE("winrt::Orientation::Horizontal")]
    Microsoft.UI.Xaml.Controls.Orientation Orientation;
    static Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };

    WrapPanelItemsStretch ItemsStretch;
    static Microsoft.UI.Xaml.DependencyProperty ItemsStretchProperty{ get; };
}

}
