namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass TeachingTipAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    TeachingTipAutomationPeer(MU_XC_NAMESPACE.TeachingTip owner);
}

}
