[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass TeachingTipAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    TeachingTipAutomationPeer(MU_XC_NAMESPACE.TeachingTip owner);
}
