namespace MU_XC_NAMESPACE
{



[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxSpinButtonPlacementMode
{
    Hidden,
    Inline
};


[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxBasicValidationMode
{
    InvalidInputOverwritten,
    IconMessage,
    TextBlockMessage,
    Disabled
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxMinMaxMode
{
    None,
    MinEnabled,
    MaxEnabled,
    MinAndMaxEnabled,
    WrapEnabled
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxNumberRounder
{
    None,
    IncrementNumberRounder,
    SignificantDigitsNumberRounder
};





[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass NumberBox : Windows.UI.Xaml.Controls.Control
{
    NumberBox();
    
    
    [MUX_DEFAULT_VALUE("0")]
    Double Value{ get; set; };
    String Header;
    NumberBoxBasicValidationMode BasicValidationMode;

    [MUX_DEFAULT_VALUE("winrt::NumberBoxSpinButtonPlacementMode::Hidden")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    NumberBoxSpinButtonPlacementMode SpinButtonPlacementMode{ get; set; };
    [MUX_DEFAULT_VALUE("false")]
    Boolean HyperScrollEnabled;
    [MUX_DEFAULT_VALUE("1")]
    Double StepFrequency;

    [MUX_DEFAULT_VALUE("winrt::NumberBoxMinMaxMode::None")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    NumberBoxMinMaxMode MinMaxMode{ get; set; };
    [MUX_DEFAULT_VALUE("0")]
    Double MinValue;
    [MUX_DEFAULT_VALUE("0")]
    Double MaxValue;

    [MUX_DEFAULT_VALUE("1")]
    Int32 IntegerDigits;
    [MUX_DEFAULT_VALUE("0")]
    Int32 FractionDigits;
    [MUX_DEFAULT_VALUE("0")]
    Int32 SignificantDigits;
    [MUX_DEFAULT_VALUE("false")]
    Boolean IsDecimalPointAlwaysDisplayed;
    [MUX_DEFAULT_VALUE("false")]
    Boolean IsZeroSigned;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::RoundingAlgorithm::RoundAwayFromZero")]
    Windows.Globalization.NumberFormatting.RoundingAlgorithm RoundingAlgorithm{ get; set; };
    [MUX_DEFAULT_VALUE("winrt::NumberBoxNumberRounder::None")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    NumberBoxNumberRounder NumberRounder{ get; set; };
    [MUX_DEFAULT_VALUE("1")]
    Double IncrementPrecision;
    [MUX_DEFAULT_VALUE("1")]
    Int32 SignificantDigitPrecision;



    event Windows.Foundation.TypedEventHandler<NumberBox, Object> ValueChanged;

    //Object Placeholder{ get; set; };
    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty BasicValidationModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SpinButtonPlacementModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MinMaxModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HyperScrollEnabledProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty StepFrequencyProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MinValueProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MaxValueProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IntegerDigitsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty FractionDigitsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SignificantDigitsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsDecimalPointAlwaysDisplayedProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsZeroSignedProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty RoundingAlgorithmProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty NumberRounderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IncrementPrecisionProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SignificantDigitPrecisionProperty{ get; };




}

}
