namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
enum NumberBoxSpinButtonPlacementMode
{
    Hidden,
    Compact,
    Inline
};

[WUXC_VERSION_MUXONLY]
[webhosthidden]
enum NumberBoxValidationMode
{
    InvalidInputOverwritten,
    Disabled
};

[WUXC_VERSION_MUXONLY]
[webhosthidden]
runtimeclass NumberBoxValueChangedEventArgs
{
    Double OldValue{ get; };
    Double NewValue{ get; };
};

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass NumberBox : Windows.UI.Xaml.Controls.Control
{
    NumberBox();

    [MUX_DEFAULT_VALUE("-std::numeric_limits<double>::max()")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Double Minimum;

    [MUX_DEFAULT_VALUE("std::numeric_limits<double>::max()")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Double Maximum;

    [MUX_DEFAULT_VALUE("std::numeric_limits<double>::quiet_NaN()")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Double Value;

    [MUX_DEFAULT_VALUE("1")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Double SmallChange;

    [MUX_DEFAULT_VALUE("10")]
    Double LargeChange;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    String Text;

    // TextBox properties
    Object Header;
    Windows.UI.Xaml.DataTemplate HeaderTemplate;
    String PlaceholderText;
    Windows.UI.Xaml.Controls.Primitives.FlyoutBase SelectionFlyout;
    Windows.UI.Xaml.Media.SolidColorBrush SelectionHighlightColor;
    Windows.UI.Xaml.TextReadingOrder TextReadingOrder;
    Boolean PreventKeyboardDisplayOnProgrammaticFocus;
    Object Description;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    NumberBoxValidationMode ValidationMode;

    [MUX_DEFAULT_VALUE("winrt::NumberBoxSpinButtonPlacementMode::Hidden")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    NumberBoxSpinButtonPlacementMode SpinButtonPlacementMode{ get; set; };

    [MUX_DEFAULT_VALUE("false")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsWrapEnabled;

    [MUX_DEFAULT_VALUE("false")]
    Boolean AcceptsExpression;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_PROPERTY_VALIDATION_CALLBACK("ValidateNumberFormatter")]
    Windows.Globalization.NumberFormatting.INumberFormatter2 NumberFormatter;

    event Windows.Foundation.TypedEventHandler<NumberBox, NumberBoxValueChangedEventArgs> ValueChanged;

    static Windows.UI.Xaml.DependencyProperty MinimumProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MaximumProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SmallChangeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty LargeChangeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty TextProperty{ get; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    static Windows.UI.Xaml.DependencyProperty HeaderTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty PlaceholderTextProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectionFlyoutProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectionHighlightColorProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty TextReadingOrderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty PreventKeyboardDisplayOnProgrammaticFocusProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty DescriptionProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty ValidationModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SpinButtonPlacementModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsWrapEnabledProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty AcceptsExpressionProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty NumberFormatterProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass NumberBoxAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    NumberBoxAutomationPeer(MU_XC_NAMESPACE.NumberBox owner);
}

}
