namespace MU_XC_NAMESPACE
{



[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxSpinButtonPlacementMode
{
    Hidden,
    Inline
};


[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxBasicValidationMode
{
    InvalidInputOverwritten,
    IconMessage,
    TextBlockMessage,
    Disabled
};

// Temporarily renamed "None" to Disabled because of previous definition issue
[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxMinMaxMode
{
    BoundsDisabled,
    MinEnabled,
    MaxEnabled,
    MinAndMaxEnabled,
    WrapEnabled
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum NumberBoxNumberRounder
{
    RounderDisabled,
    IncrementNumberRounder,
    SignificantDigitsNumberRounder
};





[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass NumberBox : Windows.UI.Xaml.Controls.Control
{
    NumberBox();
    
    [MUX_DEFAULT_VALUE("0")]
    Double Value{ get; set; };
    event Windows.Foundation.TypedEventHandler<NumberBox, Object> ValueChanged;

    //Object Placeholder{ get; set; };
    static Windows.UI.Xaml.DependencyProperty ValueProperty{ get; };
}

}
