namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass RevealListViewItemPresenter : Windows.UI.Xaml.Controls.Primitives.ListViewItemPresenter
{
    RevealListViewItemPresenter();
}

}