namespace MU_PRIVATE_MEDIA_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
runtimeclass RevealBrushTestApi : Windows.UI.Xaml.DependencyObject
{
    RevealBrushTestApi();

    MU_XM_NAMESPACE.RevealBrush RevealBrush { get; set; };
    Boolean IsInFallbackMode { get; };
    Boolean IsAmbientLightSet { get; };
    Boolean IsBorderLightSet { get; };
    Boolean IsHoverLightSet { get; };
    Windows.UI.Composition.CompositionBrush CompositionBrush { get; };
    Windows.UI.Composition.CompositionBrush NoiseBrush { get; };
    
}

}