namespace MU_XM_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
enum RevealBrushState
{
    Normal = 0,
    PointerOver = 1,
    Pressed = 2,
};

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass RevealBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    protected RevealBrush();

    [MUX_DEFAULT_VALUE("RevealBrush::sc_defaultColor")]
    Windows.UI.Color Color { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ApplicationTheme::Light")]
    Windows.UI.Xaml.ApplicationTheme TargetTheme { get; set; };
    Boolean AlwaysUseFallback { get; set; };

    static Windows.UI.Xaml.DependencyProperty ColorProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TargetThemeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty AlwaysUseFallbackProperty { get; };
    [MUX_DEFAULT_VALUE("winrt::RevealBrushState::Normal")]
    [MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnStatePropertyChanged")]
    static Windows.UI.Xaml.DependencyProperty StateProperty { get; };
    static void SetState(Windows.UI.Xaml.UIElement element, RevealBrushState value);
    static RevealBrushState GetState(Windows.UI.Xaml.UIElement element);
}

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass RevealBorderBrush : RevealBrush
{
    RevealBorderBrush();
}

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass RevealBackgroundBrush : RevealBrush
{
    RevealBackgroundBrush();
}

}