[WUXC_VERSION_RS3]
[webhosthidden]
enum RevealBrushState
{
    Normal = 0,
    PointerOver = 1,
    Pressed = 2,
};

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IRevealBrush", 2036a0ed-8271-4398-9019-25872093f13f)]
[WUXC_STATIC_NAME("IRevealBrushStatics", 190f2625-7209-4d42-a847-1ac4bbbb3499)]
[WUXC_CONSTRUCTOR_NAME("IRevealBrushFactory", 9d9379ce-e3a0-4aaf-be37-ea9d9dd43105)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass RevealBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    protected RevealBrush();

    [MUX_DEFAULT_VALUE("RevealBrush::sc_defaultColor")]
    Windows.UI.Color Color { get; set; };
    [MUX_DEFAULT_VALUE("winrt::ApplicationTheme::Light")]
    Windows.UI.Xaml.ApplicationTheme TargetTheme { get; set; };
    Boolean AlwaysUseFallback { get; set; };

    static Windows.UI.Xaml.DependencyProperty ColorProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TargetThemeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty AlwaysUseFallbackProperty { get; };
    [MUX_DEFAULT_VALUE("winrt::RevealBrushState::Normal")]
    [MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnStatePropertyChanged")]
    static Windows.UI.Xaml.DependencyProperty StateProperty { get; };
    static void SetState(Windows.UI.Xaml.UIElement element, RevealBrushState value);
    static RevealBrushState GetState(Windows.UI.Xaml.UIElement element);
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IRevealBorderBrush", 060ba115-c542-483c-8202-5f03331866c9)]
[WUXC_CONSTRUCTOR_NAME("IRevealBorderBrushFactory", 94c25298-f5f8-4482-a25c-6758501a8626)]
unsealed runtimeclass RevealBorderBrush : RevealBrush
{
    RevealBorderBrush();
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IRevealBackgroundBrush", 261dcc0e-1991-4cdf-aee0-6350a3f90bb9)]
[WUXC_CONSTRUCTOR_NAME("IRevealBackgroundBrushFactory", 8c56bcaa-02a5-4f45-8506-8d39228f5d3f)]
unsealed runtimeclass RevealBackgroundBrush : RevealBrush
{
    RevealBackgroundBrush();
}
