//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::MultipleViewsTestbedCPP::MainPage::InitializeComponent()
{
    this->InitializeComponent(nullptr);
}

void ::MultipleViewsTestbedCPP::MainPage::InitializeComponent(::Windows::Foundation::Uri^ resourceLocator)
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    if (resourceLocator == nullptr)
    {
        resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    }
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::MultipleViewsTestbedCPP::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->DisplayText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 3:
        {
            this->MyControl = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->MyControl))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MultipleViewsTestbedCPP::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MyControl_Click);
        }
        break;
    case 5:
        {
            this->DisplayText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 6:
        {
            this->MyControl = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->MyControl))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MultipleViewsTestbedCPP::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MyControl_Click);
        }
        break;
    case 8:
        {
            this->DisplayText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 9:
        {
            this->MyControl = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->MyControl))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MultipleViewsTestbedCPP::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MyControl_Checked);
            (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->MyControl))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::MultipleViewsTestbedCPP::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MyControl_Checked);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::MultipleViewsTestbedCPP::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


