namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum TabViewWidthMode
{
    SizeToContent = 0,
    Fixed = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass TabViewTabClosingEventArgs
{
    Object Item { get; };

    Boolean Cancel { get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabView : Windows.UI.Xaml.Controls.ListView
{
    TabView();

    [MUX_DEFAULT_VALUE("winrt::TabViewWidthMode::SizeToContent")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    TabViewWidthMode TabWidthMode{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    Boolean CanCloseTabs{ get; set; };

    Object LeftCustomContent{ get; set; };
    Windows.UI.Xaml.DataTemplate LeftCustomContentTemplate{ get; set; };

    Object RightCustomContent{ get; set; };
    Windows.UI.Xaml.DataTemplate RightCustomContentTemplate{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsAddButtonVisible{ get; set; };

    event Windows.Foundation.TypedEventHandler<TabView, TabViewTabClosingEventArgs> TabClosing;

    event Windows.Foundation.TypedEventHandler<TabView, Object> AddButtonClick;

    static Windows.UI.Xaml.DependencyProperty TabWidthModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty CanCloseTabsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty LeftCustomContentProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty LeftCustomContentTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty RightCustomContentProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty RightCustomContentTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsAddButtonVisibleProperty{ get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabViewItem : Windows.UI.Xaml.Controls.ListViewItem
{
    TabViewItem();

    Object Header{ get; set; };

    Windows.UI.Xaml.DataTemplate HeaderTemplate{ get; set; };

    Windows.UI.Xaml.Controls.IconElement Icon{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsCloseable{ get; set; };

    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HeaderTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IconProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsCloseableProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabViewAutomationPeer : Windows.UI.Xaml.Automation.Peers.ListViewAutomationPeer
{
    TabViewAutomationPeer(MU_XC_NAMESPACE.TabView owner);
}

}

