namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum TabViewWidthMode
{
    SizeToContent = 0,
    Fixed = 1,
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass TabViewTabClosingEventArgs
{
    Object Item { get; };

    Boolean Cancel { get; set; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabView : Windows.UI.Xaml.Controls.Control
{
    TabView();

    [MUX_DEFAULT_VALUE("winrt::TabViewWidthMode::SizeToContent")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    TabViewWidthMode TabWidthMode{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    Boolean CanCloseTabs{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    Boolean CanDragDropTabs{ get; set; };

    Object LeftCustomContent{ get; set; };
    Windows.UI.Xaml.DataTemplate LeftCustomContentTemplate{ get; set; };

    Object RightCustomContent{ get; set; };
    Windows.UI.Xaml.DataTemplate RightCustomContentTemplate{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    Boolean IsAddButtonVisible{ get; set; };

    event Windows.Foundation.TypedEventHandler<TabView, TabViewTabClosingEventArgs> TabClosing;

    event Windows.Foundation.TypedEventHandler<TabView, Object> AddButtonClick;

    // From ListView
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Object ItemsSource;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Windows.Foundation.Collections.IVector<Object> Items{ get; };

    Windows.UI.Xaml.DataTemplate ItemTemplate;

    [MUX_DEFAULT_VALUE("-1")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Int32 SelectedIndex;

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Object SelectedItem;

    Windows.UI.Xaml.DependencyObject ContainerFromItem(Object item);
    Windows.UI.Xaml.DependencyObject ContainerFromIndex(Int32 index);

    event Windows.UI.Xaml.Controls.SelectionChangedEventHandler SelectionChanged;

    static Windows.UI.Xaml.DependencyProperty TabWidthModeProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty CanCloseTabsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty CanDragDropTabsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty LeftCustomContentProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty LeftCustomContentTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty RightCustomContentProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty RightCustomContentTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsAddButtonVisibleProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemsProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectedIndexProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectedItemProperty{ get; };
}

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabViewItem : Windows.UI.Xaml.Controls.ListViewItem
{
    TabViewItem();

    Object Header{ get; set; };

    Windows.UI.Xaml.DataTemplate HeaderTemplate{ get; set; };

    Windows.UI.Xaml.Controls.IconElement Icon{ get; set; };

    [MUX_DEFAULT_VALUE("true")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsCloseable{ get; set; };

    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty HeaderTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IconProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty IsCloseableProperty{ get; };
}

}

namespace MU_XCP_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabViewListView : Windows.UI.Xaml.Controls.ListView
{
    TabViewListView();
}

}

namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass TabViewAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    TabViewAutomationPeer(MU_XC_NAMESPACE.TabView owner);
}

}

