// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#pragma once

// Forward declarations for external headers.  Please use in header files instead of declaring manually.

#include <abi/xaml_abi.h>

XAML_ABI_NAMESPACE_BEGIN
namespace Microsoft {
namespace UI {
namespace Xaml {
    class AdaptiveTrigger;
    class Application;
    class ApplicationInitializationCallbackParams;
    class BindingFailedEventArgs;
    class BringIntoViewOptions;
    class BringIntoViewRequestedEventArgs;
    class BrushTransition;
    class ColorPaletteResources;
    class CornerRadiusHelper;
    class DataContextChangedEventArgs;
    class DataTemplate;
    class DataTemplateKey;
    class DebugSettings;
    class DependencyObject;
    class DependencyObjectCollection;
    class DependencyProperty;
    class DependencyPropertyChangedEventArgs;
    class DispatcherTimer;
    class DragEventArgs;
    class DragOperationDeferral;
    class DragStartingEventArgs;
    class DragUI;
    class DragUIOverride;
    class DropCompletedEventArgs;
    class DurationHelper;
    class DxamlCoreTestHooks;
    class EffectiveViewportChangedEventArgs;
    class ElementFactoryGetArgs;
    class ElementFactoryRecycleArgs;
    class ElementSoundPlayer;
    class EventTrigger;
    class ExceptionRoutedEventArgs;
    class FrameworkElement;
    class FrameworkElementEx;
    class FrameworkTemplate;
    class FrameworkView;
    class FrameworkViewSource;
    class GridLengthHelper;
    class InteractionBase;
    class LaunchActivatedEventArgs;
    class MediaFailedRoutedEventArgs;
    class PanelEx;
    class PointHelper;
    class PropertyMetadata;
    class PropertyPath;
    class RectHelper;
    class ResourceDictionary;
    class RoutedEvent;
    class RoutedEventArgs;
    class ScalarTransition;
    class Setter;
    class SetterBase;
    class SetterBaseCollection;
    class SizeChangedEventArgs;
    class SizeHelper;
    class StateTrigger;
    class StateTriggerBase;
    class Style;
    class TargetPropertyPath;
    class ThicknessHelper;
    class TriggerAction;
    class TriggerActionCollection;
    class TriggerBase;
    class TriggerCollection;
    class UIElement;
    class UIElementWeakCollection;
    class UnhandledExceptionEventArgs;
    class Vector3Transition;
    class VisualState;
    class VisualStateChangedEventArgs;
    class VisualStateGroup;
    class VisualStateManager;
    class VisualTransition;
    class Window;
    class WindowEventArgs;
    class WindowActivatedEventArgs;
    class WindowCreatedEventArgs;
    class WindowSizeChangedEventArgs;
    class XamlRoot;
    class XamlRootChangedEventArgs;
    enum ApplicationHighContrastAdjustment : unsigned int;
    enum ApplicationRequiresPointerMode : int;
    enum ApplicationTheme : int;
    enum AutomationTextAttributesEnum : int;
    enum DurationType : int;
    enum ElementHighContrastAdjustment : unsigned int;
    enum ElementSoundKind : int;
    enum ElementSoundMode : int;
    enum ElementSoundPlayerState : int;
    enum ElementSpatialAudioMode : int;
    enum ElementTheme : int;
    enum FlowDirection : int;
    enum FocusState : int;
    enum FocusVisualKind : int;
    enum FontCapitals : int;
    enum FontEastAsianLanguage : int;
    enum FontEastAsianWidths : int;
    enum FontFraction : int;
    enum FontNumeralAlignment : int;
    enum FontNumeralStyle : int;
    enum FontVariants : int;
    enum GridUnitType : int;
    enum HorizontalAlignment : int;
    enum LineStackingStrategy : int;
    enum OpticalMarginAlignment : int;
    enum TextAlignment : int;
    enum TextLineBounds : int;
    enum TextReadingOrder : int;
    enum TextTrimming : int;
    enum TextWrapping : int;
    enum TransitionParent : int;
    enum TransitionTrigger : int;
    enum Vector3TransitionComponents : unsigned int;
    enum VerticalAlignment : int;
    enum Visibility : int;
    interface IAdaptiveTrigger;
    interface IAdaptiveTriggerFactory;
    interface IAdaptiveTriggerStatics;
    interface IApplication;
    interface IApplication2;
    interface IApplication3;
    interface IApplicationFactory;
    interface IApplicationInitializationCallback;
    interface IApplicationInitializationCallbackParams;
    interface IApplicationOverrides;
    interface IApplicationOverrides2;
    interface IApplicationStatics;
    interface IAtlasRequestCallback;
    interface IBindingFailedEventArgs;
    interface IBindingFailedEventHandler;
    interface IBringIntoViewOptions;
    interface IBringIntoViewOptions2;
    interface IBringIntoViewRequestedEventArgs;
    interface IBrushTransition;
    interface IBrushTransitionFactory;
    interface IColorPaletteResources;
    interface IColorPaletteResourcesFactory;
    interface ICornerRadiusHelper;
    interface ICornerRadiusHelperStatics;
    interface ICreateDefaultValueCallback;
    interface IDataContextChangedEventArgs;
    interface IDataTemplate;
    interface IDataTemplateExtension;
    interface IDataTemplateFactory;
    interface IDataTemplateKey;
    interface IDataTemplateKeyFactory;
    interface IDataTemplateStatics2;
    interface IDebugSettings;
    interface IDebugSettings2;
    interface IDebugSettings3;
    interface IDebugSettings4;
    interface IDependencyObject;
    interface IDependencyObjectCollectionFactory;
    interface IDependencyObjectFactory;
    interface IDependencyProperty;
    interface IDependencyPropertyChangedCallback;
    interface IDependencyPropertyChangedEventArgs;
    interface IDependencyPropertyChangedEventHandler;
    interface IDependencyPropertyStatics;
    interface IDispatcherTimer;
    interface IDispatcherTimerFactory;
    interface IDragEventArgs;
    interface IDragEventArgs2;
    interface IDragEventArgs3;
    interface IDragEventHandler;
    interface IDragOperationDeferral;
    interface IDragStartingEventArgs;
    interface IDragStartingEventArgs2;
    interface IDragUI;
    interface IDragUIOverride;
    interface IDropCompletedEventArgs;
    interface IDurationHelper;
    interface IDurationHelperStatics;
    interface IDxamlCoreTestHooks;
    interface IDxamlCoreTestHooksStatics;
    interface IEffectiveViewportChangedEventArgs;
    interface IElementFactory;
    interface IElementFactoryGetArgs;
    interface IElementFactoryGetArgsFactory;
    interface IElementFactoryRecycleArgs;
    interface IElementFactoryRecycleArgsFactory;
    interface IElementSoundPlayer;
    interface IElementSoundPlayerStatics;
    interface IElementSoundPlayerStatics2;
    interface IElementSoundPlayerStaticsPrivate;
    interface IEnteredBackgroundEventHandler;
    interface IEventTrigger;
    interface IExceptionRoutedEventArgs;
    interface IExceptionRoutedEventArgsFactory;
    interface IExceptionRoutedEventHandler;
    interface IFrameworkApplicationPrivate;
    interface IFrameworkApplicationStaticsPrivate;
    interface IFrameworkElement;
    interface IFrameworkElementEx;
    interface IFrameworkElementExFactory;
    interface IFrameworkElementExProtected;
    interface IFrameworkElementExStatics;
    interface IFrameworkElementFactory;
    interface IFrameworkElementOverrides;
    interface IFrameworkElementOverrides2;
    interface IFrameworkElementProtected7;
    interface IFrameworkElementStatics;
    interface IFrameworkElementStatics2;
    interface IFrameworkElementStatics4;
    interface IFrameworkElementStatics5;
    interface IFrameworkElementStatics6;
    interface IFrameworkTemplate;
    interface IFrameworkTemplateFactory;
    interface IFrameworkTemplatePrivate;
    interface IFrameworkView;
    interface IFrameworkViewSource;
    interface IGridLengthHelper;
    interface IGridLengthHelperStatics;
    interface IInteractionBase;
    interface IInteractionBaseFactory;
    interface IInteractionBaseOverrides;
    interface ILaunchActivatedEventArgs;
    interface ILeavingBackgroundEventHandler;
    interface IMediaFailedRoutedEventArgs;
    interface IMemoryInfoPrivate;
    interface IPanelEx;
    interface IPanelExFactory;
    interface IPanelExStatics;
    interface IPointHelper;
    interface IPointHelperStatics;
    interface IPropertyChangedCallback;
    interface IPropertyMetadata;
    interface IPropertyMetadataFactory;
    interface IPropertyMetadataStatics;
    interface IPropertyPath;
    interface IPropertyPathFactory;
    interface IRectHelper;
    interface IRectHelperStatics;
    interface IRectHelperStaticsPrivate;
    interface IResourceDictionary;
    interface IResourceDictionaryFactory;
    interface IRoutedEvent;
    interface IRoutedEventArgs;
    interface IRoutedEventArgsFactory;
    interface IRoutedEventHandler;
    interface IScalarTransition;
    interface IScalarTransitionFactory;
    interface ISetter;
    interface ISetter2;
    interface ISetterBase;
    interface ISetterBaseCollection;
    interface ISetterBaseFactory;
    interface ISetterFactory;
    interface ISizeChangedEventArgs;
    interface ISizeChangedEventHandler;
    interface ISizeHelper;
    interface ISizeHelperStatics;
    interface ISourceInfoPrivate;
    interface IStateTrigger;
    interface IStateTriggerBase;
    interface IStateTriggerBaseFactory;
    interface IStateTriggerBaseProtected;
    interface IStateTriggerStatics;
    interface IStyle;
    interface IStyleFactory;
    interface ISuspendingEventHandler;
    interface ITargetPropertyPath;
    interface ITargetPropertyPathFactory;
    interface IThicknessHelper;
    interface IThicknessHelperStatics;
    interface ITriggerAction;
    interface ITriggerActionFactory;
    interface ITriggerBase;
    interface ITriggerBaseFactory;
    interface IUIElement;
    interface IUIElementFactory;
    interface IUIElementFeature_Xaml2018;
    interface IUIElementFeature_XamlMotionSystemHoldbacks;
    interface IUIElementOverrides;
    interface IUIElementStatics;
    interface IUIElementStaticsPrivate;
    interface IUIElementWeakCollection;
    interface IUIElementWeakCollectionFactory;
    interface IUnhandledExceptionEventArgs;
    interface IUnhandledExceptionEventHandler;
    interface IVector3Transition;
    interface IVector3TransitionFactory;
    interface IVisualState;
    interface IVisualState2;
    interface IVisualStateChangedEventArgs;
    interface IVisualStateChangedEventHandler;
    interface IVisualStateGroup;
    interface IVisualStateManager;
    interface IVisualStateManagerFactory;
    interface IVisualStateManagerOverrides;
    interface IVisualStateManagerProtected;
    interface IVisualStateManagerStatics;
    interface IVisualTransition;
    interface IVisualTransitionFactory;
    interface IWindow;
    interface IWindow2;
    interface IWindow3;
    interface IWindowActivatedEventArgs;
    interface IWindowCreatedEventArgs;
    interface IWindowEventArgs;
    interface IWindowPrivate;
    interface IWindowSizeChangedEventArgs;
    interface IWindowStatics;
    interface IWindowVisibilityChangedEventHandler;
    interface IXamlRoot;
    interface IXamlRootChangedEventArgs;
    interface IXamlServiceProvider;
    struct CornerRadius;
    struct Duration;
    struct GridLength;
    struct Thickness;
    struct WindowCreationParameters;
} // Xaml
} // UI
} // Microsoft
XAML_ABI_NAMESPACE_END
