namespace AppTestAutomationHelpers
{
    [default_interface]
    runtimeclass IdleSynchronizer
    {
        IdleSynchronizer(Windows.System.DispatcherQueue dispatcherQueue);
        
        String TryWait();
    }
}
