// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlGen.Templates.ModernIDL
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OM;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Interface : ModernIdlCodeGenerator<ClassDefinition>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
 foreach (var version in Model.Versions.Select(v => v.GetProjection()).OrderBy(v => v.Version)) { 
 WriteAttributes(version); 
            this.Write("interface ");
            this.Write(this.ToStringHelper.ToStringWithCulture(version.IdlClassInfo.InterfaceName));
            this.Write(" ");
 WriteImplementedInterfaces(version); 
            this.Write("{\r\n");
   foreach (var member in version.IdlClassInfo.PublicInstancePMEs.Where(m => m.OrderHint == null)) { 
            this.Write("    ");
 IncludeMember(member, RequestedInterface.PublicMembers, version.Version); 
   } 
   foreach (var member in version.IdlClassInfo.PublicInstancePMEs.Where(m => m.OrderHint != null).OrderBy(m => m.OrderHint)) { 
            this.Write("    ");
 IncludeMember(member, RequestedInterface.PublicMembers, version.Version); 
   } 
            this.Write("};\r\n\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
}
