[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass Forms : Windows.UI.Xaml.Controls.Control
{
    Forms();

    Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Controls.MenuFlyoutItemBase> Sections{ get; };

    static Windows.UI.Xaml.DependencyProperty SectionsProperty{ get; };
}

[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass FormSection : Windows.UI.Xaml.Controls.Panel
{
    FormSection();

    String Header{ get; set; };

    [MUX_DEFAULT_VALUE("1")]
    Int32 Columns;

    static Windows.UI.Xaml.DependencyProperty HeaderProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ColumnsProperty{ get; };
}

[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass FormRow : Windows.UI.Xaml.Controls.Panel
{
    FormRow();

    [MUX_DEFAULT_VALUE("FormRow::s_defaultLength")]
    [MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnLengthPropertyChanged")]
    static Windows.UI.Xaml.DependencyProperty LengthProperty{ get; };
    static void SetLength(Windows.UI.Xaml.UIElement element, Windows.UI.Xaml.GridLength value);
    static Windows.UI.Xaml.GridLength GetLength(Windows.UI.Xaml.UIElement element);
}
