namespace MU_XM_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[contentproperty("GradientStops")]
unsealed runtimeclass RadialGradientBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    RadialGradientBrush();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::Point(0.5,0.5)")]
    Windows.Foundation.Point EllipseCenter { get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::Point(0.5,0.5)")]
    Windows.Foundation.Point EllipseRadius { get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::Point(0.5,0.5)")]
    Windows.Foundation.Point GradientOffset { get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::BrushMappingMode::RelativeToBoundingBox")]
    Windows.UI.Xaml.Media.BrushMappingMode MappingMode { get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::Windows::UI::Composition::CompositionColorSpace::Auto")]
    Windows.UI.Composition.CompositionColorSpace InterpolationSpace { get; set; };

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    [MUX_DEFAULT_VALUE("winrt::GradientSpreadMethod::Pad")]
    Windows.UI.Xaml.Media.GradientSpreadMethod SpreadMethod { get; set; };

    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Media.GradientStop> GradientStops { get; };

    static Windows.UI.Xaml.DependencyProperty EllipseCenterProperty { get; };
    static Windows.UI.Xaml.DependencyProperty EllipseRadiusProperty { get; };
    static Windows.UI.Xaml.DependencyProperty GradientOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty InterpolationSpaceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MappingModeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty SpreadMethodProperty { get; };
}

}
