namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass ProgressRing : Windows.UI.Xaml.Controls.Primitives.RangeBase
{
    ProgressRing();

    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    Boolean IsIndeterminate{ get; set; };

    static Windows.UI.Xaml.DependencyProperty IsIndeterminateProperty{ get; };
}

}

namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
unsealed runtimeclass ProgressRingAutomationPeer : Windows.UI.Xaml.Automation.Peers.RangeBaseAutomationPeer
{
    ProgressRingAutomationPeer(MU_XC_NAMESPACE.ProgressRing owner);
}

}
