namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
runtimeclass MUXControlsTestHooksLoggingMessageEventArgs
{
    String Message { get; };
    Boolean IsVerboseLevel { get; };
}

[MUX_INTERNAL]
[webhosthidden]
[default_interface]
runtimeclass MUXControlsTestHooks
{
    static void SetOutputDebugStringLevelForType(String type, Boolean isLoggingInfoLevel, Boolean isLoggingVerboseLevel);
    static void SetLoggingLevelForType(String type, Boolean isLoggingInfoLevel, Boolean isLoggingVerboseLevel);
    static void SetLoggingLevelForInstance(Object sender, Boolean isLoggingInfoLevel, Boolean isLoggingVerboseLevel);
    static event Windows.Foundation.TypedEventHandler<Object, MUXControlsTestHooksLoggingMessageEventArgs> LoggingMessage;
}

}