name: Bug report
description: File a bug report
title: "Bug title"
labels: ["bug", "needs-triage"]
type: Bug
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: In a few sentences, please enter a short, clear description of the bug.
      placeholder: E.g. When clicking on a togggle button, '...' happens instead of '...' when '...' is enabled.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Why is this important?
      description: Please provide the impact/scenario of this issue to yourself or the end-user of an application. What is it that is trying to be accomplished that this bug prevents from happening? (For context, this helps us understand if this is the root issue of your problem. See https://xyproblem.info/ for more info.)
      placeholder: E.g. My user needs to click on the toggle button to switch the state of our setting, but we're not seeing our ViewModel update in this scenario. Their environment needs to be '...' as they're in another locale.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior. It is best if you can either reproduce the issue in the [WinUI Gallery](https://aka.ms/winuigallery) or create a new WinUI project that minimally reproduces the issue to attach here. (Providing a simple to follow reproduction with an example project, without extraneous code, makes it easier for anyone to quickly reproduce the issue and spend time investigating/fixing the issue over understanding how to reproduce it.)
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See issue '...'
  - type: textarea
    attributes:
      label: Actual behavior
      description: Please provide a description of what does happen when you follow the repro steps above
      placeholder: FooEvent doesn't fire.
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
      placeholder: FooEvent should fire.
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: NuGet package version
      description: If you are seeing your issue on older versions please try the latest release
      options:
        - "WinUI 3 - Windows App SDK 1.8 Experimental 4: 1.8.250702007-experimental4"
        - "WinUI 3 - Windows App SDK 1.7.3: 1.7.250606001"
        - "WinUI 3 - Windows App SDK 1.7 Preview 1: 1.7.250208002-preview1"
        - "WinUI 2 - Microsoft.UI.Xaml 2.8.7"
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Windows Insider Build (xxxxx)"
        - "Windows 11 (24H2): Build 26100"
        - "Windows 11 (23H2): Build 22631"
        - "Windows 11 (22H2): Build 22621"
        - "Windows 11 (21H2): Build 22000"
        - "Windows 10 (21H2): Build 19044"
        - "Windows 10 (21H1): Build 19043"
        - "Windows 10 (20H2): Build 19042"
        - "Windows 10 (1809): Build 17763"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
