name: Bug report
description: File a bug report
title: "Bug title"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        For bugs related to UWP or the app models, please open a bug on the [Project Reunion repository](https://github.com/microsoft/ProjectReunion)
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: NuGet package version
      description: If you are seeing your issue on older versions please try the latest release
      options:
        - "WinUI 3 - Windows App SDK 1.1 Preview 2: 1.1.0-preview2"
        - "WinUI 3 - Windows App SDK 1.1 Preview 1: 1.1.0-preview1"
        - "WinUI 3 - Windows App SDK 1.0.3"
        - "WinUI 3 - Windows App SDK 1.0.2"
        - "WinUI 3 - Windows App SDK 1.0.1"
        - "WinUI 3 - Windows App SDK 1.0"
        - "WinUI 3 - Windows App SDK 1.0 Experimental: 1.0.0-experimental1"
        - "WinUI 3 - Project Reunion 0.8: 0.8.8"
        - "WinUI 3 - Project Reunion 0.8: 0.8.7"
        - "WinUI 3 - Project Reunion 0.8 Preview 1: 0.8.7-preview1"
        - "WinUI 3 - Project Reunion 0.8: 0.8.6"
        - "WinUI 3 - Project Reunion 0.8 Preview 1: 0.8.6-preview1"
        - "WinUI 3 - Project Reunion 0.8: 0.8.5"
        - "WinUI 3 - Project Reunion 0.5: 0.5.7"
        - "WinUI 3 - Project Reunion 0.5: 0.5.0"
        - "WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease"
        - "Microsoft.WinUI 3.0.0-preview4.210210.4"
        - "Microsoft.UI.Xaml 2.7.1"
        - "Microsoft.UI.Xaml 2.7.0"
        - "Microsoft.UI.Xaml 2.6.2"
        - "Microsoft.UI.Xaml 2.6.1"
        - "Microsoft.UI.Xaml 2.6.0"
        - "Microsoft.UI.Xaml.2.6.0-prerelease.210430001"
        - "Microsoft.UI.Xaml 2.5.0"
        - "Microsoft.UI.Xaml 2.4.0"
  - type: checkboxes
    attributes:
      label: Windows app type
      description: If you are using WinUI 3, please specify for which Windows app type you have encountered the issue.
      options:
        - label: "UWP"
        - label: "Win32"
  - type: dropdown
    attributes:
      label: Device form factor
      description: Which device form factors did you see the issue on?
      multiple: true
      options:
        - "Desktop"
        - "Xbox"
        - "Surface Hub"
        - "IoT"
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Windows Insider Build (xxxxx)"
        - "Windows 11 (21H2): Build 22000"
        - "Windows 10 (21H2): Build 19044"
        - "Windows 10 (21H1): Build 19043"
        - "Windows 10 (20H2): Build 19042"
        - "Windows 10 (2004): Build 19041"
        - "Windows 10 (1909): Build 18363"
        - "Windows 10 (1903): Build 18362"
        - "Windows 10 (1809): Build 17763"
        - "Windows 10 (1803): Build 17134"
        - "Windows 10 (1709): Build 16299"
        - "Windows 10 (1703): Build 15063"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
