name: Bug report
description: File a bug report
title: "Bug title"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        For bugs related to UWP or the app models, please open a bug on the [Windows App SDK repository](https://github.com/microsoft/WindowsAppSDK)
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    attributes:
      label: NuGet package version
      description: If you are seeing your issue on older versions please try the latest release
      options:
        - "WinUI 3 - Windows App SDK 1.3.3: 1.3.230724000"
        - "WinUI 3 - Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1"
        - "WinUI 3 - Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1"
        - "WinUI 2 - Microsoft.UI.Xaml 2.8.2"
  - type: dropdown
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      multiple: true
      options:
        - "Windows Insider Build (xxxxx)"
        - "Windows 11 (22H2): Build 22621"
        - "Windows 11 (21H2): Build 22000"
        - "Windows 10 (21H2): Build 19044"
        - "Windows 10 (21H1): Build 19043"
        - "Windows 10 (20H2): Build 19042"
        - "Windows 10 (1809): Build 17763"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
