name: Feature Proposal
description: Suggest a new feature
title: "Proposal:"
labels: ["feature proposal", "needs-triage"]
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        This is a template for new feature or API proposals. Please search the existing [Ideas discussion](https://github.com/microsoft/microsoft-ui-xaml/discussions/categories/ideas)
        and issue list first to see if someone else has made a similar proposal.

        This form should be used if you have a more concrete idea of what to propose or have already discussed an idea in the discussion forum.

        For example you can use this to propose a new API on an existing type, or an idea for a new UI control.
        For feature proposals related to UWP or the app models, please open an issue in the [Windows App SDK repository](https://github.com/microsoft/WindowsAppSDK).

        It's fine if you don't have all the details: you can start with the Summary and Rationale.

        This link describes the WinUI feature/API proposal process:
        https://github.com/Microsoft/microsoft-ui-xaml/blob/main/docs/feature_proposal_process.md
  - type: textarea
    validations:
      required: true
    attributes:
      label: Title
      description: Please enter a short, clear title for your feature or API proposal.
      placeholder: |
        e.g. "Add a new property to the X control to control Y"
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: Include 1-2 sentences summarizing your feature or API proposal
  - type: textarea
    validations:
      required: true
    attributes:
      label: Rationale
      description: |
        Create a list that describes WHY the feature should be added to WinUI for all developers and users.
        Proposals often have multiple motives for why we should do the work, so list each one as a separate bullet.
        If applicable you can also describe how the proposal aligns to the current WinUI roadmap and priorities in a separate paragraph:
        https://github.com/Microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md
          * {First reason for why we should consider this proposal}
          * {Second reason for why we should consider this proposal}
          * {etc}
  - type: textarea
    attributes:
      label: Scope
      description: |
        Please include a list of what the feature should and shouldn't do by filling in the table below.
        'Must' implies that the feature should not ship without this capability.  
        'Should' is something we should push hard for, but is not absolutely required to ship.
        'Could' is a nice-to-have; a good stretch goal that isn't painful if we don't achieve it.
        'Won't' is a clear statement that the proposal/feature will intentionally not have that capability.
        This list will evolve and grow as the proposal becomes more refined over time.
        A good rule of thumb is to start your proposal with no more than 7 high-level requirements.
      value: |
        | Capability | Priority |
        | :---------- | :------- |
        | This proposal will allow developers to accomplish W | Must   |
        | This proposal will allow end users to accomplish X  | Should |
        | This proposal will allow developers to accomplish Y | Could  |
        | This proposal will allow end users to accomplish Z  | Won't  |
  - type: textarea
    attributes:
      label: Important Notes
      description: |
        Please include any other important details.
        This could include one or more of:
        - usage examples
        - an API proposal (any supported language or pseudocode is fine)
        - design mockups or example screenshots
        - other implementation notes
  - type: textarea
    attributes:
      label: Open Questions
      description: |
        Please list any open issues that you think still need to be addressed.
        These could include areas you think would benefit from community or WinUI team input.
