[WUXC_VERSION_RS5]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass NEWCONTROL : Windows.UI.Xaml.Controls.Control
{
    NEWCONTROL();

    Object Placeholder{ get; set; };

    static Windows.UI.Xaml.DependencyProperty PlaceholderProperty{ get; };
}
