// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once


#define __ApplicationInitializationCallbackParams_GUID "50f58b0f-03dd-496f-ad6d-27d88079d3b5"

namespace DirectUI
{
    class ApplicationInitializationCallbackParams;

    class __declspec(novtable) __declspec(uuid(__ApplicationInitializationCallbackParams_GUID)) ApplicationInitializationCallbackParams:
        public ctl::WeakReferenceSource
        , public ABI::Microsoft::UI::Xaml::IApplicationInitializationCallbackParams
    {

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.ApplicationInitializationCallbackParams");

        BEGIN_INTERFACE_MAP(ApplicationInitializationCallbackParams, ctl::WeakReferenceSource)
            INTERFACE_ENTRY(ApplicationInitializationCallbackParams, ABI::Microsoft::UI::Xaml::IApplicationInitializationCallbackParams)
        END_INTERFACE_MAP(ApplicationInitializationCallbackParams, ctl::WeakReferenceSource)

    public:
        ApplicationInitializationCallbackParams();
        ~ApplicationInitializationCallbackParams() override;

        // Event source typedefs.


        // Properties.

        // Events.

        // Methods.


    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:
        // Customized properties.

        // Customized methods.

        // Fields.
    };
}


