// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once


#define __DatePickerValueChangedEventArgs_GUID "480b852f-078a-48a0-bfad-8a66a7f53fcc"

namespace DirectUI
{
    class DatePickerValueChangedEventArgs;

    class __declspec(novtable) DatePickerValueChangedEventArgsGenerated :
        public ABI::Microsoft::UI::Xaml::Controls::IDatePickerValueChangedEventArgs,
        public DirectUI::EventArgs
    {
        friend class DirectUI::DatePickerValueChangedEventArgs;

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Controls.DatePickerValueChangedEventArgs");

        BEGIN_INTERFACE_MAP(DatePickerValueChangedEventArgsGenerated, DirectUI::EventArgs)
            INTERFACE_ENTRY(DatePickerValueChangedEventArgsGenerated, ABI::Microsoft::UI::Xaml::Controls::IDatePickerValueChangedEventArgs)
        END_INTERFACE_MAP(DatePickerValueChangedEventArgsGenerated, DirectUI::EventArgs)

    public:
        DatePickerValueChangedEventArgsGenerated();
        ~DatePickerValueChangedEventArgsGenerated() override;

        // Properties.
        IFACEMETHOD(get_OldDate)(_Out_ ABI::Windows::Foundation::DateTime* pValue) override;
        _Check_return_ HRESULT put_OldDate(_In_ ABI::Windows::Foundation::DateTime value);
        IFACEMETHOD(get_NewDate)(_Out_ ABI::Windows::Foundation::DateTime* pValue) override;
        _Check_return_ HRESULT put_NewDate(_In_ ABI::Windows::Foundation::DateTime value);

        // Methods.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:

        // Fields.
        ABI::Windows::Foundation::DateTime m_oldDate;
        ABI::Windows::Foundation::DateTime m_newDate;
    };
}

#include "DatePickerValueChangedEventArgs_Partial.h"

