// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include "RoutedEventArgs.g.h"

#define __DragCompletedEventArgs_GUID "b2710805-5d88-454d-99e4-f6fb002b35bc"

namespace DirectUI
{
    class DragCompletedEventArgs;

    class __declspec(novtable) DragCompletedEventArgsGenerated :
        public ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgs,
        public DirectUI::RoutedEventArgs
    {
        friend class DirectUI::DragCompletedEventArgs;

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Controls.Primitives.DragCompletedEventArgs");

        BEGIN_INTERFACE_MAP(DragCompletedEventArgsGenerated, DirectUI::RoutedEventArgs)
            INTERFACE_ENTRY(DragCompletedEventArgsGenerated, ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgs)
        END_INTERFACE_MAP(DragCompletedEventArgsGenerated, DirectUI::RoutedEventArgs)

    public:
        DragCompletedEventArgsGenerated();
        ~DragCompletedEventArgsGenerated() override;

        // Properties.
        IFACEMETHOD(get_HorizontalChange)(_Out_ DOUBLE* pValue) override;
        _Check_return_ HRESULT put_HorizontalChange(_In_ DOUBLE value);
        IFACEMETHOD(get_VerticalChange)(_Out_ DOUBLE* pValue) override;
        _Check_return_ HRESULT put_VerticalChange(_In_ DOUBLE value);
        IFACEMETHOD(get_Canceled)(_Out_ BOOLEAN* pValue) override;
        _Check_return_ HRESULT put_Canceled(_In_ BOOLEAN value);

        // Methods.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:

        // Fields.
    };
}

#include "DragCompletedEventArgs_Partial.h"

namespace DirectUI
{
    // Note that the ordering of the base types here is important - the base factory comes first, followed by all the
    // interfaces specific to this type.  By doing this, we allow every Factory's CreateInstance method to be more
    // COMDAT-folding-friendly.  Because this ensures that the first vfptr contains GetTypeIndex, it means that all
    // CreateInstance functions with the same base factory generate the same assembly instructions and thus will
    // fold together.  This is significant for binary size in Microsoft.UI.Xaml.dll so change this only with great
    // care.
    class __declspec(novtable) DragCompletedEventArgsFactory:
       public ctl::AggregableActivationFactory<DirectUI::DragCompletedEventArgs>
        , public ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgsFactory
    {
        BEGIN_INTERFACE_MAP(DragCompletedEventArgsFactory, ctl::AggregableActivationFactory<DirectUI::DragCompletedEventArgs>)
            INTERFACE_ENTRY(DragCompletedEventArgsFactory, ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgsFactory)
        END_INTERFACE_MAP(DragCompletedEventArgsFactory, ctl::AggregableActivationFactory<DirectUI::DragCompletedEventArgs>)

    public:
        // Factory methods.
        IFACEMETHOD(CreateInstanceWithHorizontalChangeVerticalChangeAndCanceled)(_In_ DOUBLE horizontalChange, _In_ DOUBLE verticalChange, _In_ BOOLEAN canceled, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgs** ppInstance);

        // Static properties.

        // Dependency properties.

        // Attached properties.

        // Static methods.

        // Static events.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;



    private:
        _Check_return_ HRESULT CreateInstanceWithHorizontalChangeVerticalChangeAndCanceledImpl(_In_ DOUBLE horizontalChange, _In_ DOUBLE verticalChange, _In_ BOOLEAN canceled, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Controls::Primitives::IDragCompletedEventArgs** ppInstance);

        // Customized static properties.

        // Customized static  methods.
    };
}
