// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include "RoutedEventArgs.g.h"

#define __DropCompletedEventArgs_GUID "7c1a59cb-0f5d-4604-9017-2cc8227b0fd5"

namespace DirectUI
{
    class DropCompletedEventArgs;

    class __declspec(novtable) __declspec(uuid(__DropCompletedEventArgs_GUID)) DropCompletedEventArgs :
        public ABI::Microsoft::UI::Xaml::IDropCompletedEventArgs,
        public DirectUI::RoutedEventArgs
    {

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.DropCompletedEventArgs");

        BEGIN_INTERFACE_MAP(DropCompletedEventArgs, DirectUI::RoutedEventArgs)
            INTERFACE_ENTRY(DropCompletedEventArgs, ABI::Microsoft::UI::Xaml::IDropCompletedEventArgs)
        END_INTERFACE_MAP(DropCompletedEventArgs, DirectUI::RoutedEventArgs)

    public:
        DropCompletedEventArgs();
        ~DropCompletedEventArgs() override;

        // Properties.
        IFACEMETHOD(get_DropResult)(_Out_ ABI::Windows::ApplicationModel::DataTransfer::DataPackageOperation* pValue) override;
        _Check_return_ HRESULT put_DropResult(_In_ ABI::Windows::ApplicationModel::DataTransfer::DataPackageOperation value);

        // Methods.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:
        // Customized properties.

        // Customized methods.

        // Fields.
        ABI::Windows::ApplicationModel::DataTransfer::DataPackageOperation m_dropResult;
    };
}


