// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#include "FrameNavigationOptions.g.h"
#include "NavigationTransitionInfo.g.h"

// Constructors/destructors.
DirectUI::FrameNavigationOptions::FrameNavigationOptions(): m_isNavigationStackEnabled()
{
}

DirectUI::FrameNavigationOptions::~FrameNavigationOptions()
{
}

HRESULT DirectUI::FrameNavigationOptions::QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject)
{
    if (InlineIsEqualGUID(iid, __uuidof(DirectUI::FrameNavigationOptions)))
    {
        *ppObject = static_cast<DirectUI::FrameNavigationOptions*>(this);
    }
    else if (InlineIsEqualGUID(iid, __uuidof(ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptions)))
    {
        *ppObject = static_cast<ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptions*>(this);
    }
    else
    {
        RRETURN(ctl::WeakReferenceSource::QueryInterfaceImpl(iid, ppObject));
    }

    AddRefOuter();
    RRETURN(S_OK);
}

// Properties.
IFACEMETHODIMP DirectUI::FrameNavigationOptions::get_IsNavigationStackEnabled(_Out_ BOOLEAN* pValue)
{
    HRESULT hr = S_OK;
    ARG_VALIDRETURNPOINTER(pValue);
    IFC(CheckThread());
    IFC(CValueBoxer::CopyValue(m_isNavigationStackEnabled, pValue));
Cleanup:
    RRETURN(hr);
}
IFACEMETHODIMP DirectUI::FrameNavigationOptions::put_IsNavigationStackEnabled(_In_ BOOLEAN value)
{
    HRESULT hr = S_OK;
    IFC(CheckThread());
    IFC(CValueBoxer::CopyValue(value, &m_isNavigationStackEnabled));
Cleanup:
    RRETURN(hr);
}
IFACEMETHODIMP DirectUI::FrameNavigationOptions::get_TransitionInfoOverride(_Outptr_result_maybenull_ ABI::Microsoft::UI::Xaml::Media::Animation::INavigationTransitionInfo** ppValue)
{
    HRESULT hr = S_OK;
    ARG_VALIDRETURNPOINTER(ppValue);
    IFC(CheckThread());
    IFC(m_pTransitionInfoOverride.CopyTo(ppValue));
Cleanup:
    RRETURN(hr);
}
IFACEMETHODIMP DirectUI::FrameNavigationOptions::put_TransitionInfoOverride(_In_opt_ ABI::Microsoft::UI::Xaml::Media::Animation::INavigationTransitionInfo* pValue)
{
    HRESULT hr = S_OK;
    IFC(CheckThread());
    SetPtrValue(m_pTransitionInfoOverride, pValue);
Cleanup:
    RRETURN(hr);
}

// Events.

// Methods.

HRESULT DirectUI::FrameNavigationOptionsFactory::QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject)
{
    if (InlineIsEqualGUID(iid, __uuidof(ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptionsFactory)))
    {
        *ppObject = static_cast<ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptionsFactory*>(this);
    }
    else
    {
        RRETURN(ctl::AggregableActivationFactory<DirectUI::FrameNavigationOptions>::QueryInterfaceImpl(iid, ppObject));
    }

    AddRefOuter();
    RRETURN(S_OK);
}


// Factory methods.
IFACEMETHODIMP DirectUI::FrameNavigationOptionsFactory::CreateInstance(_In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptions** ppInstance)
{


    // Can't just IFC(_RETURN) this because for some validate calls (those with multiple template parameters), the
    // preprocessor gets confused at the "," in the template type-list before the function's opening parenthesis.
    // So we'll use IFC_RETURN syntax with a local hr variable, kind of weirdly.
    const HRESULT hr = ctl::ValidateFactoryCreateInstanceWithAggregableActivationFactory<DirectUI::FrameNavigationOptions,ABI::Microsoft::UI::Xaml::Navigation::IFrameNavigationOptions>(pOuter, ppInner, reinterpret_cast<IUnknown**>(ppInstance), GetTypeIndex(), false /*isFreeThreaded*/);
    IFC_RETURN(hr);
    return S_OK;
}

// Dependency properties.

// Attached properties.

// Static properties.

// Static methods.

namespace DirectUI
{
    _Check_return_ IActivationFactory* CreateActivationFactory_FrameNavigationOptions()
    {
        RRETURN(ctl::ActivationFactoryCreator<FrameNavigationOptionsFactory>::CreateActivationFactory());
    }
}
