// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include <FeatureFlags.h>
#if WI_IS_FEATURE_PRESENT(Feature_InputValidation) 
#define FEATURE_INPUTVALIDATION_OVERRIDE override
#else
#define FEATURE_INPUTVALIDATION_OVERRIDE
#endif
#define __InputValidationContext_GUID "9ec15c00-97d1-4125-b0d8-7ac11ae0791e"

namespace DirectUI
{
    class InputValidationContext;

    class __declspec(novtable) __declspec(uuid(__InputValidationContext_GUID)) InputValidationContext:
        public ctl::WeakReferenceSource
#if WI_IS_FEATURE_PRESENT(Feature_InputValidation)
        , public ABI::Microsoft::UI::Xaml::Controls::IInputValidationContext
#endif
    {

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Controls.InputValidationContext");

        BEGIN_INTERFACE_MAP(InputValidationContext, ctl::WeakReferenceSource)
#if WI_IS_FEATURE_PRESENT(Feature_InputValidation)
            INTERFACE_ENTRY(InputValidationContext, ABI::Microsoft::UI::Xaml::Controls::IInputValidationContext)
#else
            INTERFACE_ENTRY(DUMMYINTERFACE, IUnknown)
#endif
        END_INTERFACE_MAP(InputValidationContext, ctl::WeakReferenceSource)

    public:
        InputValidationContext();
        ~InputValidationContext() override;

        // Event source typedefs.

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::InputValidationContext;
        }

        static XCP_FORCEINLINE KnownTypeIndex GetTypeIndexStatic()
        {
            return KnownTypeIndex::InputValidationContext;
        }

        // Properties.
        IFACEMETHOD(get_IsInputRequired)(_Out_ BOOLEAN* pValue) FEATURE_INPUTVALIDATION_OVERRIDE;
        _Check_return_ HRESULT put_IsInputRequired(_In_ BOOLEAN value);
        IFACEMETHOD(get_MemberName)(_Out_ HSTRING* pValue) FEATURE_INPUTVALIDATION_OVERRIDE;
        _Check_return_ HRESULT put_MemberName(_In_opt_ HSTRING value);

        // Events.

        // Methods.


    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:
        // Customized properties.

        // Customized methods.

        // Fields.
        BOOLEAN m_isInputRequired;
        Microsoft::WRL::Wrappers::HString m_pMemberName;
    };
}


namespace DirectUI
{
    // Note that the ordering of the base types here is important - the base factory comes first, followed by all the
    // interfaces specific to this type.  By doing this, we allow every Factory's CreateInstance method to be more
    // COMDAT-folding-friendly.  Because this ensures that the first vfptr contains GetTypeIndex, it means that all
    // CreateInstance functions with the same base factory generate the same assembly instructions and thus will
    // fold together.  This is significant for binary size in Microsoft.UI.Xaml.dll so change this only with great
    // care.
    class __declspec(novtable) InputValidationContextFactory:
       public ctl::AggregableActivationFactory<DirectUI::InputValidationContext>
#if WI_IS_FEATURE_PRESENT(Feature_InputValidation)
        , public ABI::Microsoft::UI::Xaml::Controls::IInputValidationContextFactory
#endif
    {
        BEGIN_INTERFACE_MAP(InputValidationContextFactory, ctl::AggregableActivationFactory<DirectUI::InputValidationContext>)
#if WI_IS_FEATURE_PRESENT(Feature_InputValidation)
            INTERFACE_ENTRY(InputValidationContextFactory, ABI::Microsoft::UI::Xaml::Controls::IInputValidationContextFactory)
#else
            INTERFACE_ENTRY(DUMMYINTERFACE, IUnknown)
#endif
        END_INTERFACE_MAP(InputValidationContextFactory, ctl::AggregableActivationFactory<DirectUI::InputValidationContext>)

    public:
        // Factory methods.
        IFACEMETHOD(CreateInstance)(_In_ HSTRING memberName, _In_ BOOLEAN isRequired, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Controls::IInputValidationContext** ppInstance);

        // Static properties.

        // Dependency properties.

        // Attached properties.

        // Static methods.

        // Static events.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::InputValidationContext;
        }


    private:
        _Check_return_ HRESULT CreateInstanceImpl(_In_ HSTRING memberName, _In_ BOOLEAN isRequired, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Controls::IInputValidationContext** ppInstance);

        // Customized static properties.

        // Customized static  methods.
    };
}
