// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#include "KeySpline.g.h"
#include "XamlTelemetry.h"

// Constructors/destructors.
DirectUI::KeySpline::KeySpline()
{
}

DirectUI::KeySpline::~KeySpline()
{
}

HRESULT DirectUI::KeySpline::QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject)
{
    if (InlineIsEqualGUID(iid, __uuidof(DirectUI::KeySpline)))
    {
        *ppObject = static_cast<DirectUI::KeySpline*>(this);
    }
    else if (InlineIsEqualGUID(iid, __uuidof(ABI::Microsoft::UI::Xaml::Media::Animation::IKeySpline)))
    {
        *ppObject = static_cast<ABI::Microsoft::UI::Xaml::Media::Animation::IKeySpline*>(this);
    }
    else
    {
        RRETURN(DirectUI::DependencyObject::QueryInterfaceImpl(iid, ppObject));
    }

    AddRefOuter();
    RRETURN(S_OK);
}

// Properties.
IFACEMETHODIMP DirectUI::KeySpline::get_ControlPoint1(_Out_ ABI::Windows::Foundation::Point* pValue)
{
    RRETURN(GetValueByKnownIndex(KnownPropertyIndex::KeySpline_ControlPoint1, pValue));
}
IFACEMETHODIMP DirectUI::KeySpline::put_ControlPoint1(_In_ ABI::Windows::Foundation::Point value)
{
    IFC_RETURN(DefaultStrictApiCheck(this));
    RRETURN(SetValueByKnownIndex(KnownPropertyIndex::KeySpline_ControlPoint1, value));
}
IFACEMETHODIMP DirectUI::KeySpline::get_ControlPoint2(_Out_ ABI::Windows::Foundation::Point* pValue)
{
    RRETURN(GetValueByKnownIndex(KnownPropertyIndex::KeySpline_ControlPoint2, pValue));
}
IFACEMETHODIMP DirectUI::KeySpline::put_ControlPoint2(_In_ ABI::Windows::Foundation::Point value)
{
    IFC_RETURN(DefaultStrictApiCheck(this));
    RRETURN(SetValueByKnownIndex(KnownPropertyIndex::KeySpline_ControlPoint2, value));
}

// Events.

// Methods.

// Factory methods.

// Dependency properties.



// Attached properties.

// Static properties.

// Static methods.

namespace DirectUI
{
    _Check_return_ IActivationFactory* CreateActivationFactory_KeySpline()
    {
        RRETURN(ctl::ActivationFactoryCreator<KeySplineFactory>::CreateActivationFactory());
    }
}
