// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include "SelectorItemAutomationPeer.g.h"

#define __ListViewBaseItemDataAutomationPeer_GUID "f875aa65-e76c-4e07-b0b5-0063b058838a"

namespace DirectUI
{
    class ListViewBaseItemDataAutomationPeer;

    class __declspec(novtable) ListViewBaseItemDataAutomationPeerGenerated:
        public DirectUI::SelectorItemAutomationPeer
    {
        friend class DirectUI::ListViewBaseItemDataAutomationPeer;



    public:
        ListViewBaseItemDataAutomationPeerGenerated();
        ~ListViewBaseItemDataAutomationPeerGenerated() override;

        // Event source typedefs.

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::ListViewBaseItemDataAutomationPeer;
        }

        static XCP_FORCEINLINE KnownTypeIndex GetTypeIndexStatic()
        {
            return KnownTypeIndex::ListViewBaseItemDataAutomationPeer;
        }

        // Properties.

        // Events.

        // Methods.


    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:

        // Fields.
    };
}

#include "ListViewBaseItemDataAutomationPeer_Partial.h"

