// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include "ListViewBaseItemAutomationPeer.g.h"

#define __ListViewItemAutomationPeer_GUID "cfa5a4a2-6f23-4f0b-8185-81d8ce109657"

namespace DirectUI
{
    class ListViewItemAutomationPeer;

    class __declspec(novtable) ListViewItemAutomationPeerGenerated:
        public DirectUI::ListViewBaseItemAutomationPeer
        , public ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeer
    {
        friend class DirectUI::ListViewItemAutomationPeer;

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Automation.Peers.ListViewItemAutomationPeer");

        BEGIN_INTERFACE_MAP(ListViewItemAutomationPeerGenerated, DirectUI::ListViewBaseItemAutomationPeer)
            INTERFACE_ENTRY(ListViewItemAutomationPeerGenerated, ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeer)
        END_INTERFACE_MAP(ListViewItemAutomationPeerGenerated, DirectUI::ListViewBaseItemAutomationPeer)

    public:
        ListViewItemAutomationPeerGenerated();
        ~ListViewItemAutomationPeerGenerated() override;

        // Event source typedefs.

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::ListViewItemAutomationPeer;
        }

        static XCP_FORCEINLINE KnownTypeIndex GetTypeIndexStatic()
        {
            return KnownTypeIndex::ListViewItemAutomationPeer;
        }

        // Properties.

        // Events.

        // Methods.


    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:

        // Fields.
    };
}

#include "ListViewItemAutomationPeer_Partial.h"

namespace DirectUI
{
    // Note that the ordering of the base types here is important - the base factory comes first, followed by all the
    // interfaces specific to this type.  By doing this, we allow every Factory's CreateInstance method to be more
    // COMDAT-folding-friendly.  Because this ensures that the first vfptr contains GetTypeIndex, it means that all
    // CreateInstance functions with the same base factory generate the same assembly instructions and thus will
    // fold together.  This is significant for binary size in Microsoft.UI.Xaml.dll so change this only with great
    // care.
    class __declspec(novtable) ListViewItemAutomationPeerFactory:
       public ctl::BetterAggregableCoreObjectActivationFactory
        , public ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeerFactory
    {
        BEGIN_INTERFACE_MAP(ListViewItemAutomationPeerFactory, ctl::BetterAggregableCoreObjectActivationFactory)
            INTERFACE_ENTRY(ListViewItemAutomationPeerFactory, ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeerFactory)
        END_INTERFACE_MAP(ListViewItemAutomationPeerFactory, ctl::BetterAggregableCoreObjectActivationFactory)

    public:
        // Factory methods.
        IFACEMETHOD(CreateInstanceWithOwner)(_In_ ABI::Microsoft::UI::Xaml::Controls::IListViewItem* pOwner, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeer** ppInstance);

        // Static properties.

        // Dependency properties.

        // Attached properties.

        // Static methods.

        // Static events.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::ListViewItemAutomationPeer;
        }


    private:
        _Check_return_ HRESULT CreateInstanceWithOwnerImpl(_In_ ABI::Microsoft::UI::Xaml::Controls::IListViewItem* pOwner, _In_opt_ IInspectable* pOuter, _Outptr_ IInspectable** ppInner, _Outptr_ ABI::Microsoft::UI::Xaml::Automation::Peers::IListViewItemAutomationPeer** ppInstance);

        // Customized static properties.

        // Customized static  methods.
    };
}
