// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

#include "Transform.g.h"

#define __RotateTransform_GUID "ea45e69d-7527-4314-aea3-1bba433c65a9"

namespace DirectUI
{
    class RotateTransform;

    class __declspec(novtable) __declspec(uuid(__RotateTransform_GUID)) RotateTransform:
        public DirectUI::Transform
        , public ABI::Microsoft::UI::Xaml::Media::IRotateTransform
    {

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Media.RotateTransform");

        BEGIN_INTERFACE_MAP(RotateTransform, DirectUI::Transform)
            INTERFACE_ENTRY(RotateTransform, ABI::Microsoft::UI::Xaml::Media::IRotateTransform)
        END_INTERFACE_MAP(RotateTransform, DirectUI::Transform)

    public:
        RotateTransform();
        ~RotateTransform() override;

        // Event source typedefs.

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::RotateTransform;
        }

        static XCP_FORCEINLINE KnownTypeIndex GetTypeIndexStatic()
        {
            return KnownTypeIndex::RotateTransform;
        }

        // Properties.
        IFACEMETHOD(get_Angle)(_Out_ DOUBLE* pValue) override;
        IFACEMETHOD(put_Angle)(_In_ DOUBLE value) override;
        _Check_return_ HRESULT get_AngleAnimation(_Outptr_result_maybenull_ IInspectable** ppValue);
        _Check_return_ HRESULT put_AngleAnimation(_In_opt_ IInspectable* pValue);
        IFACEMETHOD(get_CenterX)(_Out_ DOUBLE* pValue) override;
        IFACEMETHOD(put_CenterX)(_In_ DOUBLE value) override;
        _Check_return_ HRESULT get_CenterXAnimation(_Outptr_result_maybenull_ IInspectable** ppValue);
        _Check_return_ HRESULT put_CenterXAnimation(_In_opt_ IInspectable* pValue);
        IFACEMETHOD(get_CenterY)(_Out_ DOUBLE* pValue) override;
        IFACEMETHOD(put_CenterY)(_In_ DOUBLE value) override;
        _Check_return_ HRESULT get_CenterYAnimation(_Outptr_result_maybenull_ IInspectable** ppValue);
        _Check_return_ HRESULT put_CenterYAnimation(_In_opt_ IInspectable* pValue);

        // Events.

        // Methods.


    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:
        // Customized properties.

        // Customized methods.

        // Fields.
    };
}


namespace DirectUI
{
    // Note that the ordering of the base types here is important - the base factory comes first, followed by all the
    // interfaces specific to this type.  By doing this, we allow every Factory's CreateInstance method to be more
    // COMDAT-folding-friendly.  Because this ensures that the first vfptr contains GetTypeIndex, it means that all
    // CreateInstance functions with the same base factory generate the same assembly instructions and thus will
    // fold together.  This is significant for binary size in Microsoft.UI.Xaml.dll so change this only with great
    // care.
    class __declspec(novtable) RotateTransformFactory:
       public ctl::BetterCoreObjectActivationFactory
        , public ABI::Microsoft::UI::Xaml::Media::IRotateTransformStatics
    {
        BEGIN_INTERFACE_MAP(RotateTransformFactory, ctl::BetterCoreObjectActivationFactory)
            INTERFACE_ENTRY(RotateTransformFactory, ABI::Microsoft::UI::Xaml::Media::IRotateTransformStatics)
        END_INTERFACE_MAP(RotateTransformFactory, ctl::BetterCoreObjectActivationFactory)

    public:
        // Factory methods.

        // Static properties.

        // Dependency properties.
        IFACEMETHOD(get_CenterXProperty)(_Out_ ABI::Microsoft::UI::Xaml::IDependencyProperty** ppValue) override;
        
        IFACEMETHOD(get_CenterYProperty)(_Out_ ABI::Microsoft::UI::Xaml::IDependencyProperty** ppValue) override;
        
        IFACEMETHOD(get_AngleProperty)(_Out_ ABI::Microsoft::UI::Xaml::IDependencyProperty** ppValue) override;
        

        // Attached properties.

        // Static methods.

        // Static events.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

        KnownTypeIndex GetTypeIndex() const override
        {
            return KnownTypeIndex::RotateTransform;
        }


    private:

        // Customized static properties.

        // Customized static  methods.
    };
}
