// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once


#define __SvgImageSourceFailedEventArgs_GUID "4eb20bec-e6c4-41c6-b301-6a29da9092f8"

namespace DirectUI
{
    class SvgImageSourceFailedEventArgs;

    class __declspec(novtable) __declspec(uuid(__SvgImageSourceFailedEventArgs_GUID)) SvgImageSourceFailedEventArgs :
        public ABI::Microsoft::UI::Xaml::Media::Imaging::ISvgImageSourceFailedEventArgs,
        public DirectUI::EventArgs
    {

        INSPECTABLE_CLASS(L"Microsoft.UI.Xaml.Media.Imaging.SvgImageSourceFailedEventArgs");

        BEGIN_INTERFACE_MAP(SvgImageSourceFailedEventArgs, DirectUI::EventArgs)
            INTERFACE_ENTRY(SvgImageSourceFailedEventArgs, ABI::Microsoft::UI::Xaml::Media::Imaging::ISvgImageSourceFailedEventArgs)
        END_INTERFACE_MAP(SvgImageSourceFailedEventArgs, DirectUI::EventArgs)

    public:
        SvgImageSourceFailedEventArgs();
        ~SvgImageSourceFailedEventArgs() override;

        // Properties.
        IFACEMETHOD(get_Status)(_Out_ ABI::Microsoft::UI::Xaml::Media::Imaging::SvgImageSourceLoadStatus* pValue) override;
        _Check_return_ HRESULT put_Status(_In_ ABI::Microsoft::UI::Xaml::Media::Imaging::SvgImageSourceLoadStatus value);

        // Methods.

    protected:
        HRESULT QueryInterfaceImpl(_In_ REFIID iid, _Outptr_ void** ppObject) override;

    private:
        // Customized properties.

        // Customized methods.

        // Fields.
    };
}


