namespace MU_XCP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ColorPickerSlider : Windows.UI.Xaml.Controls.Slider
{
    ColorPickerSlider();

    [MUX_DEFAULT_VALUE("winrt::ColorPickerHsvChannel::Value")]
    MU_XC_NAMESPACE.ColorPickerHsvChannel ColorChannel { get; set; };

    static Windows.UI.Xaml.DependencyProperty ColorChannelProperty { get; };
}

}
