namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ColorPickerSliderAutomationPeer : Windows.UI.Xaml.Automation.Peers.SliderAutomationPeer
{
    [method_name("CreateInstanceWithOwner")] ColorPickerSliderAutomationPeer(MU_XCP_NAMESPACE.ColorPickerSlider owner);
}

}