namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass ColorSpectrumAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    [method_name("CreateInstanceWithOwner")] ColorSpectrumAutomationPeer(MU_XCP_NAMESPACE.ColorSpectrum owner);
}

}