namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_RS3]
[webhosthidden]
enum ColorSpectrumShape
{
    Box = 0,
    Ring = 1,
};

[WUXC_VERSION_RS3]
[webhosthidden]
enum ColorSpectrumComponents
{
    HueValue = 0,
    ValueHue = 1,
    HueSaturation = 2,
    SaturationHue = 3,
    SaturationValue = 4,
    ValueSaturation = 5,
};

[WUXC_VERSION_RS3]
[webhosthidden]
enum ColorPickerHsvChannel
{
    Hue = 0,
    Saturation = 1,
    Value = 2,
    Alpha = 3,
};

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IColorChangedEventArgs", 34f7201f-aad0-4c3a-b97b-2abf36455539)]
runtimeclass ColorChangedEventArgs
{
    Windows.UI.Color OldColor { get; };
    Windows.UI.Color NewColor { get; };
}

}