namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
enum ColorSpectrumShape
{
    Box = 0,
    Ring = 1,
};

[MUX_PUBLIC]
[webhosthidden]
enum ColorSpectrumComponents
{
    HueValue = 0,
    ValueHue = 1,
    HueSaturation = 2,
    SaturationHue = 3,
    SaturationValue = 4,
    ValueSaturation = 5,
};

[MUX_PUBLIC]
[webhosthidden]
enum ColorPickerHsvChannel
{
    Hue = 0,
    Saturation = 1,
    Value = 2,
    Alpha = 3,
};

[MUX_PUBLIC]
[webhosthidden]
runtimeclass ColorChangedEventArgs
{
    Windows.UI.Color OldColor { get; };
    Windows.UI.Color NewColor { get; };
}

}