namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
runtimeclass SpectrumBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    SpectrumBrush();

    Windows.UI.Xaml.Media.LoadedImageSurface MinSurface { get; set; };
    Windows.UI.Xaml.Media.LoadedImageSurface MaxSurface { get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double MaxSurfaceOpacity { get; set; };

    static Windows.UI.Xaml.DependencyProperty MinSurfaceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxSurfaceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxSurfaceOpacityProperty { get; };
}

}