namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass DisplayRegionHelperTestApi
{
    static Boolean SimulateDisplayRegions { get; set; };
    static MU_XC_NAMESPACE.TwoPaneViewMode SimulateMode { get; set; };
}

}