namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_19H1]
[webhosthidden]
enum TwoPaneViewPriority
{
    Pane1 = 0,
    Pane2 = 1,
};

[WUXC_VERSION_19H1]
[webhosthidden]
enum TwoPaneViewMode
{
    SinglePane = 0,
    Wide = 1,
    Tall = 2,
};

[WUXC_VERSION_19H1]
[webhosthidden]
enum TwoPaneViewWideModeConfiguration
{
    SinglePane = 0,
    LeftRight = 1,
    RightLeft = 2,
};

[WUXC_VERSION_19H1]
[webhosthidden]
enum TwoPaneViewTallModeConfiguration
{
    SinglePane = 0,
    TopBottom = 1,
    BottomTop = 2,
};

[WUXC_VERSION_19H1]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass TwoPaneView : Windows.UI.Xaml.Controls.Control
{
    TwoPaneView();

    Windows.UI.Xaml.UIElement Pane1 { get; set; };
    Windows.UI.Xaml.UIElement Pane2 { get; set; };
    [MUX_DEFAULT_VALUE("c_pane1LengthDefault")]
    Windows.UI.Xaml.GridLength Pane1Length { get; set; };
    [MUX_DEFAULT_VALUE("c_pane2LengthDefault")]
    Windows.UI.Xaml.GridLength Pane2Length { get; set; };
    [MUX_DEFAULT_VALUE("winrt::TwoPaneViewPriority::Pane1")]
    TwoPaneViewPriority PanePriority { get; set; };
    [MUX_DEFAULT_VALUE("winrt::TwoPaneViewMode::SinglePane")]
    [MUX_PROPERTY_CHANGED_CALLBACK(FALSE)]
    TwoPaneViewMode Mode { get; };
    [MUX_DEFAULT_VALUE("winrt::TwoPaneViewWideModeConfiguration::LeftRight")]
    TwoPaneViewWideModeConfiguration WideModeConfiguration { get; set; };
    [MUX_DEFAULT_VALUE("winrt::TwoPaneViewTallModeConfiguration::TopBottom")]
    TwoPaneViewTallModeConfiguration TallModeConfiguration{ get; set; };
    [MUX_DEFAULT_VALUE("c_defaultMinWideModeWidth")]
    Double MinWideModeWidth { get; set; };
    [MUX_DEFAULT_VALUE("c_defaultMinTallModeHeight")]
    Double MinTallModeHeight { get; set; };
    event Windows.Foundation.TypedEventHandler<TwoPaneView, Object> ModeChanged;

    static Windows.UI.Xaml.DependencyProperty Pane1Property { get; };
    static Windows.UI.Xaml.DependencyProperty Pane2Property { get; };
    static Windows.UI.Xaml.DependencyProperty Pane1LengthProperty { get; };
    static Windows.UI.Xaml.DependencyProperty Pane2LengthProperty { get; };
    static Windows.UI.Xaml.DependencyProperty PanePriorityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ModeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty WideModeConfigurationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TallModeConfigurationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MinWideModeWidthProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MinTallModeHeightProperty { get; };
}

// TODO: Once IApplicationViewSpanningRects is available in the official SDK, remove this.
[WUXC_VERSION_INTERNAL]
[webhosthidden]
[uuid(645737E4-A882-4E16-B289-FD860560106A)]
interface IApplicationViewSpanningRects : IInspectable
{
    Windows.Foundation.Collections.IVectorView<Windows.Foundation.Rect> GetSpanningRects();
}

}
