namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass RepeaterAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    RepeaterAutomationPeer(MU_XC_NAMESPACE.ItemsRepeater owner);
}

}