// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
using XamlOM;

[assembly: Namespace(Order = 0, Name = "Microsoft.UI.Xaml.ComponentModel", IndexName = "NAMESPACE_INDEX_COMPONENT_MODEL", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 1, Name = "Windows.Media.Capture", IndexName = "NAMESPACE_INDEX_WINDOWS_MEDIA_CAPTURE")]
[assembly: Namespace(Order = 2, Name = "Windows.Media.Protection", IndexName = "NAMESPACE_INDEX_WINDOWS_MEDIA_PROTECTION")]
[assembly: Namespace(Order = 4, Name = "Windows.System", IndexName = "NAMESPACE_INDEX_WINDOWS_SYSTEM")]
[assembly: Namespace(Order = 5, Name = "Microsoft.UI.Input", IndexName = "NAMESPACE_INDEX_MICROSOFT_UI_INPUT")]
[assembly: Namespace(Order = 6, Name = "Windows.Storage.Streams", IndexName = "NAMESPACE_INDEX_WINDOWS_STORAGE_STREAMS")]
[assembly: Namespace(Order = 7, Name = "Windows.UI", IndexName = "NAMESPACE_INDEX_WINDOWS_UI")]
[assembly: Namespace(Order = 8, Name = "Windows.UI.Input", IndexName = "NAMESPACE_INDEX_WINDOWS_UI_INPUT")]
[assembly: Namespace(Order = 9, Name = "Windows.UI.Core", IndexName = "NAMESPACE_INDEX_WINDOWS_UI_CORE")]
[assembly: Namespace(Order = 10, Name = "Windows.UI.Text", IndexName = "NAMESPACE_INDEX_WINDOWS_UI_TEXT")]
[assembly: Namespace(Order = 11, Name = "Windows.ApplicationModel", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 12, Name = "Windows.ApplicationModel.Activation", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL_ACTIVATION", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 13, Name = "Windows.ApplicationModel.Core", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL_CORE", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 14, Name = "Windows.Foundation", IndexName = "NAMESPACE_INDEX_SYSTEM")]
[assembly: Namespace(Order = 15, Name = "Windows.Foundation.Collections", IndexName = "NAMESPACE_INDEX_WINDOWS_FOUNDATION_COLLECTIONS")]
[assembly: Namespace(Order = 16, Name = "Windows.ApplicationModel.DataTransfer", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL_DATATRANSFER")]
[assembly: Namespace(Order = 17, Name = "Microsoft.UI.Xaml", IndexName = "NAMESPACE_INDEX_DEFAULT")]
[assembly: Namespace(Order = 18, Name = "Microsoft.UI.Xaml.Resources", IndexName = "NAMESPACE_INDEX_SYSTEM_RESOURCES")]
[assembly: Namespace(Order = 20, Name = "Microsoft.UI.Xaml.Media", IndexName = "NAMESPACE_INDEX_MEDIA")]
[assembly: Namespace(Order = 21, Name = "Microsoft.UI.Xaml.Media.Animation", IndexName = "NAMESPACE_INDEX_MEDIA_ANIMATION")]
[assembly: Namespace(Order = 22, Name = "Microsoft.UI.Xaml.Input", IndexName = "NAMESPACE_INDEX_INPUT")]
[assembly: Namespace(Order = 23, Name = "Microsoft.UI.Xaml.Shapes", DXamlIdlGroup ="coretypes2", IndexName = "NAMESPACE_INDEX_SHAPES")]
[assembly: Namespace(Order = 24, Name = "Microsoft.UI.Xaml.Documents", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_DOCUMENTS")]
[assembly: Namespace(Order = 25, Name = "Microsoft.UI.Xaml.Controls", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_CONTROLS")]
[assembly: Namespace(Order = 26, Name = "Microsoft.UI.Xaml.Collections", IndexName = "NAMESPACE_INDEX_COLLECTIONS")]
[assembly: Namespace(Order = 27, Name = "Microsoft.UI.Xaml.Internal", IndexName = "NAMESPACE_INDEX_INTERNAL")]
[assembly: Namespace(Order = 28, Name = "Microsoft.UI.Xaml.Media.Imaging", IndexName = "NAMESPACE_INDEX_MEDIA_IMAGING")]
[assembly: Namespace(Order = 29, Name = "Microsoft.UI.Xaml.Controls.Primitives", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_CONTROLS_PRIMITIVES")]
[assembly: Namespace(Order = 30, Name = "Microsoft.UI.Xaml.Automation", IndexName = "NAMESPACE_INDEX_AUTOMATION")]
[assembly: Namespace(Order = 31, Name = "Microsoft.UI.Xaml.Automation.Peers", IndexName = "NAMESPACE_INDEX_AUTOMATION_PEERS")]
[assembly: Namespace(Order = 32, Name = "Microsoft.UI.Xaml.Automation.Provider", IndexName = "NAMESPACE_INDEX_AUTOMATION_PROVIDER")]
[assembly: Namespace(Order = 33, Name = "Microsoft.UI.Xaml.Automation.Text", IndexName = "NAMESPACE_INDEX_AUTOMATION_TEXT", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 34, Name = "Microsoft.UI.Xaml.Data", IndexName = "NAMESPACE_INDEX_DATA")]
[assembly: Namespace(Order = 35, Name = "Microsoft.UI.Xaml.Media.Media3D", IndexName = "NAMESPACE_INDEX_MEDIA3D")]
[assembly: Namespace(Order = 36, Name = "Microsoft.UI.Xaml.Markup", IndexName = "NAMESPACE_INDEX_MARKUP")]
[assembly: Namespace(Order = 37, Name = "Windows.Graphics.Printing", IndexName = "NAMESPACE_INDEX_WINDOWS_GRAPHICS_PRINTING")]
[assembly: Namespace(Order = 38, Name = "Microsoft.UI.Xaml.Printing", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_PRINTING")]
[assembly: Namespace(Order = 39, Name = "MS.Internal.Automation", IndexName = "NAMESPACE_INDEX_INTERNAL_AUTOMATION")]
[assembly: Namespace(Order = 40, Name = "Microsoft.UI.Xaml.Navigation", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_NAVIGATION")]
[assembly: Namespace(Order = 41, Name = "Microsoft.UI.Xaml.Interop", IndexName = "NAMESPACE_INDEX_INTEROP")]
[assembly: Namespace(Order = 42, Name = "Microsoft.UI.Xaml.Hosting", IndexName = "NAMESPACE_INDEX_HOSTING", IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 43, Name = "Windows.Media.Core", IndexName = "NAMESPACE_INDEX_WINDOWS_MEDIA_CORE")]
[assembly: Namespace(Order = 44, Name = "Windows.ApplicationModel.Search", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL_SEARCH")]
[assembly: Namespace(Order = 45, Name = "Windows.Storage", IndexName = "NAMESPACE_INDEX_WINDOWS_STORAGE", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 46, Name = "Windows.UI.ViewManagement", IndexName = "NAMESPACE_INDEX_WINDOWS_UI_VIEWMANAGEMENT", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 48, Name = "Windows.Devices.Geolocation", IndexName = "NAMESPACE_INDEX_WINDOWS_DEVICES_GEOLOCATION", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 50, Name = "Windows.ApplicationModel.Background", IndexName = "NAMESPACE_INDEX_WINDOWS_APPLICATIONMODEL_BACKGROUND", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 51, Name = "Microsoft.UI.Xaml.Controls.Maps", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_CONTROLS_MAPS", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 52, Name = "Windows.Globalization", IndexName = "NAMESPACE_INDEX_GLOBALIZATION")]
[assembly: Namespace(Order = 53, Name = "Windows.Devices.Casting", IndexName = "NAMESPACE_INDEX_DEVICES_CASTING")]
[assembly: Namespace(Order = 54, Name = "Windows.Media.Playback")]
[assembly: Namespace(Order = 55, Name = "Microsoft.UI.Composition")]
[assembly: Namespace(Order = 56, Name = "Microsoft.UI.Xaml.Controls.Inking", DXamlIdlGroup = "Controls", IndexName = "NAMESPACE_INDEX_CONTROLS_INKING", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 57, Name = "Windows.Foundation.Metadata", IsExcludedFromDXamlTypeTable = true, IsExcludedFromTypeTable = true)]
[assembly: Namespace(Order = 59, Name = "Windows.Foundation.Numerics", IndexName = "NAMESPACE_INDEX_WINDOWS_FOUNDATION_NUMERICS")]
[assembly: Namespace(Order = 60, Name = "Microsoft.UI.Xaml.Core", IndexName = "NAMESPACE_INDEX_CORE")]
[assembly: Namespace(Order = 61, Name = "Microsoft.UI.Xaml.Core.Direct", IndexName = "NAMESPACE_INDEX_CORE_DIRECT")]
[assembly: Namespace(Order = 62, Name = "Microsoft.UI", IndexName = "NAMESPACE_INDEX_MICROSOFT_UI")]
[assembly: Namespace(Order = 63, Name = "Microsoft.UI.Text", IndexName = "NAMESPACE_INDEX_MICROSOFT_UI_TEXT")]
[assembly: Namespace(Order = 64, Name = "Microsoft.UI.Dispatching", IndexName = "NAMESPACE_INDEX_MICROSOFT_SYSTEM")]
[assembly: Namespace(Order = 65, Name = "Windows.UI.Xaml.Interop", IndexName = "NAMESPACE_INDEX_WINDOWS_INTEROP")]
[assembly: Namespace(Order = 66, Name = "Microsoft.UI.Input.Experimental")]
[assembly: Namespace(Order = 67, Name = "Microsoft.UI.Windowing")]
