<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- This needs to be imported from Directory.Build.props, as the file contains reassignment of
  MSBuildProjectExtensionsPath, which in SDK projects needs to happen before it's used. -->
  <Import Project="..\..\build\Paths.props"/>
</Project>
