// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace BindPhasingTestBedCppWinRT
{
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
    }
}
