namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass PersonPicture : Windows.UI.Xaml.Controls.Control
{
    PersonPicture();

    Int32 BadgeNumber { get; set; };
    String BadgeGlyph { get; set; };
    Windows.UI.Xaml.Media.ImageSource BadgeImageSource { get; set; };
    String BadgeText { get; set; };
    Boolean IsGroup { get; set; };
    Windows.ApplicationModel.Contacts.Contact Contact { get; set; };
    String DisplayName { get; set; };
    String Initials { get; set; };
    Boolean PreferSmallImage { get; set; };
    Windows.UI.Xaml.Media.ImageSource ProfilePicture { get; set; };

    [MUX_PROPERTY_NEEDS_DP_FIELD]
    PersonPictureTemplateSettings TemplateSettings { get; };

    static Windows.UI.Xaml.DependencyProperty BadgeNumberProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BadgeGlyphProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BadgeImageSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BadgeTextProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsGroupProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ContactProperty { get; };
    static Windows.UI.Xaml.DependencyProperty DisplayNameProperty { get; };
    static Windows.UI.Xaml.DependencyProperty InitialsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty PreferSmallImageProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ProfilePictureProperty { get; };
}

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_NEEDS_DP_FIELD]
runtimeclass PersonPictureTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    String ActualInitials { get; };
    Windows.UI.Xaml.Media.ImageBrush ActualImageBrush { get; };
}

}