namespace MU_XC_NAMESPACE
{
    [MUX_PREVIEW]
    delegate void DoInkPresenterWork(Windows.UI.Input.Inking.InkPresenter presenter);


    [MUX_PREVIEW]
    unsealed runtimeclass InkCanvas : Microsoft.UI.Xaml.FrameworkElement
    {
        InkCanvas();

        [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
        [MUX_DEFAULT_VALUE("true")]
        Boolean IsEnabled{ get; set; };

        Windows.Foundation.IAsyncAction QueueInkPresenterWorkItem(DoInkPresenterWork workItem);

        static Microsoft.UI.Xaml.DependencyProperty IsEnabledProperty{ get; };
    };
}


