// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace EventHandling_968976
{
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
    }
}
