// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XamlGen.Templates.Code.Core.Bodies
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using OM;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class UIElement : CppCodeGenerator<OMContextView>
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(this.ToStringHelper.ToStringWithCulture(IncludeTemplate<Copyright>()));
            this.Write(@"

#include ""precomp.h""

//------------------------------------------------------------------------
//
//  Const array:   CUIElement::Delegates
//
//  Synopsis:
//      Static array of frequently used control delegates.
//
//------------------------------------------------------------------------
const INTERNAL_EVENT_HANDLER CUIElement::Delegates[static_cast<XUINT32>(LastControlEvent)] =
{
");
 foreach (var ev in Model.GetAllControlEvents()) { 
            this.Write("    ");
            this.Write(this.ToStringHelper.ToStringWithCulture(ev.ControlEventNamePointer));
            this.Write(",\r\n");
 } 
            this.Write("};\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
}
