/* MenuBarAutomationPeer Content */
[WUXC_VERSION_RS5]
[webhosthidden]
unsealed runtimeclass MenuBarAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    MenuBarAutomationPeer(MU_XC_NAMESPACE.MenuBar owner);
}

/* MenuBarItemAutomationPeer Content */
[WUXC_VERSION_RS5]
[webhosthidden]
unsealed runtimeclass MenuBarItemAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer,
Windows.UI.Xaml.Automation.Provider.IExpandCollapseProvider,
Windows.UI.Xaml.Automation.Provider.IInvokeProvider
{
    MenuBarItemAutomationPeer(MU_XC_NAMESPACE.MenuBarItem owner);
}