namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass MenuBarItemFlyout : Windows.UI.Xaml.Controls.MenuFlyout
{
    MenuBarItemFlyout();
}

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("Items")]
unsealed runtimeclass MenuBarItem : Windows.UI.Xaml.Controls.Control
{
    MenuBarItem();

    String Title { get; set; };
    Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Controls.MenuFlyoutItemBase> Items { get; };

    static Windows.UI.Xaml.DependencyProperty TitleProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ItemsProperty { get; };
}

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("Items")]
unsealed runtimeclass MenuBar : Windows.UI.Xaml.Controls.Control
{
    MenuBar();

    Windows.Foundation.Collections.IVector<MenuBarItem> Items { get; };

    static Windows.UI.Xaml.DependencyProperty ItemsProperty { get; };
}

}