[WUXC_VERSION_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass TeachingTipTestHooks
{
    static void SetExpandEasingFunction(MU_XC_NAMESPACE.TeachingTip teachingTip, Windows.UI.Composition.CompositionEasingFunction easingFunction);
    static void SetContractEasingFunction(MU_XC_NAMESPACE.TeachingTip teachingTip, Windows.UI.Composition.CompositionEasingFunction easingFunction);
    static void SetTipShadow(MU_XC_NAMESPACE.TeachingTip teachingTip, Boolean tipShadow);
    static void SetContentElevation(MU_XC_NAMESPACE.TeachingTip teachingTip, Single elevation);
    static void SetBeakElevation(MU_XC_NAMESPACE.TeachingTip teachingTip, Single elevation);
    static void SetUseTestWindowBounds(MU_XC_NAMESPACE.TeachingTip teachingTip, Boolean useTestWindowBounds);
    static void SetTestWindowBounds(MU_XC_NAMESPACE.TeachingTip teachingTip, Windows.Foundation.Rect testWindowBounds);
    static void SetTipFollowsTarget(MU_XC_NAMESPACE.TeachingTip teachingTip, Boolean tipFollowsTarget);
    static void SetExpandAnimationDuration(MU_XC_NAMESPACE.TeachingTip teachingTip, Windows.Foundation.TimeSpan animationDurationMultiplier);
    static void SetContractAnimationDuration(MU_XC_NAMESPACE.TeachingTip teachingTip, Windows.Foundation.TimeSpan animationDurationMultiplier);

    static Boolean GetIsIdle(MU_XC_NAMESPACE.TeachingTip teachingTip);
    static MU_XC_NAMESPACE.TeachingTipPlacementMode GetEffectivePlacement(MU_XC_NAMESPACE.TeachingTip teachingTip);
    static MU_XC_NAMESPACE.TeachingTipBleedingImagePlacementMode GetEffectiveBleedingPlacement(MU_XC_NAMESPACE.TeachingTip teachingTip);
    static Double GetVerticalOffset(MU_XC_NAMESPACE.TeachingTip teachingTip);
    static Double GetHorizontalOffset(MU_XC_NAMESPACE.TeachingTip teachingTip);

    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.TeachingTip, Object> OpenedStatusChanged;
    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.TeachingTip, Object> IdleStatusChanged;
    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.TeachingTip, Object> OffsetChanged;
    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.TeachingTip, Object> EffectivePlacementChanged;
    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.TeachingTip, Object> EffectiveBleedingPlacementChanged;
}
