namespace MU_PRIVATE_MEDIA_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
runtimeclass AcrylicTestApi : Windows.UI.Xaml.DependencyObject
{
    AcrylicTestApi();

    MU_XM_NAMESPACE.AcrylicBrush AcrylicBrush { get; set; };
    Boolean IsUsingAcrylicBrush { get; };
    Windows.UI.Composition.CompositionBrush CompositionBrush { get; };
    Windows.UI.Composition.CompositionBrush NoiseBrush { get; };
    void ForceCreateAcrylicBrush(Boolean useCrossFadeEffect);

}

[MUX_INTERNAL]
[webhosthidden]
interface IAcrylicBrushStaticsPrivate
{
    Windows.UI.Composition.CompositionEffectBrush CreateBackdropAcrylicEffectBrush(Windows.UI.Composition.Compositor compositor, Windows.UI.Color initialTintColor, Windows.UI.Color initialFallbackColor, Boolean willTintColorAlwaysBeOpaque);
    Windows.UI.Composition.CompositionEffectBrush CreateBackdropAcrylicEffectBrushWithLuminosity(Windows.UI.Composition.Compositor compositor, Windows.UI.Color initialTintColor, Windows.UI.Color initialLuminosityColor, Windows.UI.Color initialFallbackColor, Boolean willTintColorAlwaysBeOpaque);
}

}
