namespace MU_XM_NAMESPACE
{

[WUXC_VERSION_RS3]
[webhosthidden]
enum AcrylicBackgroundSource
{
    HostBackdrop = 0,
    Backdrop = 1,
};

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("IAcrylicBrush", 79bbcf4e-cd66-4f1b-a8b6-cd6d2977c18d)]
[WUXC_STATIC_NAME("IAcrylicBrushStatics", 2787fd79-a3da-423f-b81a-599147971523)]
[WUXC_CONSTRUCTOR_NAME("IAcrylicBrushFactory", 81a32568-f6cc-4013-8363-928ae23b7a61)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
[MUX_HAS_CUSTOM_FACTORY]
unsealed runtimeclass AcrylicBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    AcrylicBrush();

    [MUX_DEFAULT_VALUE("winrt::AcrylicBackgroundSource::Backdrop")]
    AcrylicBackgroundSource BackgroundSource { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintColor")]
    Windows.UI.Color TintColor { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintOpacity")]
    [MUX_PROPERTY_VALIDATION_CALLBACK("CoerceToZeroOneRange")]
    Double TintOpacity { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintTransitionDuration")]
    Windows.Foundation.TimeSpan TintTransitionDuration { get; set; };

    Boolean AlwaysUseFallback { get; set; };

    [WUXC_VERSION_19H1]
    {
        [MUX_PROPERTY_VALIDATION_CALLBACK("CoerceToZeroOneRange_Nullable")]
        Windows.Foundation.IReference<Double> TintLuminosityOpacity{ get; set; };
    }

    static Windows.UI.Xaml.DependencyProperty BackgroundSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintColorProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintOpacityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintTransitionDurationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty AlwaysUseFallbackProperty { get; };

    [WUXC_VERSION_19H1]
    {
        static Windows.UI.Xaml.DependencyProperty TintLuminosityOpacityProperty { get; };
    }
}

}