namespace MU_XM_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
enum AcrylicBackgroundSource
{
    HostBackdrop = 0,
    Backdrop = 1,
};

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
[MUX_HAS_CUSTOM_FACTORY]
unsealed runtimeclass AcrylicBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
{
    AcrylicBrush();

    [MUX_DEFAULT_VALUE("winrt::AcrylicBackgroundSource::Backdrop")]
    AcrylicBackgroundSource BackgroundSource { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintColor")]
    Windows.UI.Color TintColor { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintOpacity")]
    [MUX_PROPERTY_VALIDATION_CALLBACK("CoerceToZeroOneRange")]
    Double TintOpacity { get; set; };

    [MUX_DEFAULT_VALUE("AcrylicBrush::sc_defaultTintTransitionDuration")]
    Windows.Foundation.TimeSpan TintTransitionDuration { get; set; };

    Boolean AlwaysUseFallback { get; set; };

    [MUX_PUBLIC]
    {
        [MUX_PROPERTY_VALIDATION_CALLBACK("CoerceToZeroOneRange_Nullable")]
        Windows.Foundation.IReference<Double> TintLuminosityOpacity{ get; set; };
    }

    static Windows.UI.Xaml.DependencyProperty BackgroundSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintColorProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintOpacityProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TintTransitionDurationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty AlwaysUseFallbackProperty { get; };

    [MUX_PUBLIC]
    {
        static Windows.UI.Xaml.DependencyProperty TintLuminosityOpacityProperty { get; };
    }
}

}
