namespace MU_XAP_NAMESPACE
{
    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
    {
        InkToolBarAutomationPeer(MU_XC_NAMESPACE.InkToolBar owner);
    }

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarToolButtonAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.RadioButtonAutomationPeer
    {
        InkToolBarToolButtonAutomationPeer(MU_XC_NAMESPACE.InkToolBarToolButton owner);
    }

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarMenuButtonAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.ToggleButtonAutomationPeer
    {
        InkToolBarMenuButtonAutomationPeer(MU_XC_NAMESPACE.InkToolBarMenuButton owner);
    }

    [MUX_PREVIEW]
    [default_interface]
    unsealed runtimeclass InkToolBarFlyoutItemAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.ButtonBaseAutomationPeer
    {
        InkToolBarFlyoutItemAutomationPeer(MU_XC_NAMESPACE.InkToolBarFlyoutItem owner);
    }
}

