namespace MU_XC_NAMESPACE
{
    [MUX_PREVIEW]
    enum InkToolBarButtonFlyoutPlacement
    {
        Auto,
        Top,
        Bottom,
        Left,
        Right,
    };

    [MUX_PREVIEW]
    enum InkToolBarEraserFlyoutItemKind
    {
        StrokeEraser,
        PrecisionSmallEraser,
        PrecisionLargeEraser,
        ClearAll,
    };

    [MUX_PREVIEW]
    enum InkToolBarEraserKind
    {
        Stroke,
        PrecisionSmall,
        PrecisionLarge,
    };

    [MUX_PREVIEW]
    enum InkToolBarFlyoutItemKind
    {
        Simple,
        Radio,
        Check,
        RadioCheck,
    };

    [MUX_PREVIEW]
    enum InkToolBarInitialControls
    {
        All,
        None,
        PensOnly,
        AllExceptPens,
    };

    [MUX_PREVIEW]
    enum InkToolBarMenuKind
    {
        Stencil,
    };

    [MUX_PREVIEW]
    enum InkToolBarStencilKind
    {
        Ruler,
        Protractor,
    };

    [MUX_PREVIEW]
    enum InkToolBarToggle
    {
        Ruler,
        Custom,
    };

    [MUX_PREVIEW]
    enum InkToolBarTool
    {
        BallpointPen,
        Pencil,
        Highlighter,
        Eraser,
        CustomPen,
        CustomTool,
    };


    [MUX_PREVIEW]
    runtimeclass InkToolBarEraserFlyoutItemClickedEventArgs
    {
        Microsoft.UI.Xaml.Controls.InkToolBarEraserFlyoutItemKind EraserFlyoutItemKind{ get; };
        Boolean Handled{ set; get; };
    };

    [MUX_PREVIEW]
    runtimeclass InkToolBarIsStencilButtonCheckedChangedEventArgs
    {
        Microsoft.UI.Xaml.Controls.InkToolBarStencilButton StencilButton{ get; };
        Microsoft.UI.Xaml.Controls.InkToolBarStencilKind StencilKind{ get; };
    };

    [MUX_PREVIEW]
    [constructor_name("Microsoft.UI.Xaml.Controls.IInkToolBarCustomPenFactory")]
    unsealed runtimeclass InkToolBarCustomPen
        : Microsoft.UI.Xaml.DependencyObject
    {
        [method_name("CreateInstance")] protected InkToolBarCustomPen();
        Windows.UI.Input.Inking.InkDrawingAttributes CreateInkDrawingAttributes(Microsoft.UI.Xaml.Media.Brush brush, Double strokeWidth);
        overridable Windows.UI.Input.Inking.InkDrawingAttributes CreateInkDrawingAttributesCore(Microsoft.UI.Xaml.Media.Brush brush, Double strokeWidth);
    };

    [MUX_PREVIEW]
    [contentproperty("Children")]
    unsealed runtimeclass InkToolBar
        : Microsoft.UI.Xaml.Controls.Control
    {
        [method_name("CreateInstance")] InkToolBar();
        Microsoft.UI.Xaml.Controls.InkToolBarInitialControls InitialControls;
        Microsoft.UI.Xaml.DependencyObjectCollection Children{ get; };
        Microsoft.UI.Xaml.Controls.InkToolBarToolButton ActiveTool;
        Windows.UI.Input.Inking.InkDrawingAttributes InkDrawingAttributes{ get; };
        Boolean IsRulerButtonChecked;
        Microsoft.UI.Xaml.Controls.InkCanvas TargetInkCanvas;
        Boolean IsStencilButtonChecked;
        Microsoft.UI.Xaml.Controls.InkToolBarButtonFlyoutPlacement ButtonFlyoutPlacement;
        Microsoft.UI.Xaml.Controls.Orientation Orientation;
        Object TargetInkPresenter;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBar,Object> ActiveToolChanged;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBar,Object> InkDrawingAttributesChanged;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBar,Object> EraseAllClicked;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBarEraserFlyoutItemClickedEventArgs,Object> EraserFlyoutItemClicked;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBar,Microsoft.UI.Xaml.Controls.InkToolBarIsStencilButtonCheckedChangedEventArgs> IsStencilButtonCheckedChanged;
        Microsoft.UI.Xaml.Controls.InkToolBarToolButton GetToolButton(Microsoft.UI.Xaml.Controls.InkToolBarTool tool);
        Microsoft.UI.Xaml.Controls.InkToolBarToggleButton GetToggleButton(Microsoft.UI.Xaml.Controls.InkToolBarToggle tool);
        Microsoft.UI.Xaml.Controls.InkToolBarMenuButton GetMenuButton(Microsoft.UI.Xaml.Controls.InkToolBarMenuKind menu);
        static Microsoft.UI.Xaml.DependencyProperty InitialControlsProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ChildrenProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ActiveToolProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty InkDrawingAttributesProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsRulerButtonCheckedProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty TargetInkCanvasProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsStencilButtonCheckedProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ButtonFlyoutPlacementProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty OrientationProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty TargetInkPresenterProperty{ get; };
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarPenConfigurationControl
        : Microsoft.UI.Xaml.Controls.Control
    {
        [method_name("CreateInstance")] InkToolBarPenConfigurationControl();
        Microsoft.UI.Xaml.Controls.InkToolBarPenButton PenButton{ get; };
        static Microsoft.UI.Xaml.DependencyProperty PenButtonProperty{ get; };
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarFlyoutItem
        : Microsoft.UI.Xaml.Controls.Primitives.ButtonBase
    {
        [method_name("CreateInstance")] InkToolBarFlyoutItem();
        Microsoft.UI.Xaml.Controls.InkToolBarFlyoutItemKind Kind;
        Boolean IsChecked;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBarFlyoutItem,Object> Checked;
        event Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.InkToolBarFlyoutItem,Object> Unchecked;
        static Microsoft.UI.Xaml.DependencyProperty KindProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsCheckedProperty{ get; };
    };

    [MUX_PREVIEW]
    [constructor_name("Microsoft.UI.Xaml.Controls.IInkToolBarMenuButtonFactory")]
    unsealed runtimeclass InkToolBarMenuButton
        : Microsoft.UI.Xaml.Controls.Primitives.ToggleButton
    {
        Microsoft.UI.Xaml.Controls.InkToolBarMenuKind MenuKind{ get; };
        Boolean IsExtensionGlyphShown;
        static Microsoft.UI.Xaml.DependencyProperty IsExtensionGlyphShownProperty{ get; };
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarStencilButton
        : Microsoft.UI.Xaml.Controls.InkToolBarMenuButton
    {
        [method_name("CreateInstance")] InkToolBarStencilButton();
        Windows.UI.Input.Inking.InkPresenterRuler Ruler{ get; };
        Windows.UI.Input.Inking.InkPresenterProtractor Protractor{ get; };
        Microsoft.UI.Xaml.Controls.InkToolBarStencilKind SelectedStencil;
        Boolean IsRulerItemVisible;
        Boolean IsProtractorItemVisible;
        static Microsoft.UI.Xaml.DependencyProperty RulerProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ProtractorProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty SelectedStencilProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsRulerItemVisibleProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsProtractorItemVisibleProperty{ get; };
    };

    [MUX_PREVIEW]
    [constructor_name("Microsoft.UI.Xaml.Controls.IInkToolBarToggleButtonFactory")]
    unsealed runtimeclass InkToolBarToggleButton
        : Microsoft.UI.Xaml.Controls.CheckBox
    {
        Microsoft.UI.Xaml.Controls.InkToolBarToggle ToggleKind{ get; };
    };

    [MUX_PREVIEW]
    [constructor_name("Microsoft.UI.Xaml.Controls.IInkToolBarToolButtonFactory")]
    unsealed runtimeclass InkToolBarToolButton
        : Microsoft.UI.Xaml.Controls.RadioButton
    {
        Microsoft.UI.Xaml.Controls.InkToolBarTool ToolKind{ get; };
        Boolean IsExtensionGlyphShown;
        static Microsoft.UI.Xaml.DependencyProperty IsExtensionGlyphShownProperty{ get; };
        Microsoft.UI.Xaml.Controls.InkToolBarToggle ToggleKind{ get; };
    };

    [MUX_PREVIEW]
    [default_interface]
    unsealed runtimeclass InkToolBarCustomToggleButton
        : Microsoft.UI.Xaml.Controls.InkToolBarToggleButton
    {
        [method_name("CreateInstance")] InkToolBarCustomToggleButton();
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarCustomToolButton
        : Microsoft.UI.Xaml.Controls.InkToolBarToolButton
    {
        [method_name("CreateInstance")] InkToolBarCustomToolButton();
        Microsoft.UI.Xaml.UIElement ConfigurationContent;
        static Microsoft.UI.Xaml.DependencyProperty ConfigurationContentProperty{ get; };
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarEraserButton
        : Microsoft.UI.Xaml.Controls.InkToolBarToolButton
    {
        Microsoft.UI.Xaml.Controls.InkToolBarEraserKind SelectedEraser;
        Boolean IsClearAllVisible;
        Boolean IsStrokeEraserVisible;
        Boolean ArePrecisionErasersVisible;
        static Microsoft.UI.Xaml.DependencyProperty IsClearAllVisibleProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty SelectedEraserProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty IsStrokeEraserVisibleProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ArePrecisionErasersVisibleProperty{ get; };
     };

    [MUX_PREVIEW]
    [constructor_name("Microsoft.UI.Xaml.Controls.IInkToolBarPenButtonFactory")]
    unsealed runtimeclass InkToolBarPenButton
        : Microsoft.UI.Xaml.Controls.InkToolBarToolButton
    {
        Windows.Foundation.Collections.IVector<Microsoft.UI.Xaml.Media.Brush> Palette;
        Double MinStrokeWidth;
        Double MaxStrokeWidth;
        Microsoft.UI.Xaml.Media.Brush SelectedBrush{ get; };
        Int32 SelectedBrushIndex;
        Double SelectedStrokeWidth;
        static Microsoft.UI.Xaml.DependencyProperty PaletteProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty MinStrokeWidthProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty MaxStrokeWidthProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty SelectedBrushProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty SelectedBrushIndexProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty SelectedStrokeWidthProperty{ get; };
    };

    [MUX_PREVIEW]
    [default_interface]
    unsealed runtimeclass InkToolBarBallpointPenButton
        : Microsoft.UI.Xaml.Controls.InkToolBarPenButton
    {
        [method_name("CreateInstance")] InkToolBarBallpointPenButton();
    };

    [MUX_PREVIEW]
    unsealed runtimeclass InkToolBarCustomPenButton
        : Microsoft.UI.Xaml.Controls.InkToolBarPenButton
    {
        [method_name("CreateInstance")] InkToolBarCustomPenButton();
        Microsoft.UI.Xaml.Controls.InkToolBarCustomPen CustomPen;
        Microsoft.UI.Xaml.UIElement ConfigurationContent;
        static Microsoft.UI.Xaml.DependencyProperty CustomPenProperty{ get; };
        static Microsoft.UI.Xaml.DependencyProperty ConfigurationContentProperty{ get; };
    };

    [MUX_PREVIEW]
    [default_interface]
    unsealed runtimeclass InkToolBarHighlighterButton
        : Microsoft.UI.Xaml.Controls.InkToolBarPenButton
    {
        [method_name("CreateInstance")] InkToolBarHighlighterButton();
    };

    [MUX_PREVIEW]
    [default_interface]
    unsealed runtimeclass InkToolBarPencilButton
        : Microsoft.UI.Xaml.Controls.InkToolBarPenButton
    {
        [method_name("CreateInstance")] InkToolBarPencilButton();
    };

}


