#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBlock;
            }
        }
    }
}

namespace Simple
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class FieldModifierTests : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class FieldModifierTests_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Private1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Private2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Private3;
        internal: ::Windows::UI::Xaml::Controls::TextBlock^ Internal1;
        internal: ::Windows::UI::Xaml::Controls::TextBlock^ Internal2;
        internal: ::Windows::UI::Xaml::Controls::TextBlock^ Internal3;
    };
}

