// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace NonStandardCppWinRT
{
    [Windows.Foundation.Metadata.WebHostHidden]
    runtimeclass BlankPage : Microsoft.UI.Xaml.Controls.Page
    {
        BlankPage();
    }
}
