namespace MU_XC_NAMESPACE
{

runtimeclass StackLayout;

[MUX_PREVIEW]
[webhosthidden]
[default_interface]
runtimeclass BreadcrumbItemClickedEventArgs
{
    Object Item { get; };
}

[MUX_PREVIEW]
[webhosthidden]
unsealed runtimeclass BreadcrumbItem : Windows.UI.Xaml.Controls.ContentControl
{
    BreadcrumbItem();
}

[MUX_PREVIEW]
[webhosthidden]
unsealed runtimeclass BreadcrumbLayout : NonVirtualizingLayout
{
    BreadcrumbLayout();
}

[MUX_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass Breadcrumb : Windows.UI.Xaml.Controls.Control
{
    Breadcrumb();

    Object DropdownItemTemplate{ get; set; };
    Object ItemsSource{ get; set; };
    Object ItemTemplate{ get; set; };

    event Windows.Foundation.TypedEventHandler<Breadcrumb, BreadcrumbItemClickedEventArgs> ItemClicked;

    static Windows.UI.Xaml.DependencyProperty DropdownItemTemplateProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemsSourceProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ItemTemplateProperty{ get; };
}

}
