namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum PipsPagerButtonVisibility
{
    Visible, // arrows ALWAYS visible 
    VisibleOnHover,
    Collapsed
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
runtimeclass PipsPagerSelectedIndexChangedEventArgs
{
    Int32 NewPageIndex{get; };
    Int32 PreviousPageIndex{get; };
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_NEEDS_DP_FIELD]
unsealed runtimeclass PipsPagerTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    PipsPagerTemplateSettings();
    Windows.Foundation.Collections.IVector<Object> VerticalPipsItems { get; };
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass PipsPager : Windows.UI.Xaml.Controls.Control
{
    PipsPager();

    [MUX_DEFAULT_VALUE("0")]
    Int32 NumberOfPages;

    [MUX_DEFAULT_VALUE("0")]
    Int32 SelectedPageIndex;

    [MUX_DEFAULT_VALUE("5")]
    Int32 MaxDisplayedPages;

    [MUX_DEFAULT_VALUE("winrt::Orientation::Vertical")]
    Windows.UI.Xaml.Controls.Orientation Orientation;

    [MUX_DEFAULT_VALUE("winrt::PipsPagerButtonVisibility::VisibleOnHover")]
    PipsPagerButtonVisibility PreviousButtonVisibility;
    [MUX_DEFAULT_VALUE("winrt::PipsPagerButtonVisibility::VisibleOnHover")]
    PipsPagerButtonVisibility NextButtonVisibility;

    Windows.UI.Xaml.Style PreviousButtonStyle;
    Windows.UI.Xaml.Style NextButtonStyle;

    Windows.UI.Xaml.Style SelectedIndicatorStyle;
    Windows.UI.Xaml.Style DefaultIndicatorStyle;

    event Windows.Foundation.TypedEventHandler<PipsPager, PipsPagerSelectedIndexChangedEventArgs> SelectedIndexChanged;

    [MUX_PROPERTY_NEEDS_DP_FIELD]
    PipsPagerTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty NumberOfPagesProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SelectedPageIndexProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MaxDisplayedPagesProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty OrientationProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty PreviousButtonVisibilityProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty NextButtonVisibilityProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty PreviousButtonStyleProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty NextButtonStyleProperty{ get; };

    static Windows.UI.Xaml.DependencyProperty SelectedIndicatorStyleProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty DefaultIndicatorStyleProperty{ get; };
};

}
