namespace MU_XAP_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass PipsPagerAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    PipsPagerAutomationPeer(MU_XC_NAMESPACE.PipsPager owner);
}

}

