namespace MU_XAP_NAMESPACE
{

[MUX_PREVIEW]
[webhosthidden]
unsealed runtimeclass PipsPagerAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    PipsPagerAutomationPeer(MU_XC_NAMESPACE.PipsPager owner);
}

}

