namespace RuntimeComponentThatUsesMUX
{
    [default_interface]
    runtimeclass MUXCInterfaceImplementation : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        MUXCInterfaceImplementation();

        Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Windows.UI.Composition.Compositor compositor, out Object diagnostics);
    }
}
