namespace RuntimeComponentThatUsesMUX
{
    [default_interface]
    runtimeclass MUXCInterfaceImplementation : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
    {
        MUXCInterfaceImplementation();
    }
}
