namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass LayoutPanel : Windows.UI.Xaml.Controls.Panel
{
    LayoutPanel();

    Layout Layout{ get; set; };
    static Windows.UI.Xaml.DependencyProperty LayoutProperty{ get; };

    Windows.UI.Xaml.Media.Brush BorderBrush{ get; set; };
    static Windows.UI.Xaml.DependencyProperty BorderBrushProperty{ get; };

    Windows.UI.Xaml.Thickness BorderThickness{ get; set; };
    static Windows.UI.Xaml.DependencyProperty BorderThicknessProperty{ get; };

    Windows.UI.Xaml.Thickness Padding{ get; set; };
    static Windows.UI.Xaml.DependencyProperty PaddingProperty{ get; };

    Windows.UI.Xaml.CornerRadius CornerRadius{ get; set; };
    static Windows.UI.Xaml.DependencyProperty CornerRadiusProperty{ get; };
}

}
