<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(DotNetCoreTargetFrameworkMoniker)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsAppSdkTargetPlatformVersion)</TargetPlatformMinVersion>
    <RootNamespace>WinUIDesktopTemplateCS</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <DefineConstants>DESKTOP;USING_CSWINRT</DefineConstants>
  </PropertyGroup>   
  <ItemGroup>
    <!--TODO: Convert BindTestbedModelCX to C++/WinRT-->
    <!-- A reference to the entire .Net Framework and Windows SDK are automatically included -->
    <!-- <ProjectReference Include="..\BindTestbedCXModel\BindTestbedCXModel.vcxproj">
      <Project>{6eb67720-b6ed-486b-9bed-98a4c3696cec}</Project>
      <Name>BindTestbedCXModel</Name>
    </ProjectReference> -->
    <ProjectReference Include="..\BindTestbedModel\BindTestbedModelDesktop.csproj">
      <Project>{0748b16e-2455-494b-9d33-0231960ff58a}</Project>
      <Name>BindTestbedModel</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VCRTForwarders.140" Version="1.0.6" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="$(MicrosoftCsWinRTPackageVersion)"/>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets" />
</Project>
