// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace CppWinRT
{
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 CurrentYearAsInteger{ get; };
    }
}
