<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(DotNetCoreTargetFrameworkMoniker)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsAppSdkTargetPlatformVersion)</TargetPlatformMinVersion>
    <RootNamespace>LibManagedDll</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\projection\Microsoft.WinUI.csproj">
      <ReferenceOutputAssembly>True</ReferenceOutputAssembly>
      <ExcludeAssets>All</ExcludeAssets>
    </ProjectReference>
    <ProjectReference Include="..\LibManagedDllSatellite\LibManagedDllSatellite.csproj" />
    <Reference Include="$(NugetPackageDirectory)\$(LiftedIXPTransportPackageName)\$(IxpTransportPackageVersion)\lib\net6.0-windows$(CurrentLiftedIXPTargetPlatformVersion)\Microsoft.InteractiveExperiences.Projection.dll" />
  </ItemGroup>
</Project>