// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace LinkedMDControlsCppWinRT
{
    runtimeclass B : Microsoft.UI.Xaml.Controls.Page
    {
        B();
        String StringPropertyOnB{ get; };
    }
}
