namespace MU_XCP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[default_interface]
runtimeclass AutoSuggestBoxHelper
{
    [MUX_DEFAULT_VALUE("false")]
    [MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnKeepInteriorCornersSquarePropertyChanged")]
    static Windows.UI.Xaml.DependencyProperty KeepInteriorCornersSquareProperty { get; };
    static void SetKeepInteriorCornersSquare(Windows.UI.Xaml.Controls.AutoSuggestBox autoSuggestBox, Boolean value);
    static Boolean GetKeepInteriorCornersSquare(Windows.UI.Xaml.Controls.AutoSuggestBox autoSuggestBox);
};

}
