// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML types.
//      NOTE: This file was generated by a tool.
//
//------------------------------------------------------------------------

#pragma once

namespace DirectUI
{
    interface __declspec(uuid("9e02e489-8ca7-4728-94c5-09c4d68d970e")) IKeyboardHeaderNavigationPanel : public IInspectable
    {
        // Properties.

        // Events.

        // Methods.
        IFACEMETHOD(GetTargetHeaderIndexFromNavigationAction)(_In_ UINT sourceIndex, _In_ ABI::Microsoft::UI::Xaml::Controls::KeyNavigationAction action, _Out_ UINT* pComputedTargetIndex, _Out_ BOOLEAN* pActionHandled) = 0;
    };
}
