[WUXC_VERSION_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass ScrollBar2 : Windows.UI.Xaml.FrameworkElement
{
    ScrollBar2();

    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultMinOffset")]
    Double MinOffset { get; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultMaxOffset")]
    Double MaxOffset { get; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultOffset")]
    Double Offset { get; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultViewport")]
    Double Viewport { get; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultSmallChange")]
    Double SmallChange { get; set; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultLargeChange")]
    Double LargeChange { get; set; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultIndicatorMode")]
    Windows.UI.Xaml.Controls.Primitives.ScrollingIndicatorMode IndicatorMode { get; set; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultIsEnabled")]
    Boolean IsEnabled { get; set; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultOrientation")]
    Windows.UI.Xaml.Controls.Orientation Orientation { get; set; };
    Windows.UI.Xaml.Style ScrollBarStyle { get; set; };
    [MUX_DEFAULT_VALUE("ScrollBar2::s_defaultScrollMode")]
    [MUX_PROPERTY_VALIDATION_CALLBACK("ValidateScrollMode")]
    ScrollerScrollMode ScrollMode{ get; set; };

    static Windows.UI.Xaml.DependencyProperty MinOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty MaxOffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty OffsetProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ViewportProperty { get; };
    static Windows.UI.Xaml.DependencyProperty SmallChangeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty LargeChangeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IndicatorModeProperty { get; };
    static Windows.UI.Xaml.DependencyProperty IsEnabledProperty { get; };
    static Windows.UI.Xaml.DependencyProperty OrientationProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ScrollBarStyleProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ScrollModeProperty { get; };
}
