// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace CppWinRTComponent
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;
    }
}
