// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
namespace LinkedMDAppCppWinRT
{
    runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 Dummy{ get; };
    }
}
