<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.1" />
  <Import Project="$(CommonFilesPath)RuntimeComponentPreamble.csproj" />

  <PropertyGroup>
    <RootNamespace>ConditionalControls</RootNamespace>
    <AssemblyName>ConditionalControls</AssemblyName>
    <DefineConstants>$(DefineConstants);CSWINRT_1642</DefineConstants>
  </PropertyGroup>
</Project>