REM Copyright (c) Microsoft Corporation.
REM Licensed under the MIT License.

set NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS=30
set NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS=30
echo ##vso[task.setVariable variable=NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS]%NUGET_PLUGIN_HANDSHAKE_TIMEOUT_IN_SECONDS%
echo ##vso[task.setVariable variable=NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS]%NUGET_PLUGIN_REQUEST_TIMEOUT_IN_SECONDS%
