<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(CommonFilesPath)AppPreamble.csproj" />

  <ItemGroup>
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarkupExtensionsComponents\MarkupExtensionsComponents.csproj" />
  </ItemGroup>

</Project>
