namespace MU_XC_NAMESPACE
{
    [MUX_PUBLIC]
    [webhosthidden]
    [default_interface]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    unsealed runtimeclass BackdropMaterial : Windows.UI.Xaml.DependencyObject
    {
        [MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnApplyToRootOrPageBackgroundChanged")]
        static Windows.UI.Xaml.DependencyProperty ApplyToRootOrPageBackgroundProperty { get; };
        static void SetApplyToRootOrPageBackground(Windows.UI.Xaml.Controls.Control element, Boolean value);
        static Boolean GetApplyToRootOrPageBackground(Windows.UI.Xaml.Controls.Control element);
    }
}

namespace MU_PRIVATE_CONTROLS_NAMESPACE
{
    [webhosthidden]
    [default_interface]
    [MUX_INTERNAL]
    runtimeclass MicaController
    {
        MicaController();

        Boolean SetTarget(Windows.UI.Xaml.Window xamlWindow);

        Windows.UI.Color TintColor;
        Single TintOpacity;
        Single LuminosityOpacity;
        Windows.UI.Color FallbackColor;
    }

    [MUX_INTERNAL]
    [webhosthidden]
    [default_interface]
    runtimeclass BackdropMaterialState
    {

    }

    [MUX_INTERNAL]
    [webhosthidden]
    [default_interface]
    runtimeclass BackdropMaterialTestApi
    {
        static Boolean IsBackdropMaterialActive { get; };
        static Windows.UI.Color TintColor;
        static Single TintOpacity;
        static Single LuminosityOpacity;
        static Windows.UI.Color FallbackColor;
    }
}
