namespace MU_XM_NAMESPACE
{
    [MUX_PREVIEW]
    [webhosthidden]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    unsealed runtimeclass BackdropMaterialBrush : Windows.UI.Xaml.Media.XamlCompositionBrushBase
    {
        BackdropMaterialBrush();
    }
}

namespace MU_XCP_NAMESPACE
{
    [webhosthidden]
    [default_interface]
    [MUX_PREVIEW]
    runtimeclass MicaController
    {
        MicaController();

        //[default_overload]
        //Boolean SetTarget(Windows.UI.WindowId windowId, Windows.UI.Composition.CompositionTarget desktopWindowTarget);
        //Boolean SetTarget(Windows.UI.Core.CoreWindow coreWindow, Windows.UI.Composition.CompositionTarget compositionTarget);
        Boolean SetTarget(Windows.UI.Xaml.Window xamlWindow);

        //void SniffWindowMessage(UInt32 message, UInt64 wparam, Int64 lparam);

        Windows.UI.Color TintColor;
        Single TintOpacity;
        Single LuminosityOpacity;
        Windows.UI.Color FallbackColor;
    }

    [MUX_PREVIEW]
    [webhosthidden]
    [uuid("397dafe4-b6c2-5bb9-951d-f5707de8b7bc")]
    interface ICompositionSupportsSystemBackdropLatest
    {
        Windows.UI.Composition.CompositionBrush SystemBackdrop;
    };
}
