namespace MU_XC_NAMESPACE
{

[WUXC_VERSION_RS5]
[webhosthidden]
[contentproperty("PrimaryCommands")]
unsealed runtimeclass CommandBarFlyout : Windows.UI.Xaml.Controls.Primitives.FlyoutBase
{
    CommandBarFlyout();

    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> PrimaryCommands { get; };
    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> SecondaryCommands { get; };
};

[WUXC_VERSION_RS5]
[webhosthidden]
unsealed runtimeclass TextCommandBarFlyout : CommandBarFlyout
{
    TextCommandBarFlyout();
};

}