namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("PrimaryCommands")]
unsealed runtimeclass CommandBarFlyout : Windows.UI.Xaml.Controls.Primitives.FlyoutBase
{
    CommandBarFlyout();

    [MUX_PREVIEW]
    {
        Boolean AlwaysExpanded{ get; set; };
    }

    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> PrimaryCommands { get; };
    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> SecondaryCommands { get; };
};

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass TextCommandBarFlyout : CommandBarFlyout
{
    TextCommandBarFlyout();
};

}
