namespace MU_XC_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[contentproperty("PrimaryCommands")]
unsealed runtimeclass CommandBarFlyout : Windows.UI.Xaml.Controls.Primitives.FlyoutBase
{
    CommandBarFlyout();

    [MUX_PREVIEW]
    {
        Boolean AlwaysExpanded{ get; set; };
    }

    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> PrimaryCommands { get; };
    Windows.Foundation.Collections.IObservableVector<Windows.UI.Xaml.Controls.ICommandBarElement> SecondaryCommands { get; };
};

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass TextCommandBarFlyout : CommandBarFlyout
{
    TextCommandBarFlyout();
};

}

namespace MU_XCP_NAMESPACE
{
    // Needed so we can access this enum and interface until they ship in the official SDK.
    [MUX_INTERNAL]
    [webhosthidden]
    enum PopupPlacementMode
    {
        Auto,
        Top,
        Bottom,
        Left,
        Right,
        TopEdgeAlignedLeft,
        TopEdgeAlignedRight,
        BottomEdgeAlignedLeft,
        BottomEdgeAlignedRight,
        LeftEdgeAlignedTop,
        LeftEdgeAlignedBottom,
        RightEdgeAlignedTop,
        RightEdgeAlignedBottom,
    };

    [MUX_INTERNAL]
    [webhosthidden]
    [uuid(0909bd79-eda7-57a4-82d8-9a47fc950a1d)]
    interface IPopup4
    {
        Windows.UI.Xaml.FrameworkElement PlacementTarget;
        Microsoft.UI.Xaml.Controls.Primitives.PopupPlacementMode DesiredPlacement;
        Microsoft.UI.Xaml.Controls.Primitives.PopupPlacementMode ActualPlacement{ get; };

        event Windows.Foundation.EventHandler<Object> ActualPlacementChanged;
    };
}
