namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[WUXC_VERSION_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass ScrollViewTestHooks
{
    static Windows.Foundation.IReference<Boolean> GetAutoHideScrollControllers(MU_XC_NAMESPACE.ScrollView scrollView);
    static void SetAutoHideScrollControllers(MU_XC_NAMESPACE.ScrollView scrollView, Windows.Foundation.IReference<Boolean> value);

    static MU_XCP_NAMESPACE.ScrollPresenter GetScrollPresenterPart(MU_XC_NAMESPACE.ScrollView scrollView);
}

}
