namespace MU_PRIVATE_MEDIA_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
runtimeclass RevealTestApi : Windows.UI.Xaml.DependencyObject
{
    RevealTestApi();

    Windows.UI.Xaml.ApplicationTheme TargetTheme { get; set; };
    Windows.UI.Composition.SpotLight BackgroundLight { get; };
    Windows.UI.Xaml.Media.XamlLight BorderLight { get; };
    Windows.UI.Xaml.Media.XamlLight BorderWideLight { get; };
    Double BackgroundLightMinSize { get; set; };
    Double BackgroundLightMaxSize { get; set; };
    Windows.UI.Composition.SpotLight GetSpotLight(Windows.UI.Xaml.Media.XamlLight value);
    Windows.UI.Composition.ExpressionAnimation GetHoverLightOffsetExpression(RevealHoverLight value);
    RevealBorderLight GetAsRevealBorderLight(Windows.UI.Xaml.Media.XamlLight value);
    RevealHoverLight GetAsRevealHoverLight(Windows.UI.Xaml.Media.XamlLight value);
    Boolean BorderLight_ShouldBeOn(RevealBorderLight value);
#ifdef BUILD_WINDOWS
    Windows.UI.Composition.CompositionLight GetSharedLight(RevealBorderLight value);
    Boolean BorderLight_FallbackToLocalLight(RevealBorderLight value);
#endif
    Boolean HoverLight_ShouldBeOn(RevealHoverLight value);
    Boolean HoverLight_IsPressed(RevealHoverLight value);
    Boolean HoverLight_IsPointerOver(RevealHoverLight value);
}

}
