namespace MU_XCP_NAMESPACE
{

[bindable]
[WUXC_VERSION_PREVIEW]
[webhosthidden]
[default_interface]
runtimeclass CornerRadiusFilterConverter : Windows.UI.Xaml.Data.IValueConverter
{
    CornerRadiusFilterConverter();
};

}
