namespace MU_XCP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
[default_interface]
runtimeclass CornerRadiusFilterConverter : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.IValueConverter
{
    CornerRadiusFilterConverter();

    [MUX_DEFAULT_VALUE("winrt::CornerRadiusFilterKind::None")]
    CornerRadiusFilterKind Filter{ get; set; };
    [MUX_DEFAULT_VALUE("1.0")]
    Double Scale{ get; set; };

    static Windows.UI.Xaml.DependencyProperty FilterProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ScaleProperty{ get; };
};

[MUX_PUBLIC]
[webhosthidden]
enum CornerRadiusFilterKind
{
    None,
    Top,
    Right,
    Bottom,
    Left,
    TopLeftValue,
    BottomRightValue
};

}
