namespace MU_XCP_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
[default_interface]
runtimeclass CornerRadiusFilterConverter : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.IValueConverter
{
    CornerRadiusFilterConverter();

    [MUX_DEFAULT_VALUE("winrt::CornerRadiusFilterKind::None")]
    CornerRadiusFilterKind Filter{ get; set; };

    [MUX_DEFAULT_VALUE("false")]
    Boolean ReturnAsDouble{ get; set; };

    static Windows.UI.Xaml.DependencyProperty FilterProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty ReturnAsDoubleProperty{ get; };
};

[WUXC_VERSION_MUXONLY]
[webhosthidden]
enum CornerRadiusFilterKind
{
    None,
    Top,
    Right,
    Bottom,
    Left,
    TopLeft,
    BottomRight
};

}
