namespace MU_XCP_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
[default_interface]
runtimeclass CornerRadiusToFilteredMultipliedThicknessConverter : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.IValueConverter
{
    CornerRadiusToFilteredMultipliedThicknessConverter();

    [MUX_DEFAULT_VALUE("winrt::CornerRadiusToThicknessSide::Left")]
    CornerRadiusToThicknessSide Side{ get; set; };

    [MUX_DEFAULT_VALUE("1.0f")]
    Double Multiplier{ get; set; };

    static Windows.UI.Xaml.DependencyProperty SideProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MultiplierProperty{ get; };
};

[WUXC_VERSION_PREVIEW]
[webhosthidden]
enum CornerRadiusToThicknessSide
{
    Left,
    Top,
    Right,
    Bottom,
    All
};

}
