namespace MU_XCP_NAMESPACE
{

[WUXC_VERSION_MUXONLY]
[webhosthidden]
[default_interface]
runtimeclass CornerRadiusToThicknessConverter : Windows.UI.Xaml.DependencyObject, Windows.UI.Xaml.Data.IValueConverter
{
    CornerRadiusToThicknessConverter();

    [MUX_DEFAULT_VALUE("winrt::CornerRadiusToThicknessConverterKind::FilterLeftAndRightFromTop")]
    CornerRadiusToThicknessConverterKind  ConversionKind{ get; set; };
    [MUX_DEFAULT_VALUE("1.0f")]
    Double Multiplier{ get; set; };

    static Windows.UI.Xaml.DependencyProperty ConversionKindProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty MultiplierProperty{ get; };
};

[WUXC_VERSION_MUXONLY]
[webhosthidden]
enum CornerRadiusToThicknessConverterKind
{
    FilterTopAndBottomFromLeft,
    FilterTopAndBottomFromRight,
    FilterLeftAndRightFromTop,
    FilterLeftAndRightFromBottom,
    FilterTopFromTopLeft,
    FilterTopFromTopRight,
    FilterRightFromTopRight,
    FilterRightFromBottomRight,
    FilterBottomFromBottomRight,
    FilterBottomFromBottomLeft,
    FilterLeftFromBottomLeft,
    FilterLeftFromTopLeft,
};

}
