namespace MU_XAP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass BreadcrumbBarItemAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer,
Microsoft.UI.Xaml.Automation.Provider.IInvokeProvider
{
    BreadcrumbBarItemAutomationPeer(MU_XC_NAMESPACE.BreadcrumbBarItem owner);
}

}
