namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass SliderInteraction : 
//#ifdef USE_INTERNAL_SDK
//Windows.UI.Xaml.InteractionBase,
//#else
Windows.UI.Xaml.DependencyObject,
//#endif 
Windows.UI.Xaml.Data.INotifyPropertyChanged
{
    SliderInteraction();

    Windows.UI.Xaml.Controls.Orientation Orientation { get; set; };
    Double Minimum { get; set; };
    Double Maximum { get; set; };
    Double Position { get; };
    Double SmallChange { get; set; };
    Double LargeChange { get; set; };
}

}
