namespace MU_XC_NAMESPACE
{

runtimeclass SwipeItems;
runtimeclass SwipeControl;
runtimeclass SwipeItemInvokedEventArgs;
runtimeclass SwipeItem;

[MUX_PUBLIC]
[webhosthidden]
enum SwipeBehaviorOnInvoked
{
    Auto = 0,
    Close = 1,
    RemainOpen = 2,
};

[MUX_PUBLIC]
[webhosthidden]
enum SwipeMode
{
    Reveal = 0,
    Execute = 1,
};

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass SwipeItems : Windows.UI.Xaml.DependencyObject, Windows.Foundation.Collections.IVector<SwipeItem>
{
    SwipeItems();

    [MUX_DEFAULT_VALUE("winrt::SwipeMode::Reveal")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    SwipeMode Mode { get; set; };

    static Windows.UI.Xaml.DependencyProperty ModeProperty { get; };
}

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass SwipeControl : Windows.UI.Xaml.Controls.ContentControl
{
    SwipeControl();

    SwipeItems LeftItems { get; set; };
    SwipeItems RightItems { get; set; };
    SwipeItems TopItems { get; set; };
    SwipeItems BottomItems { get; set; };
    void Close();

    static Windows.UI.Xaml.DependencyProperty LeftItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty RightItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TopItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BottomItemsProperty { get; };
}

[MUX_PUBLIC]
[webhosthidden]
runtimeclass SwipeItemInvokedEventArgs
{
    SwipeControl SwipeControl { get; };
}

[MUX_PUBLIC]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass SwipeItem : Windows.UI.Xaml.DependencyObject
{
    SwipeItem();

    String Text { get; set; };
    IconSource IconSource { get; set; };
    Windows.UI.Xaml.Media.Brush Background { get; set; };
    Windows.UI.Xaml.Media.Brush Foreground { get; set; };
    Windows.UI.Xaml.Input.ICommand Command { get; set; };
    Object CommandParameter { get; set; };
    [MUX_DEFAULT_VALUE("winrt::SwipeBehaviorOnInvoked::Auto")]
    SwipeBehaviorOnInvoked BehaviorOnInvoked { get; set; };
    event Windows.Foundation.TypedEventHandler<SwipeItem, SwipeItemInvokedEventArgs> Invoked;

    static Windows.UI.Xaml.DependencyProperty IconSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TextProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BackgroundProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ForegroundProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CommandProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CommandParameterProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BehaviorOnInvokedProperty { get; };
}

}