runtimeclass SwipeItems;
runtimeclass SwipeControl;
runtimeclass SwipeItemInvokedEventArgs;
runtimeclass SwipeItem;

[WUXC_VERSION_RS3]
[webhosthidden]
enum SwipeBehaviorOnInvoked
{
    Auto = 0,
    Close = 1,
    RemainOpen = 2,
};

[WUXC_VERSION_RS3]
[webhosthidden]
enum SwipeMode
{
    Reveal = 0,
    Execute = 1,
};

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("ISwipeItems", b01726ff-969a-40d0-9f04-76084ce6d7b7)]
[WUXC_STATIC_NAME("ISwipeItemsStatics", 376250df-48db-43e3-b0e9-089e5da9a114)]
[WUXC_CONSTRUCTOR_NAME("ISwipeItemsFactory", 47c460ee-d5aa-445f-b31e-50c076c011b9)]
unsealed runtimeclass SwipeItems : Windows.UI.Xaml.DependencyObject, Windows.Foundation.Collections.IVector<SwipeItem>
{
    SwipeItems();

    [MUX_DEFAULT_VALUE("winrt::SwipeMode::Reveal")]
    [MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
    SwipeMode Mode { get; set; };

    static Windows.UI.Xaml.DependencyProperty ModeProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("ISwipeControl", 9ee3d96f-6704-4823-aa15-1c143bc53cf7)]
[WUXC_STATIC_NAME("ISwipeControlStatics", e57ae83c-2216-4717-9ef6-4662334c6501)]
[WUXC_CONSTRUCTOR_NAME("ISwipeControlFactory", c0aaa3ae-d141-4e12-a728-5f95b507e7ab)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass SwipeControl : Windows.UI.Xaml.Controls.ContentControl
{
    SwipeControl();

    SwipeItems LeftItems { get; set; };
    SwipeItems RightItems { get; set; };
    SwipeItems TopItems { get; set; };
    SwipeItems BottomItems { get; set; };
    void Close();

    static Windows.UI.Xaml.DependencyProperty LeftItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty RightItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TopItemsProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BottomItemsProperty { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("ISwipeItemInvokedEventArgs", c5b025f5-cb32-4733-8011-5d0d37f4550a)]
runtimeclass SwipeItemInvokedEventArgs
{
    SwipeControl SwipeControl { get; };
}

[WUXC_VERSION_RS3]
[webhosthidden]
[WUXC_INTERFACE_NAME("ISwipeItem", 836edadc-45c8-4a00-90a0-7107fa894a1b)]
[WUXC_STATIC_NAME("ISwipeItemStatics", d0b44e96-2766-4d93-b5db-f5e1be832c2d)]
[WUXC_CONSTRUCTOR_NAME("ISwipeItemFactory", 844bd61a-1716-4097-bba2-7526da22de39)]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
unsealed runtimeclass SwipeItem : Windows.UI.Xaml.DependencyObject
{
    SwipeItem();

    String Text { get; set; };
    IconSource IconSource { get; set; };
    Windows.UI.Xaml.Media.Brush Background { get; set; };
    Windows.UI.Xaml.Media.Brush Foreground { get; set; };
    Windows.UI.Xaml.Input.ICommand Command { get; set; };
    Object CommandParameter { get; set; };
    [MUX_DEFAULT_VALUE("winrt::SwipeBehaviorOnInvoked::Auto")]
    SwipeBehaviorOnInvoked BehaviorOnInvoked { get; set; };
    event Windows.Foundation.TypedEventHandler<SwipeItem, SwipeItemInvokedEventArgs> Invoked;

    static Windows.UI.Xaml.DependencyProperty IconSourceProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TextProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BackgroundProperty { get; };
    static Windows.UI.Xaml.DependencyProperty ForegroundProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CommandProperty { get; };
    static Windows.UI.Xaml.DependencyProperty CommandParameterProperty { get; };
    static Windows.UI.Xaml.DependencyProperty BehaviorOnInvokedProperty { get; };
}
