<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <!--Xaml Compiler now supports any PCH or no PCH.
        But C++/WinRT does not yet support no PCH, falling back to "pch.h"-->
        <!--<UsingPrecompiledHeader>false</UsingPrecompiledHeader>-->
    </PropertyGroup>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />    
</Project>
