namespace MU_XCP_NAMESPACE
{

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass NavigationViewItemPresenter : Windows.UI.Xaml.Controls.ContentControl
{
    NavigationViewItemPresenter();

    Windows.UI.Xaml.Controls.IconElement Icon { get; set; };
    NavigationViewItemPresenterTemplateSettings TemplateSettings{ get; };

    static Windows.UI.Xaml.DependencyProperty IconProperty { get; };
    static Windows.UI.Xaml.DependencyProperty TemplateSettingsProperty{ get; };
}

[MUX_PUBLIC]
[webhosthidden]
unsealed runtimeclass NavigationViewItemPresenterTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    NavigationViewItemPresenterTemplateSettings();

    Double IconWidth{ get; };
    Double SmallerIconWidth{ get; };

    static Windows.UI.Xaml.DependencyProperty IconWidthProperty{ get; };
    static Windows.UI.Xaml.DependencyProperty SmallerIconWidthProperty{ get; };

}

}
