[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass NavigationViewItemPresenterTemplateSettings : Windows.UI.Xaml.DependencyObject
{
    NavigationViewItemPresenterTemplateSettings();

    Windows.UI.Xaml.Thickness Indentation{ get; };
    static Windows.UI.Xaml.DependencyProperty IndentationProperty{ get; };
}

[WUXC_VERSION_RS5]
[webhosthidden]
unsealed runtimeclass NavigationViewItemPresenter : Windows.UI.Xaml.Controls.ContentControl
{
    NavigationViewItemPresenter();

    Windows.UI.Xaml.Controls.IconElement Icon { get; set; };
    static Windows.UI.Xaml.DependencyProperty IconProperty { get; };

    [WUXC_VERSION_PREVIEW]
    {
        NavigationViewItemPresenterTemplateSettings TemplateSettings{ get; };
        static Windows.UI.Xaml.DependencyProperty TemplateSettingsProperty{ get; };
    }
}
