namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[default_interface]
[webhosthidden]
runtimeclass RadioButtonsTestHooks
{
    static void SetTestHooksEnabled(MU_XC_NAMESPACE.RadioButtons radioButtons, Boolean enabled);

    static Int32 GetRows(MU_XC_NAMESPACE.RadioButtons radioButtons);
    static Int32 GetColumns(MU_XC_NAMESPACE.RadioButtons radioButtons);
    static Int32 GetLargerColumns(MU_XC_NAMESPACE.RadioButtons radioButtons);

    static event Windows.Foundation.TypedEventHandler<MU_XC_NAMESPACE.RadioButtons, Object> LayoutChanged;
}

}
