//  Copyright (c) Microsoft Corporation. All rights reserved.
//
//  WindowsRuntimeAPISet
//------------------------------------------------------------------------
//
//  Abstract:
//
//      XAML framework interfaces.
//
//------------------------------------------------------------------------

#include "sdkddkver.h"

import "Microsoft.UI.Xaml.controls.controls.idl";
import "Microsoft.UI.Xaml.controls.controls2.idl";
import "windows.ui.xaml.interop.idl";

namespace Microsoft.UI.Xaml
{
    declare
    {
        interface IIterable<Microsoft.UI.Xaml.Controls.CalendarViewDayItem*>;
        interface IVector<Microsoft.UI.Xaml.Controls.CalendarViewDayItem*>;
        interface IObservableVector<Single>;
        interface IObservableVector<Windows.Foundation.DateTime>;
        interface IObservableVector<Windows.UI.Color>;
        interface IVector<Windows.UI.Color>;
        interface IIterable<Microsoft.UI.Xaml.Media.CompositeTransform*>;
        interface IIterator<Microsoft.UI.Xaml.Controls.HubSection*>;
        interface IObservableVector<Microsoft.UI.Xaml.Controls.HubSection*>;
        interface IVector<Microsoft.UI.Xaml.Automation.Peers.ItemAutomationPeer>;
        interface IVector<Microsoft.UI.Xaml.Automation.Provider.IRawElementProviderSimple>;
        interface IVector<Microsoft.UI.Xaml.Controls.Primitives.Popup*>;
        interface IVector<Microsoft.UI.Xaml.DependencyObject>;
        interface IVector<Microsoft.UI.Xaml.Input.Pointer>;
        interface IVector<Microsoft.UI.Xaml.Media.Animation.Storyboard>;
        interface IVector<Microsoft.UI.Xaml.Media.CompositeTransform*>;
        interface IVector<Microsoft.UI.Xaml.Data.ItemIndexRange*>;
        interface IVector<Microsoft.UI.Xaml.Controls.ContentDialog*>;
        interface IIterator<Microsoft.UI.Xaml.Controls.ContentDialog*>;
        interface IIterable<Microsoft.UI.Xaml.XamlRoot*>;
        interface IVector<Microsoft.UI.Xaml.XamlRoot*>;
        interface IVector<IKeyValuePair<IInspectable*, IInspectable*>*>;
        interface IVectorView<IKeyValuePair<IInspectable*, IInspectable*>*>;
        interface IVector<Microsoft.UI.Xaml.Window*>;
        interface IVectorView<Microsoft.UI.Xaml.Window*>;

        interface Windows.Foundation.IReference<HSTRING>;
        interface Windows.Foundation.IReference<WCHAR>;
        interface Windows.Foundation.IReference<Windows.Globalization.DayOfWeek>;
        interface Windows.Foundation.IReference<Microsoft.UI.Input.PointerDeviceType>;
        interface Windows.Foundation.IReference<Windows.Foundation.Collections.CollectionChange>;
        interface Windows.Foundation.IReference<Windows.Foundation.Numerics.Matrix3x2>;
        interface Windows.Foundation.IReference<Windows.System.VirtualKey>;
        interface Windows.Foundation.IReference<Windows.System.VirtualKeyModifiers>;
        interface Windows.Foundation.IReference<Windows.Media.Playback.FailedMediaStreamKind>;
        interface Windows.Foundation.IReference<Windows.UI.Core.CorePhysicalKeyStatus>;
        interface Windows.Foundation.IReference<Microsoft.UI.Input.HoldingState>;
        interface Windows.Foundation.IReference<Windows.UI.Text.FontWeight>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Controls.Primitives.GeneratorPosition>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.DependencyPropertyChangedCallback>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.CornerRadius>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Data.LoadMoreItemsResult>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Documents.TextRange>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Duration>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.GridLength>;
        interface Windows.Foundation.IReference<Windows.UI.Xaml.Interop.TypeName>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Media.Animation.KeyTime>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Media.Animation.RepeatBehavior>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Media.Matrix>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Media.Media3D.Matrix3D>;
        interface Windows.Foundation.IReference<Microsoft.UI.Xaml.Thickness>;
        interface Windows.Foundation.IReference<Windows.ApplicationModel.DataTransfer.DataPackageOperation>;
        interface Windows.Foundation.IReference<Windows.UI.Core.CoreCursorType>;
        interface Windows.Foundation.IReference<Windows.Foundation.TypedEventHandler<Windows.Media.Playback.MediaPlaybackList*, IInspectable*>*>;
    };
}
