namespace MU_XC_NAMESPACE
{

[MUX_PREVIEW]
[webhosthidden]
[MUX_PROPERTY_CHANGED_CALLBACK(TRUE)]
[MUX_PROPERTY_CHANGED_CALLBACK_METHODNAME("OnPropertyChanged")]
unsealed runtimeclass NEWCONTROL : Microsoft.UI.Xaml.Controls.Control
{
    NEWCONTROL();

    Object Placeholder{ get; set; };

    static Microsoft.UI.Xaml.DependencyProperty PlaceholderProperty{ get; };
}

}