interface IRepeaterScrollingSurface;

[WUXC_VERSION_INTERNAL]
[webhosthidden]
delegate void ConfigurationChangedEventHandler(IRepeaterScrollingSurface sender);

[WUXC_VERSION_INTERNAL]
[webhosthidden]
delegate void PostArrangeEventHandler(IRepeaterScrollingSurface sender);

[WUXC_VERSION_INTERNAL]
[webhosthidden]
delegate void ViewportChangedEventHandler(IRepeaterScrollingSurface sender, Boolean isFinal);

[WUXC_VERSION_INTERNAL]
[webhosthidden]
interface IRepeaterScrollingSurface
{
    Boolean IsHorizontallyScrollable { get; };
    Boolean IsVerticallyScrollable { get; };
    Windows.UI.Xaml.UIElement AnchorElement { get; };
    event ConfigurationChangedEventHandler ConfigurationChanged;
    event PostArrangeEventHandler PostArrange;
    event ViewportChangedEventHandler ViewportChanged;
    void RegisterAnchorCandidate(Windows.UI.Xaml.UIElement element);
    void UnregisterAnchorCandidate(Windows.UI.Xaml.UIElement element);
    Windows.Foundation.Rect GetRelativeViewport(Windows.UI.Xaml.UIElement child);
}