[WUXC_VERSION_PREVIEW]
[webhosthidden]
unsealed runtimeclass RepeaterAutomationPeer : Windows.UI.Xaml.Automation.Peers.FrameworkElementAutomationPeer
{
    RepeaterAutomationPeer(ItemsRepeater owner);
}
