namespace MU_PRIVATE_CONTROLS_NAMESPACE
{

[MUX_INTERNAL]
[webhosthidden]
[default_interface]
runtimeclass RepeaterTestHooks
{
    static event Windows.Foundation.TypedEventHandler<Object, Object> BuildTreeCompleted;

    static Int32 GetElementFactoryElementIndex(Object getArgs);
    static Object CreateRepeaterElementFactoryGetArgs();
    static Object CreateRepeaterElementFactoryRecycleArgs();

    static String GetLayoutId(Object layout);
    static void SetLayoutId(Object layout, String id);
}

}