<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) Microsoft Corporation.
 Licensed under the MIT License. -->
<Project>
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.0.1" />

  <PropertyGroup>
    <TargetFramework>$(DotNetCoreTargetFrameworkMoniker)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsAppSdkTargetPlatformVersion)</TargetPlatformMinVersion>
    <CsWinRTComponent>true</CsWinRTComponent>
    <UseWinUI>true</UseWinUI>
    <!-- Enabling Single-project MSIX Packaging allows the project to be built using `dotnet build` -->
    <EnableMsixTooling>true</EnableMsixTooling>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" />
  </ItemGroup>
</Project>